/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbChaebun implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String seqId;
    private final LocalDateTime createDate;
    private final String createUser;
    private final String sts;
    private final LocalDateTime timestamp;
    private final String updateUser;
    private final Integer currentValue;
    private final String dateformat;
    private final Integer length;
    private final String prefix;
    private final String seqName;
    private final Integer step;
    private final String pattern;

    public TbChaebun(TbChaebun value) {
        this.seqId = value.seqId;
        this.createDate = value.createDate;
        this.createUser = value.createUser;
        this.sts = value.sts;
        this.timestamp = value.timestamp;
        this.updateUser = value.updateUser;
        this.currentValue = value.currentValue;
        this.dateformat = value.dateformat;
        this.length = value.length;
        this.prefix = value.prefix;
        this.seqName = value.seqName;
        this.step = value.step;
        this.pattern = value.pattern;
    }

    public TbChaebun(
        String seqId,
        LocalDateTime createDate,
        String createUser,
        String sts,
        LocalDateTime timestamp,
        String updateUser,
        Integer currentValue,
        String dateformat,
        Integer length,
        String prefix,
        String seqName,
        Integer step,
        String pattern
    ) {
        this.seqId = seqId;
        this.createDate = createDate;
        this.createUser = createUser;
        this.sts = sts;
        this.timestamp = timestamp;
        this.updateUser = updateUser;
        this.currentValue = currentValue;
        this.dateformat = dateformat;
        this.length = length;
        this.prefix = prefix;
        this.seqName = seqName;
        this.step = step;
        this.pattern = pattern;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_CHAEBUN.SEQ_ID</code>.
     */
    public String getSeqId() {
        return this.seqId;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_CHAEBUN.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_CHAEBUN.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_CHAEBUN.STS</code>.
     */
    public String getSts() {
        return this.sts;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_CHAEBUN.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_CHAEBUN.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_CHAEBUN.CURRENT_VALUE</code>.
     */
    public Integer getCurrentValue() {
        return this.currentValue;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_CHAEBUN.DATEFORMAT</code>.
     */
    public String getDateformat() {
        return this.dateformat;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_CHAEBUN.LENGTH</code>.
     */
    public Integer getLength() {
        return this.length;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_CHAEBUN.PREFIX</code>.
     */
    public String getPrefix() {
        return this.prefix;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_CHAEBUN.SEQ_NAME</code>.
     */
    public String getSeqName() {
        return this.seqName;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_CHAEBUN.STEP</code>.
     */
    public Integer getStep() {
        return this.step;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_CHAEBUN.PATTERN</code>.
     */
    public String getPattern() {
        return this.pattern;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbChaebun other = (TbChaebun) obj;
        if (this.seqId == null) {
            if (other.seqId != null)
                return false;
        }
        else if (!this.seqId.equals(other.seqId))
            return false;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.sts == null) {
            if (other.sts != null)
                return false;
        }
        else if (!this.sts.equals(other.sts))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.updateUser == null) {
            if (other.updateUser != null)
                return false;
        }
        else if (!this.updateUser.equals(other.updateUser))
            return false;
        if (this.currentValue == null) {
            if (other.currentValue != null)
                return false;
        }
        else if (!this.currentValue.equals(other.currentValue))
            return false;
        if (this.dateformat == null) {
            if (other.dateformat != null)
                return false;
        }
        else if (!this.dateformat.equals(other.dateformat))
            return false;
        if (this.length == null) {
            if (other.length != null)
                return false;
        }
        else if (!this.length.equals(other.length))
            return false;
        if (this.prefix == null) {
            if (other.prefix != null)
                return false;
        }
        else if (!this.prefix.equals(other.prefix))
            return false;
        if (this.seqName == null) {
            if (other.seqName != null)
                return false;
        }
        else if (!this.seqName.equals(other.seqName))
            return false;
        if (this.step == null) {
            if (other.step != null)
                return false;
        }
        else if (!this.step.equals(other.step))
            return false;
        if (this.pattern == null) {
            if (other.pattern != null)
                return false;
        }
        else if (!this.pattern.equals(other.pattern))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.seqId == null) ? 0 : this.seqId.hashCode());
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.sts == null) ? 0 : this.sts.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.updateUser == null) ? 0 : this.updateUser.hashCode());
        result = prime * result + ((this.currentValue == null) ? 0 : this.currentValue.hashCode());
        result = prime * result + ((this.dateformat == null) ? 0 : this.dateformat.hashCode());
        result = prime * result + ((this.length == null) ? 0 : this.length.hashCode());
        result = prime * result + ((this.prefix == null) ? 0 : this.prefix.hashCode());
        result = prime * result + ((this.seqName == null) ? 0 : this.seqName.hashCode());
        result = prime * result + ((this.step == null) ? 0 : this.step.hashCode());
        result = prime * result + ((this.pattern == null) ? 0 : this.pattern.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbChaebun (");

        sb.append(seqId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createUser);
        sb.append(", ").append(sts);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(currentValue);
        sb.append(", ").append(dateformat);
        sb.append(", ").append(length);
        sb.append(", ").append(prefix);
        sb.append(", ").append(seqName);
        sb.append(", ").append(step);
        sb.append(", ").append(pattern);

        sb.append(")");
        return sb.toString();
    }
}
