/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbComCodeM implements Serializable {

    private static final long serialVersionUID = 1L;

    private final LocalDateTime createDate;
    private final LocalDateTime timestamp;
    private final String createUser;
    private final String grpCd;
    private final String grpCdType;
    private final String updateUser;
    private final String grpNm;
    private final String sts;

    public TbComCodeM(TbComCodeM value) {
        this.createDate = value.createDate;
        this.timestamp = value.timestamp;
        this.createUser = value.createUser;
        this.grpCd = value.grpCd;
        this.grpCdType = value.grpCdType;
        this.updateUser = value.updateUser;
        this.grpNm = value.grpNm;
        this.sts = value.sts;
    }

    public TbComCodeM(
        LocalDateTime createDate,
        LocalDateTime timestamp,
        String createUser,
        String grpCd,
        String grpCdType,
        String updateUser,
        String grpNm,
        String sts
    ) {
        this.createDate = createDate;
        this.timestamp = timestamp;
        this.createUser = createUser;
        this.grpCd = grpCd;
        this.grpCdType = grpCdType;
        this.updateUser = updateUser;
        this.grpNm = grpNm;
        this.sts = sts;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_M.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_M.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_M.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_M.GRP_CD</code>.
     */
    public String getGrpCd() {
        return this.grpCd;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_M.GRP_CD_TYPE</code>.
     */
    public String getGrpCdType() {
        return this.grpCdType;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_M.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_M.GRP_NM</code>.
     */
    public String getGrpNm() {
        return this.grpNm;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_M.STS</code>.
     */
    public String getSts() {
        return this.sts;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbComCodeM other = (TbComCodeM) obj;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.grpCd == null) {
            if (other.grpCd != null)
                return false;
        }
        else if (!this.grpCd.equals(other.grpCd))
            return false;
        if (this.grpCdType == null) {
            if (other.grpCdType != null)
                return false;
        }
        else if (!this.grpCdType.equals(other.grpCdType))
            return false;
        if (this.updateUser == null) {
            if (other.updateUser != null)
                return false;
        }
        else if (!this.updateUser.equals(other.updateUser))
            return false;
        if (this.grpNm == null) {
            if (other.grpNm != null)
                return false;
        }
        else if (!this.grpNm.equals(other.grpNm))
            return false;
        if (this.sts == null) {
            if (other.sts != null)
                return false;
        }
        else if (!this.sts.equals(other.sts))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.grpCd == null) ? 0 : this.grpCd.hashCode());
        result = prime * result + ((this.grpCdType == null) ? 0 : this.grpCdType.hashCode());
        result = prime * result + ((this.updateUser == null) ? 0 : this.updateUser.hashCode());
        result = prime * result + ((this.grpNm == null) ? 0 : this.grpNm.hashCode());
        result = prime * result + ((this.sts == null) ? 0 : this.sts.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbComCodeM (");

        sb.append(createDate);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(createUser);
        sb.append(", ").append(grpCd);
        sb.append(", ").append(grpCdType);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(grpNm);
        sb.append(", ").append(sts);

        sb.append(")");
        return sb.toString();
    }
}
