/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbComCodeD implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String dtlCd;
    private final LocalDateTime createDate;
    private final String createUser;
    private final String sts;
    private final LocalDateTime timestamp;
    private final String updateUser;
    private final String dtlNm;
    private final Integer orderNum;
    private final String useYn;
    private final String attrCd;
    private final String grpCd;

    public TbComCodeD(TbComCodeD value) {
        this.dtlCd = value.dtlCd;
        this.createDate = value.createDate;
        this.createUser = value.createUser;
        this.sts = value.sts;
        this.timestamp = value.timestamp;
        this.updateUser = value.updateUser;
        this.dtlNm = value.dtlNm;
        this.orderNum = value.orderNum;
        this.useYn = value.useYn;
        this.attrCd = value.attrCd;
        this.grpCd = value.grpCd;
    }

    public TbComCodeD(
        String dtlCd,
        LocalDateTime createDate,
        String createUser,
        String sts,
        LocalDateTime timestamp,
        String updateUser,
        String dtlNm,
        Integer orderNum,
        String useYn,
        String attrCd,
        String grpCd
    ) {
        this.dtlCd = dtlCd;
        this.createDate = createDate;
        this.createUser = createUser;
        this.sts = sts;
        this.timestamp = timestamp;
        this.updateUser = updateUser;
        this.dtlNm = dtlNm;
        this.orderNum = orderNum;
        this.useYn = useYn;
        this.attrCd = attrCd;
        this.grpCd = grpCd;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_D.DTL_CD</code>.
     */
    public String getDtlCd() {
        return this.dtlCd;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_D.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_D.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_D.STS</code>.
     */
    public String getSts() {
        return this.sts;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_D.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_D.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_D.DTL_NM</code>.
     */
    public String getDtlNm() {
        return this.dtlNm;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_D.ORDER_NUM</code>.
     */
    public Integer getOrderNum() {
        return this.orderNum;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_D.USE_YN</code>.
     */
    public String getUseYn() {
        return this.useYn;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_D.ATTR_CD</code>.
     */
    public String getAttrCd() {
        return this.attrCd;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_D.GRP_CD</code>.
     */
    public String getGrpCd() {
        return this.grpCd;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbComCodeD other = (TbComCodeD) obj;
        if (this.dtlCd == null) {
            if (other.dtlCd != null)
                return false;
        }
        else if (!this.dtlCd.equals(other.dtlCd))
            return false;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.sts == null) {
            if (other.sts != null)
                return false;
        }
        else if (!this.sts.equals(other.sts))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.updateUser == null) {
            if (other.updateUser != null)
                return false;
        }
        else if (!this.updateUser.equals(other.updateUser))
            return false;
        if (this.dtlNm == null) {
            if (other.dtlNm != null)
                return false;
        }
        else if (!this.dtlNm.equals(other.dtlNm))
            return false;
        if (this.orderNum == null) {
            if (other.orderNum != null)
                return false;
        }
        else if (!this.orderNum.equals(other.orderNum))
            return false;
        if (this.useYn == null) {
            if (other.useYn != null)
                return false;
        }
        else if (!this.useYn.equals(other.useYn))
            return false;
        if (this.attrCd == null) {
            if (other.attrCd != null)
                return false;
        }
        else if (!this.attrCd.equals(other.attrCd))
            return false;
        if (this.grpCd == null) {
            if (other.grpCd != null)
                return false;
        }
        else if (!this.grpCd.equals(other.grpCd))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.dtlCd == null) ? 0 : this.dtlCd.hashCode());
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.sts == null) ? 0 : this.sts.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.updateUser == null) ? 0 : this.updateUser.hashCode());
        result = prime * result + ((this.dtlNm == null) ? 0 : this.dtlNm.hashCode());
        result = prime * result + ((this.orderNum == null) ? 0 : this.orderNum.hashCode());
        result = prime * result + ((this.useYn == null) ? 0 : this.useYn.hashCode());
        result = prime * result + ((this.attrCd == null) ? 0 : this.attrCd.hashCode());
        result = prime * result + ((this.grpCd == null) ? 0 : this.grpCd.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbComCodeD (");

        sb.append(dtlCd);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createUser);
        sb.append(", ").append(sts);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(dtlNm);
        sb.append(", ").append(orderNum);
        sb.append(", ").append(useYn);
        sb.append(", ").append(attrCd);
        sb.append(", ").append(grpCd);

        sb.append(")");
        return sb.toString();
    }
}
