/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbComCodeTPivot implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String attrCd;
    private final String grpCd;
    private final LocalDateTime createDate;
    private final String createUser;
    private final String sts;
    private final LocalDateTime timestamp;
    private final String updateUser;
    private final String attrNm;
    private final Integer orderNum;

    public TbComCodeTPivot(TbComCodeTPivot value) {
        this.attrCd = value.attrCd;
        this.grpCd = value.grpCd;
        this.createDate = value.createDate;
        this.createUser = value.createUser;
        this.sts = value.sts;
        this.timestamp = value.timestamp;
        this.updateUser = value.updateUser;
        this.attrNm = value.attrNm;
        this.orderNum = value.orderNum;
    }

    public TbComCodeTPivot(
        String attrCd,
        String grpCd,
        LocalDateTime createDate,
        String createUser,
        String sts,
        LocalDateTime timestamp,
        String updateUser,
        String attrNm,
        Integer orderNum
    ) {
        this.attrCd = attrCd;
        this.grpCd = grpCd;
        this.createDate = createDate;
        this.createUser = createUser;
        this.sts = sts;
        this.timestamp = timestamp;
        this.updateUser = updateUser;
        this.attrNm = attrNm;
        this.orderNum = orderNum;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T_PIVOT.ATTR_CD</code>.
     */
    public String getAttrCd() {
        return this.attrCd;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T_PIVOT.GRP_CD</code>.
     */
    public String getGrpCd() {
        return this.grpCd;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T_PIVOT.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T_PIVOT.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T_PIVOT.STS</code>.
     */
    public String getSts() {
        return this.sts;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T_PIVOT.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T_PIVOT.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T_PIVOT.ATTR_NM</code>.
     */
    public String getAttrNm() {
        return this.attrNm;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T_PIVOT.ORDER_NUM</code>.
     */
    public Integer getOrderNum() {
        return this.orderNum;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbComCodeTPivot other = (TbComCodeTPivot) obj;
        if (this.attrCd == null) {
            if (other.attrCd != null)
                return false;
        }
        else if (!this.attrCd.equals(other.attrCd))
            return false;
        if (this.grpCd == null) {
            if (other.grpCd != null)
                return false;
        }
        else if (!this.grpCd.equals(other.grpCd))
            return false;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.sts == null) {
            if (other.sts != null)
                return false;
        }
        else if (!this.sts.equals(other.sts))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.updateUser == null) {
            if (other.updateUser != null)
                return false;
        }
        else if (!this.updateUser.equals(other.updateUser))
            return false;
        if (this.attrNm == null) {
            if (other.attrNm != null)
                return false;
        }
        else if (!this.attrNm.equals(other.attrNm))
            return false;
        if (this.orderNum == null) {
            if (other.orderNum != null)
                return false;
        }
        else if (!this.orderNum.equals(other.orderNum))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.attrCd == null) ? 0 : this.attrCd.hashCode());
        result = prime * result + ((this.grpCd == null) ? 0 : this.grpCd.hashCode());
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.sts == null) ? 0 : this.sts.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.updateUser == null) ? 0 : this.updateUser.hashCode());
        result = prime * result + ((this.attrNm == null) ? 0 : this.attrNm.hashCode());
        result = prime * result + ((this.orderNum == null) ? 0 : this.orderNum.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbComCodeTPivot (");

        sb.append(attrCd);
        sb.append(", ").append(grpCd);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createUser);
        sb.append(", ").append(sts);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(attrNm);
        sb.append(", ").append(orderNum);

        sb.append(")");
        return sb.toString();
    }
}
