/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbLogError implements Serializable {

    private static final long serialVersionUID = 1L;

    private final LocalDateTime createDate;
    private final LocalDateTime timestamp;
    private final String errId;
    private final String createUser;
    private final String httpMethod;
    private final String ipAddr;
    private final String updateUser;
    private final String userAgent;
    private final String userId;
    private final String requestUri;
    private final String errMsg;
    private final String sts;
    private final String errStack;

    public TbLogError(TbLogError value) {
        this.createDate = value.createDate;
        this.timestamp = value.timestamp;
        this.errId = value.errId;
        this.createUser = value.createUser;
        this.httpMethod = value.httpMethod;
        this.ipAddr = value.ipAddr;
        this.updateUser = value.updateUser;
        this.userAgent = value.userAgent;
        this.userId = value.userId;
        this.requestUri = value.requestUri;
        this.errMsg = value.errMsg;
        this.sts = value.sts;
        this.errStack = value.errStack;
    }

    public TbLogError(
        LocalDateTime createDate,
        LocalDateTime timestamp,
        String errId,
        String createUser,
        String httpMethod,
        String ipAddr,
        String updateUser,
        String userAgent,
        String userId,
        String requestUri,
        String errMsg,
        String sts,
        String errStack
    ) {
        this.createDate = createDate;
        this.timestamp = timestamp;
        this.errId = errId;
        this.createUser = createUser;
        this.httpMethod = httpMethod;
        this.ipAddr = ipAddr;
        this.updateUser = updateUser;
        this.userAgent = userAgent;
        this.userId = userId;
        this.requestUri = requestUri;
        this.errMsg = errMsg;
        this.sts = sts;
        this.errStack = errStack;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.ERR_ID</code>.
     */
    public String getErrId() {
        return this.errId;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.HTTP_METHOD</code>.
     */
    public String getHttpMethod() {
        return this.httpMethod;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.IP_ADDR</code>.
     */
    public String getIpAddr() {
        return this.ipAddr;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.USER_AGENT</code>.
     */
    public String getUserAgent() {
        return this.userAgent;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.USER_ID</code>.
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.REQUEST_URI</code>.
     */
    public String getRequestUri() {
        return this.requestUri;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.ERR_MSG</code>.
     */
    public String getErrMsg() {
        return this.errMsg;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.STS</code>.
     */
    public String getSts() {
        return this.sts;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.ERR_STACK</code>.
     */
    public String getErrStack() {
        return this.errStack;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbLogError other = (TbLogError) obj;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.errId == null) {
            if (other.errId != null)
                return false;
        }
        else if (!this.errId.equals(other.errId))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.httpMethod == null) {
            if (other.httpMethod != null)
                return false;
        }
        else if (!this.httpMethod.equals(other.httpMethod))
            return false;
        if (this.ipAddr == null) {
            if (other.ipAddr != null)
                return false;
        }
        else if (!this.ipAddr.equals(other.ipAddr))
            return false;
        if (this.updateUser == null) {
            if (other.updateUser != null)
                return false;
        }
        else if (!this.updateUser.equals(other.updateUser))
            return false;
        if (this.userAgent == null) {
            if (other.userAgent != null)
                return false;
        }
        else if (!this.userAgent.equals(other.userAgent))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.requestUri == null) {
            if (other.requestUri != null)
                return false;
        }
        else if (!this.requestUri.equals(other.requestUri))
            return false;
        if (this.errMsg == null) {
            if (other.errMsg != null)
                return false;
        }
        else if (!this.errMsg.equals(other.errMsg))
            return false;
        if (this.sts == null) {
            if (other.sts != null)
                return false;
        }
        else if (!this.sts.equals(other.sts))
            return false;
        if (this.errStack == null) {
            if (other.errStack != null)
                return false;
        }
        else if (!this.errStack.equals(other.errStack))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.errId == null) ? 0 : this.errId.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.httpMethod == null) ? 0 : this.httpMethod.hashCode());
        result = prime * result + ((this.ipAddr == null) ? 0 : this.ipAddr.hashCode());
        result = prime * result + ((this.updateUser == null) ? 0 : this.updateUser.hashCode());
        result = prime * result + ((this.userAgent == null) ? 0 : this.userAgent.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.requestUri == null) ? 0 : this.requestUri.hashCode());
        result = prime * result + ((this.errMsg == null) ? 0 : this.errMsg.hashCode());
        result = prime * result + ((this.sts == null) ? 0 : this.sts.hashCode());
        result = prime * result + ((this.errStack == null) ? 0 : this.errStack.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbLogError (");

        sb.append(createDate);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(errId);
        sb.append(", ").append(createUser);
        sb.append(", ").append(httpMethod);
        sb.append(", ").append(ipAddr);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(userAgent);
        sb.append(", ").append(userId);
        sb.append(", ").append(requestUri);
        sb.append(", ").append(errMsg);
        sb.append(", ").append(sts);
        sb.append(", ").append(errStack);

        sb.append(")");
        return sb.toString();
    }
}
