/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbLogAct implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String logId;
    private final LocalDateTime createDate;
    private final String createUser;
    private final String sts;
    private final LocalDateTime timestamp;
    private final String updateUser;
    private final String actionType;
    private final String actionTypeDetail;
    private final String ipAddr;
    private final String pageUrl;
    private final String userId;

    public TbLogAct(TbLogAct value) {
        this.logId = value.logId;
        this.createDate = value.createDate;
        this.createUser = value.createUser;
        this.sts = value.sts;
        this.timestamp = value.timestamp;
        this.updateUser = value.updateUser;
        this.actionType = value.actionType;
        this.actionTypeDetail = value.actionTypeDetail;
        this.ipAddr = value.ipAddr;
        this.pageUrl = value.pageUrl;
        this.userId = value.userId;
    }

    public TbLogAct(
        String logId,
        LocalDateTime createDate,
        String createUser,
        String sts,
        LocalDateTime timestamp,
        String updateUser,
        String actionType,
        String actionTypeDetail,
        String ipAddr,
        String pageUrl,
        String userId
    ) {
        this.logId = logId;
        this.createDate = createDate;
        this.createUser = createUser;
        this.sts = sts;
        this.timestamp = timestamp;
        this.updateUser = updateUser;
        this.actionType = actionType;
        this.actionTypeDetail = actionTypeDetail;
        this.ipAddr = ipAddr;
        this.pageUrl = pageUrl;
        this.userId = userId;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ACT.LOG_ID</code>.
     */
    public String getLogId() {
        return this.logId;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ACT.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ACT.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ACT.STS</code>.
     */
    public String getSts() {
        return this.sts;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ACT.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ACT.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ACT.ACTION_TYPE</code>.
     */
    public String getActionType() {
        return this.actionType;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ACT.ACTION_TYPE_DETAIL</code>.
     */
    public String getActionTypeDetail() {
        return this.actionTypeDetail;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ACT.IP_ADDR</code>.
     */
    public String getIpAddr() {
        return this.ipAddr;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ACT.PAGE_URL</code>.
     */
    public String getPageUrl() {
        return this.pageUrl;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ACT.USER_ID</code>.
     */
    public String getUserId() {
        return this.userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbLogAct other = (TbLogAct) obj;
        if (this.logId == null) {
            if (other.logId != null)
                return false;
        }
        else if (!this.logId.equals(other.logId))
            return false;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.sts == null) {
            if (other.sts != null)
                return false;
        }
        else if (!this.sts.equals(other.sts))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.updateUser == null) {
            if (other.updateUser != null)
                return false;
        }
        else if (!this.updateUser.equals(other.updateUser))
            return false;
        if (this.actionType == null) {
            if (other.actionType != null)
                return false;
        }
        else if (!this.actionType.equals(other.actionType))
            return false;
        if (this.actionTypeDetail == null) {
            if (other.actionTypeDetail != null)
                return false;
        }
        else if (!this.actionTypeDetail.equals(other.actionTypeDetail))
            return false;
        if (this.ipAddr == null) {
            if (other.ipAddr != null)
                return false;
        }
        else if (!this.ipAddr.equals(other.ipAddr))
            return false;
        if (this.pageUrl == null) {
            if (other.pageUrl != null)
                return false;
        }
        else if (!this.pageUrl.equals(other.pageUrl))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.logId == null) ? 0 : this.logId.hashCode());
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.sts == null) ? 0 : this.sts.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.updateUser == null) ? 0 : this.updateUser.hashCode());
        result = prime * result + ((this.actionType == null) ? 0 : this.actionType.hashCode());
        result = prime * result + ((this.actionTypeDetail == null) ? 0 : this.actionTypeDetail.hashCode());
        result = prime * result + ((this.ipAddr == null) ? 0 : this.ipAddr.hashCode());
        result = prime * result + ((this.pageUrl == null) ? 0 : this.pageUrl.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbLogAct (");

        sb.append(logId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createUser);
        sb.append(", ").append(sts);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(actionType);
        sb.append(", ").append(actionTypeDetail);
        sb.append(", ").append(ipAddr);
        sb.append(", ").append(pageUrl);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
