/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbMailM implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String mailId;
    private final LocalDateTime createDate;
    private final String createUser;
    private final String sts;
    private final LocalDateTime timestamp;
    private final String updateUser;
    private final String content;
    private final String description;
    private final String langType;
    private final String mailName;
    private final String title;

    public TbMailM(TbMailM value) {
        this.mailId = value.mailId;
        this.createDate = value.createDate;
        this.createUser = value.createUser;
        this.sts = value.sts;
        this.timestamp = value.timestamp;
        this.updateUser = value.updateUser;
        this.content = value.content;
        this.description = value.description;
        this.langType = value.langType;
        this.mailName = value.mailName;
        this.title = value.title;
    }

    public TbMailM(
        String mailId,
        LocalDateTime createDate,
        String createUser,
        String sts,
        LocalDateTime timestamp,
        String updateUser,
        String content,
        String description,
        String langType,
        String mailName,
        String title
    ) {
        this.mailId = mailId;
        this.createDate = createDate;
        this.createUser = createUser;
        this.sts = sts;
        this.timestamp = timestamp;
        this.updateUser = updateUser;
        this.content = content;
        this.description = description;
        this.langType = langType;
        this.mailName = mailName;
        this.title = title;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_M.MAIL_ID</code>.
     */
    public String getMailId() {
        return this.mailId;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_M.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_M.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_M.STS</code>.
     */
    public String getSts() {
        return this.sts;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_M.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_M.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_M.CONTENT</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_M.DESCRIPTION</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_M.LANG_TYPE</code>.
     */
    public String getLangType() {
        return this.langType;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_M.MAIL_NAME</code>.
     */
    public String getMailName() {
        return this.mailName;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_M.TITLE</code>.
     */
    public String getTitle() {
        return this.title;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbMailM other = (TbMailM) obj;
        if (this.mailId == null) {
            if (other.mailId != null)
                return false;
        }
        else if (!this.mailId.equals(other.mailId))
            return false;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.sts == null) {
            if (other.sts != null)
                return false;
        }
        else if (!this.sts.equals(other.sts))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.updateUser == null) {
            if (other.updateUser != null)
                return false;
        }
        else if (!this.updateUser.equals(other.updateUser))
            return false;
        if (this.content == null) {
            if (other.content != null)
                return false;
        }
        else if (!this.content.equals(other.content))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.langType == null) {
            if (other.langType != null)
                return false;
        }
        else if (!this.langType.equals(other.langType))
            return false;
        if (this.mailName == null) {
            if (other.mailName != null)
                return false;
        }
        else if (!this.mailName.equals(other.mailName))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.mailId == null) ? 0 : this.mailId.hashCode());
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.sts == null) ? 0 : this.sts.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.updateUser == null) ? 0 : this.updateUser.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.langType == null) ? 0 : this.langType.hashCode());
        result = prime * result + ((this.mailName == null) ? 0 : this.mailName.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbMailM (");

        sb.append(mailId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createUser);
        sb.append(", ").append(sts);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(content);
        sb.append(", ").append(description);
        sb.append(", ").append(langType);
        sb.append(", ").append(mailName);
        sb.append(", ").append(title);

        sb.append(")");
        return sb.toString();
    }
}
