/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbMailH implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String logId;
    private final LocalDateTime createDate;
    private final String createUser;
    private final String sts;
    private final LocalDateTime timestamp;
    private final String updateUser;
    private final String content;
    private final String errorMsg;
    private final String fromAddr;
    private final String mailId;
    private final String success;
    private final String title;
    private final String toAddr;

    public TbMailH(TbMailH value) {
        this.logId = value.logId;
        this.createDate = value.createDate;
        this.createUser = value.createUser;
        this.sts = value.sts;
        this.timestamp = value.timestamp;
        this.updateUser = value.updateUser;
        this.content = value.content;
        this.errorMsg = value.errorMsg;
        this.fromAddr = value.fromAddr;
        this.mailId = value.mailId;
        this.success = value.success;
        this.title = value.title;
        this.toAddr = value.toAddr;
    }

    public TbMailH(
        String logId,
        LocalDateTime createDate,
        String createUser,
        String sts,
        LocalDateTime timestamp,
        String updateUser,
        String content,
        String errorMsg,
        String fromAddr,
        String mailId,
        String success,
        String title,
        String toAddr
    ) {
        this.logId = logId;
        this.createDate = createDate;
        this.createUser = createUser;
        this.sts = sts;
        this.timestamp = timestamp;
        this.updateUser = updateUser;
        this.content = content;
        this.errorMsg = errorMsg;
        this.fromAddr = fromAddr;
        this.mailId = mailId;
        this.success = success;
        this.title = title;
        this.toAddr = toAddr;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_H.LOG_ID</code>.
     */
    public String getLogId() {
        return this.logId;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_H.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_H.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_H.STS</code>.
     */
    public String getSts() {
        return this.sts;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_H.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_H.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_H.CONTENT</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_H.ERROR_MSG</code>.
     */
    public String getErrorMsg() {
        return this.errorMsg;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_H.FROM_ADDR</code>.
     */
    public String getFromAddr() {
        return this.fromAddr;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_H.MAIL_ID</code>.
     */
    public String getMailId() {
        return this.mailId;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_H.SUCCESS</code>.
     */
    public String getSuccess() {
        return this.success;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_H.TITLE</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MAIL_H.TO_ADDR</code>.
     */
    public String getToAddr() {
        return this.toAddr;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbMailH other = (TbMailH) obj;
        if (this.logId == null) {
            if (other.logId != null)
                return false;
        }
        else if (!this.logId.equals(other.logId))
            return false;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.sts == null) {
            if (other.sts != null)
                return false;
        }
        else if (!this.sts.equals(other.sts))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.updateUser == null) {
            if (other.updateUser != null)
                return false;
        }
        else if (!this.updateUser.equals(other.updateUser))
            return false;
        if (this.content == null) {
            if (other.content != null)
                return false;
        }
        else if (!this.content.equals(other.content))
            return false;
        if (this.errorMsg == null) {
            if (other.errorMsg != null)
                return false;
        }
        else if (!this.errorMsg.equals(other.errorMsg))
            return false;
        if (this.fromAddr == null) {
            if (other.fromAddr != null)
                return false;
        }
        else if (!this.fromAddr.equals(other.fromAddr))
            return false;
        if (this.mailId == null) {
            if (other.mailId != null)
                return false;
        }
        else if (!this.mailId.equals(other.mailId))
            return false;
        if (this.success == null) {
            if (other.success != null)
                return false;
        }
        else if (!this.success.equals(other.success))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.toAddr == null) {
            if (other.toAddr != null)
                return false;
        }
        else if (!this.toAddr.equals(other.toAddr))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.logId == null) ? 0 : this.logId.hashCode());
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.sts == null) ? 0 : this.sts.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.updateUser == null) ? 0 : this.updateUser.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.errorMsg == null) ? 0 : this.errorMsg.hashCode());
        result = prime * result + ((this.fromAddr == null) ? 0 : this.fromAddr.hashCode());
        result = prime * result + ((this.mailId == null) ? 0 : this.mailId.hashCode());
        result = prime * result + ((this.success == null) ? 0 : this.success.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.toAddr == null) ? 0 : this.toAddr.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbMailH (");

        sb.append(logId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createUser);
        sb.append(", ").append(sts);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(content);
        sb.append(", ").append(errorMsg);
        sb.append(", ").append(fromAddr);
        sb.append(", ").append(mailId);
        sb.append(", ").append(success);
        sb.append(", ").append(title);
        sb.append(", ").append(toAddr);

        sb.append(")");
        return sb.toString();
    }
}
