/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbMenu implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String menuCd;
    private final LocalDateTime createDate;
    private final String createUser;
    private final String sts;
    private final LocalDateTime timestamp;
    private final String updateUser;
    private final Integer menuLv;
    private final String menuNm;
    private final String menuUrl;
    private final Integer orderNum;
    private final String useYn;
    private final String upperMenuCd;

    public TbMenu(TbMenu value) {
        this.menuCd = value.menuCd;
        this.createDate = value.createDate;
        this.createUser = value.createUser;
        this.sts = value.sts;
        this.timestamp = value.timestamp;
        this.updateUser = value.updateUser;
        this.menuLv = value.menuLv;
        this.menuNm = value.menuNm;
        this.menuUrl = value.menuUrl;
        this.orderNum = value.orderNum;
        this.useYn = value.useYn;
        this.upperMenuCd = value.upperMenuCd;
    }

    public TbMenu(
        String menuCd,
        LocalDateTime createDate,
        String createUser,
        String sts,
        LocalDateTime timestamp,
        String updateUser,
        Integer menuLv,
        String menuNm,
        String menuUrl,
        Integer orderNum,
        String useYn,
        String upperMenuCd
    ) {
        this.menuCd = menuCd;
        this.createDate = createDate;
        this.createUser = createUser;
        this.sts = sts;
        this.timestamp = timestamp;
        this.updateUser = updateUser;
        this.menuLv = menuLv;
        this.menuNm = menuNm;
        this.menuUrl = menuUrl;
        this.orderNum = orderNum;
        this.useYn = useYn;
        this.upperMenuCd = upperMenuCd;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MENU.MENU_CD</code>.
     */
    public String getMenuCd() {
        return this.menuCd;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MENU.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MENU.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MENU.STS</code>.
     */
    public String getSts() {
        return this.sts;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MENU.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MENU.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MENU.MENU_LV</code>.
     */
    public Integer getMenuLv() {
        return this.menuLv;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MENU.MENU_NM</code>.
     */
    public String getMenuNm() {
        return this.menuNm;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MENU.MENU_URL</code>.
     */
    public String getMenuUrl() {
        return this.menuUrl;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MENU.ORDER_NUM</code>.
     */
    public Integer getOrderNum() {
        return this.orderNum;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MENU.USE_YN</code>.
     */
    public String getUseYn() {
        return this.useYn;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_MENU.UPPER_MENU_CD</code>.
     */
    public String getUpperMenuCd() {
        return this.upperMenuCd;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbMenu other = (TbMenu) obj;
        if (this.menuCd == null) {
            if (other.menuCd != null)
                return false;
        }
        else if (!this.menuCd.equals(other.menuCd))
            return false;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.sts == null) {
            if (other.sts != null)
                return false;
        }
        else if (!this.sts.equals(other.sts))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.updateUser == null) {
            if (other.updateUser != null)
                return false;
        }
        else if (!this.updateUser.equals(other.updateUser))
            return false;
        if (this.menuLv == null) {
            if (other.menuLv != null)
                return false;
        }
        else if (!this.menuLv.equals(other.menuLv))
            return false;
        if (this.menuNm == null) {
            if (other.menuNm != null)
                return false;
        }
        else if (!this.menuNm.equals(other.menuNm))
            return false;
        if (this.menuUrl == null) {
            if (other.menuUrl != null)
                return false;
        }
        else if (!this.menuUrl.equals(other.menuUrl))
            return false;
        if (this.orderNum == null) {
            if (other.orderNum != null)
                return false;
        }
        else if (!this.orderNum.equals(other.orderNum))
            return false;
        if (this.useYn == null) {
            if (other.useYn != null)
                return false;
        }
        else if (!this.useYn.equals(other.useYn))
            return false;
        if (this.upperMenuCd == null) {
            if (other.upperMenuCd != null)
                return false;
        }
        else if (!this.upperMenuCd.equals(other.upperMenuCd))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.menuCd == null) ? 0 : this.menuCd.hashCode());
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.sts == null) ? 0 : this.sts.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.updateUser == null) ? 0 : this.updateUser.hashCode());
        result = prime * result + ((this.menuLv == null) ? 0 : this.menuLv.hashCode());
        result = prime * result + ((this.menuNm == null) ? 0 : this.menuNm.hashCode());
        result = prime * result + ((this.menuUrl == null) ? 0 : this.menuUrl.hashCode());
        result = prime * result + ((this.orderNum == null) ? 0 : this.orderNum.hashCode());
        result = prime * result + ((this.useYn == null) ? 0 : this.useYn.hashCode());
        result = prime * result + ((this.upperMenuCd == null) ? 0 : this.upperMenuCd.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbMenu (");

        sb.append(menuCd);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createUser);
        sb.append(", ").append(sts);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(menuLv);
        sb.append(", ").append(menuNm);
        sb.append(", ").append(menuUrl);
        sb.append(", ").append(orderNum);
        sb.append(", ").append(useYn);
        sb.append(", ").append(upperMenuCd);

        sb.append(")");
        return sb.toString();
    }
}
