/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbNotice implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String notId;
    private final LocalDateTime createDate;
    private final String createUser;
    private final String sts;
    private final LocalDateTime timestamp;
    private final String updateUser;
    private final String content;
    private final String notType;
    private final String title;
    private final LocalDateTime writeDate;
    private final String writor;

    public TbNotice(TbNotice value) {
        this.notId = value.notId;
        this.createDate = value.createDate;
        this.createUser = value.createUser;
        this.sts = value.sts;
        this.timestamp = value.timestamp;
        this.updateUser = value.updateUser;
        this.content = value.content;
        this.notType = value.notType;
        this.title = value.title;
        this.writeDate = value.writeDate;
        this.writor = value.writor;
    }

    public TbNotice(
        String notId,
        LocalDateTime createDate,
        String createUser,
        String sts,
        LocalDateTime timestamp,
        String updateUser,
        String content,
        String notType,
        String title,
        LocalDateTime writeDate,
        String writor
    ) {
        this.notId = notId;
        this.createDate = createDate;
        this.createUser = createUser;
        this.sts = sts;
        this.timestamp = timestamp;
        this.updateUser = updateUser;
        this.content = content;
        this.notType = notType;
        this.title = title;
        this.writeDate = writeDate;
        this.writor = writor;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.NOT_ID</code>.
     */
    public String getNotId() {
        return this.notId;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.STS</code>.
     */
    public String getSts() {
        return this.sts;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.CONTENT</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.NOT_TYPE</code>.
     */
    public String getNotType() {
        return this.notType;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.TITLE</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.WRITE_DATE</code>.
     */
    public LocalDateTime getWriteDate() {
        return this.writeDate;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.WRITOR</code>.
     */
    public String getWritor() {
        return this.writor;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbNotice other = (TbNotice) obj;
        if (this.notId == null) {
            if (other.notId != null)
                return false;
        }
        else if (!this.notId.equals(other.notId))
            return false;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.sts == null) {
            if (other.sts != null)
                return false;
        }
        else if (!this.sts.equals(other.sts))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.updateUser == null) {
            if (other.updateUser != null)
                return false;
        }
        else if (!this.updateUser.equals(other.updateUser))
            return false;
        if (this.content == null) {
            if (other.content != null)
                return false;
        }
        else if (!this.content.equals(other.content))
            return false;
        if (this.notType == null) {
            if (other.notType != null)
                return false;
        }
        else if (!this.notType.equals(other.notType))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.writeDate == null) {
            if (other.writeDate != null)
                return false;
        }
        else if (!this.writeDate.equals(other.writeDate))
            return false;
        if (this.writor == null) {
            if (other.writor != null)
                return false;
        }
        else if (!this.writor.equals(other.writor))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.notId == null) ? 0 : this.notId.hashCode());
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.sts == null) ? 0 : this.sts.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.updateUser == null) ? 0 : this.updateUser.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.notType == null) ? 0 : this.notType.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.writeDate == null) ? 0 : this.writeDate.hashCode());
        result = prime * result + ((this.writor == null) ? 0 : this.writor.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbNotice (");

        sb.append(notId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createUser);
        sb.append(", ").append(sts);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(content);
        sb.append(", ").append(notType);
        sb.append(", ").append(title);
        sb.append(", ").append(writeDate);
        sb.append(", ").append(writor);

        sb.append(")");
        return sb.toString();
    }
}
