/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbScheH implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String logId;
    private final LocalDateTime createDate;
    private final String createUser;
    private final String sts;
    private final LocalDateTime timestamp;
    private final String updateUser;
    private final LocalDateTime endTime;
    private final String errorMsg;
    private final Long execTime;
    private final String scheGroup;
    private final String scheId;
    private final LocalDateTime startTime;
    private final String success;

    public TbScheH(TbScheH value) {
        this.logId = value.logId;
        this.createDate = value.createDate;
        this.createUser = value.createUser;
        this.sts = value.sts;
        this.timestamp = value.timestamp;
        this.updateUser = value.updateUser;
        this.endTime = value.endTime;
        this.errorMsg = value.errorMsg;
        this.execTime = value.execTime;
        this.scheGroup = value.scheGroup;
        this.scheId = value.scheId;
        this.startTime = value.startTime;
        this.success = value.success;
    }

    public TbScheH(
        String logId,
        LocalDateTime createDate,
        String createUser,
        String sts,
        LocalDateTime timestamp,
        String updateUser,
        LocalDateTime endTime,
        String errorMsg,
        Long execTime,
        String scheGroup,
        String scheId,
        LocalDateTime startTime,
        String success
    ) {
        this.logId = logId;
        this.createDate = createDate;
        this.createUser = createUser;
        this.sts = sts;
        this.timestamp = timestamp;
        this.updateUser = updateUser;
        this.endTime = endTime;
        this.errorMsg = errorMsg;
        this.execTime = execTime;
        this.scheGroup = scheGroup;
        this.scheId = scheId;
        this.startTime = startTime;
        this.success = success;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.LOG_ID</code>.
     */
    public String getLogId() {
        return this.logId;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.STS</code>.
     */
    public String getSts() {
        return this.sts;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.END_TIME</code>.
     */
    public LocalDateTime getEndTime() {
        return this.endTime;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.ERROR_MSG</code>.
     */
    public String getErrorMsg() {
        return this.errorMsg;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.EXEC_TIME</code>.
     */
    public Long getExecTime() {
        return this.execTime;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.SCHE_GROUP</code>.
     */
    public String getScheGroup() {
        return this.scheGroup;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.SCHE_ID</code>.
     */
    public String getScheId() {
        return this.scheId;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.START_TIME</code>.
     */
    public LocalDateTime getStartTime() {
        return this.startTime;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.SUCCESS</code>.
     */
    public String getSuccess() {
        return this.success;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbScheH other = (TbScheH) obj;
        if (this.logId == null) {
            if (other.logId != null)
                return false;
        }
        else if (!this.logId.equals(other.logId))
            return false;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.sts == null) {
            if (other.sts != null)
                return false;
        }
        else if (!this.sts.equals(other.sts))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.updateUser == null) {
            if (other.updateUser != null)
                return false;
        }
        else if (!this.updateUser.equals(other.updateUser))
            return false;
        if (this.endTime == null) {
            if (other.endTime != null)
                return false;
        }
        else if (!this.endTime.equals(other.endTime))
            return false;
        if (this.errorMsg == null) {
            if (other.errorMsg != null)
                return false;
        }
        else if (!this.errorMsg.equals(other.errorMsg))
            return false;
        if (this.execTime == null) {
            if (other.execTime != null)
                return false;
        }
        else if (!this.execTime.equals(other.execTime))
            return false;
        if (this.scheGroup == null) {
            if (other.scheGroup != null)
                return false;
        }
        else if (!this.scheGroup.equals(other.scheGroup))
            return false;
        if (this.scheId == null) {
            if (other.scheId != null)
                return false;
        }
        else if (!this.scheId.equals(other.scheId))
            return false;
        if (this.startTime == null) {
            if (other.startTime != null)
                return false;
        }
        else if (!this.startTime.equals(other.startTime))
            return false;
        if (this.success == null) {
            if (other.success != null)
                return false;
        }
        else if (!this.success.equals(other.success))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.logId == null) ? 0 : this.logId.hashCode());
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.sts == null) ? 0 : this.sts.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.updateUser == null) ? 0 : this.updateUser.hashCode());
        result = prime * result + ((this.endTime == null) ? 0 : this.endTime.hashCode());
        result = prime * result + ((this.errorMsg == null) ? 0 : this.errorMsg.hashCode());
        result = prime * result + ((this.execTime == null) ? 0 : this.execTime.hashCode());
        result = prime * result + ((this.scheGroup == null) ? 0 : this.scheGroup.hashCode());
        result = prime * result + ((this.scheId == null) ? 0 : this.scheId.hashCode());
        result = prime * result + ((this.startTime == null) ? 0 : this.startTime.hashCode());
        result = prime * result + ((this.success == null) ? 0 : this.success.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbScheH (");

        sb.append(logId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createUser);
        sb.append(", ").append(sts);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(endTime);
        sb.append(", ").append(errorMsg);
        sb.append(", ").append(execTime);
        sb.append(", ").append(scheGroup);
        sb.append(", ").append(scheId);
        sb.append(", ").append(startTime);
        sb.append(", ").append(success);

        sb.append(")");
        return sb.toString();
    }
}
