/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbScheM implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String scheId;
    private final LocalDateTime createDate;
    private final String createUser;
    private final String sts;
    private final LocalDateTime timestamp;
    private final String updateUser;
    private final String className;
    private final String cronExp;
    private final String description;
    private final LocalDateTime lastExecTime;
    private final String methodName;
    private final LocalDateTime nextExecTime;
    private final String scheGroup;
    private final String scheName;
    private final String triggerName;
    private final String useYn;

    public TbScheM(TbScheM value) {
        this.scheId = value.scheId;
        this.createDate = value.createDate;
        this.createUser = value.createUser;
        this.sts = value.sts;
        this.timestamp = value.timestamp;
        this.updateUser = value.updateUser;
        this.className = value.className;
        this.cronExp = value.cronExp;
        this.description = value.description;
        this.lastExecTime = value.lastExecTime;
        this.methodName = value.methodName;
        this.nextExecTime = value.nextExecTime;
        this.scheGroup = value.scheGroup;
        this.scheName = value.scheName;
        this.triggerName = value.triggerName;
        this.useYn = value.useYn;
    }

    public TbScheM(
        String scheId,
        LocalDateTime createDate,
        String createUser,
        String sts,
        LocalDateTime timestamp,
        String updateUser,
        String className,
        String cronExp,
        String description,
        LocalDateTime lastExecTime,
        String methodName,
        LocalDateTime nextExecTime,
        String scheGroup,
        String scheName,
        String triggerName,
        String useYn
    ) {
        this.scheId = scheId;
        this.createDate = createDate;
        this.createUser = createUser;
        this.sts = sts;
        this.timestamp = timestamp;
        this.updateUser = updateUser;
        this.className = className;
        this.cronExp = cronExp;
        this.description = description;
        this.lastExecTime = lastExecTime;
        this.methodName = methodName;
        this.nextExecTime = nextExecTime;
        this.scheGroup = scheGroup;
        this.scheName = scheName;
        this.triggerName = triggerName;
        this.useYn = useYn;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.SCHE_ID</code>.
     */
    public String getScheId() {
        return this.scheId;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.STS</code>.
     */
    public String getSts() {
        return this.sts;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.CLASS_NAME</code>.
     */
    public String getClassName() {
        return this.className;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.CRON_EXP</code>.
     */
    public String getCronExp() {
        return this.cronExp;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.DESCRIPTION</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.LAST_EXEC_TIME</code>.
     */
    public LocalDateTime getLastExecTime() {
        return this.lastExecTime;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.METHOD_NAME</code>.
     */
    public String getMethodName() {
        return this.methodName;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.NEXT_EXEC_TIME</code>.
     */
    public LocalDateTime getNextExecTime() {
        return this.nextExecTime;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.SCHE_GROUP</code>.
     */
    public String getScheGroup() {
        return this.scheGroup;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.SCHE_NAME</code>.
     */
    public String getScheName() {
        return this.scheName;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.TRIGGER_NAME</code>.
     */
    public String getTriggerName() {
        return this.triggerName;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_M.USE_YN</code>.
     */
    public String getUseYn() {
        return this.useYn;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbScheM other = (TbScheM) obj;
        if (this.scheId == null) {
            if (other.scheId != null)
                return false;
        }
        else if (!this.scheId.equals(other.scheId))
            return false;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.sts == null) {
            if (other.sts != null)
                return false;
        }
        else if (!this.sts.equals(other.sts))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.updateUser == null) {
            if (other.updateUser != null)
                return false;
        }
        else if (!this.updateUser.equals(other.updateUser))
            return false;
        if (this.className == null) {
            if (other.className != null)
                return false;
        }
        else if (!this.className.equals(other.className))
            return false;
        if (this.cronExp == null) {
            if (other.cronExp != null)
                return false;
        }
        else if (!this.cronExp.equals(other.cronExp))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.lastExecTime == null) {
            if (other.lastExecTime != null)
                return false;
        }
        else if (!this.lastExecTime.equals(other.lastExecTime))
            return false;
        if (this.methodName == null) {
            if (other.methodName != null)
                return false;
        }
        else if (!this.methodName.equals(other.methodName))
            return false;
        if (this.nextExecTime == null) {
            if (other.nextExecTime != null)
                return false;
        }
        else if (!this.nextExecTime.equals(other.nextExecTime))
            return false;
        if (this.scheGroup == null) {
            if (other.scheGroup != null)
                return false;
        }
        else if (!this.scheGroup.equals(other.scheGroup))
            return false;
        if (this.scheName == null) {
            if (other.scheName != null)
                return false;
        }
        else if (!this.scheName.equals(other.scheName))
            return false;
        if (this.triggerName == null) {
            if (other.triggerName != null)
                return false;
        }
        else if (!this.triggerName.equals(other.triggerName))
            return false;
        if (this.useYn == null) {
            if (other.useYn != null)
                return false;
        }
        else if (!this.useYn.equals(other.useYn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.scheId == null) ? 0 : this.scheId.hashCode());
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.sts == null) ? 0 : this.sts.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.updateUser == null) ? 0 : this.updateUser.hashCode());
        result = prime * result + ((this.className == null) ? 0 : this.className.hashCode());
        result = prime * result + ((this.cronExp == null) ? 0 : this.cronExp.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.lastExecTime == null) ? 0 : this.lastExecTime.hashCode());
        result = prime * result + ((this.methodName == null) ? 0 : this.methodName.hashCode());
        result = prime * result + ((this.nextExecTime == null) ? 0 : this.nextExecTime.hashCode());
        result = prime * result + ((this.scheGroup == null) ? 0 : this.scheGroup.hashCode());
        result = prime * result + ((this.scheName == null) ? 0 : this.scheName.hashCode());
        result = prime * result + ((this.triggerName == null) ? 0 : this.triggerName.hashCode());
        result = prime * result + ((this.useYn == null) ? 0 : this.useYn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbScheM (");

        sb.append(scheId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createUser);
        sb.append(", ").append(sts);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(className);
        sb.append(", ").append(cronExp);
        sb.append(", ").append(description);
        sb.append(", ").append(lastExecTime);
        sb.append(", ").append(methodName);
        sb.append(", ").append(nextExecTime);
        sb.append(", ").append(scheGroup);
        sb.append(", ").append(scheName);
        sb.append(", ").append(triggerName);
        sb.append(", ").append(useYn);

        sb.append(")");
        return sb.toString();
    }
}
