/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbSmsH implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String logId;
    private final LocalDateTime createDate;
    private final String createUser;
    private final String sts;
    private final LocalDateTime timestamp;
    private final String updateUser;
    private final String errorMsg;
    private final String fromPhone;
    private final String smsId;
    private final String success;
    private final String text;
    private final String toPhone;

    public TbSmsH(TbSmsH value) {
        this.logId = value.logId;
        this.createDate = value.createDate;
        this.createUser = value.createUser;
        this.sts = value.sts;
        this.timestamp = value.timestamp;
        this.updateUser = value.updateUser;
        this.errorMsg = value.errorMsg;
        this.fromPhone = value.fromPhone;
        this.smsId = value.smsId;
        this.success = value.success;
        this.text = value.text;
        this.toPhone = value.toPhone;
    }

    public TbSmsH(
        String logId,
        LocalDateTime createDate,
        String createUser,
        String sts,
        LocalDateTime timestamp,
        String updateUser,
        String errorMsg,
        String fromPhone,
        String smsId,
        String success,
        String text,
        String toPhone
    ) {
        this.logId = logId;
        this.createDate = createDate;
        this.createUser = createUser;
        this.sts = sts;
        this.timestamp = timestamp;
        this.updateUser = updateUser;
        this.errorMsg = errorMsg;
        this.fromPhone = fromPhone;
        this.smsId = smsId;
        this.success = success;
        this.text = text;
        this.toPhone = toPhone;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.LOG_ID</code>.
     */
    public String getLogId() {
        return this.logId;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.STS</code>.
     */
    public String getSts() {
        return this.sts;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.ERROR_MSG</code>.
     */
    public String getErrorMsg() {
        return this.errorMsg;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.FROM_PHONE</code>.
     */
    public String getFromPhone() {
        return this.fromPhone;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.SMS_ID</code>.
     */
    public String getSmsId() {
        return this.smsId;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.SUCCESS</code>.
     */
    public String getSuccess() {
        return this.success;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.TEXT</code>.
     */
    public String getText() {
        return this.text;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.TO_PHONE</code>.
     */
    public String getToPhone() {
        return this.toPhone;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbSmsH other = (TbSmsH) obj;
        if (this.logId == null) {
            if (other.logId != null)
                return false;
        }
        else if (!this.logId.equals(other.logId))
            return false;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.sts == null) {
            if (other.sts != null)
                return false;
        }
        else if (!this.sts.equals(other.sts))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.updateUser == null) {
            if (other.updateUser != null)
                return false;
        }
        else if (!this.updateUser.equals(other.updateUser))
            return false;
        if (this.errorMsg == null) {
            if (other.errorMsg != null)
                return false;
        }
        else if (!this.errorMsg.equals(other.errorMsg))
            return false;
        if (this.fromPhone == null) {
            if (other.fromPhone != null)
                return false;
        }
        else if (!this.fromPhone.equals(other.fromPhone))
            return false;
        if (this.smsId == null) {
            if (other.smsId != null)
                return false;
        }
        else if (!this.smsId.equals(other.smsId))
            return false;
        if (this.success == null) {
            if (other.success != null)
                return false;
        }
        else if (!this.success.equals(other.success))
            return false;
        if (this.text == null) {
            if (other.text != null)
                return false;
        }
        else if (!this.text.equals(other.text))
            return false;
        if (this.toPhone == null) {
            if (other.toPhone != null)
                return false;
        }
        else if (!this.toPhone.equals(other.toPhone))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.logId == null) ? 0 : this.logId.hashCode());
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.sts == null) ? 0 : this.sts.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.updateUser == null) ? 0 : this.updateUser.hashCode());
        result = prime * result + ((this.errorMsg == null) ? 0 : this.errorMsg.hashCode());
        result = prime * result + ((this.fromPhone == null) ? 0 : this.fromPhone.hashCode());
        result = prime * result + ((this.smsId == null) ? 0 : this.smsId.hashCode());
        result = prime * result + ((this.success == null) ? 0 : this.success.hashCode());
        result = prime * result + ((this.text == null) ? 0 : this.text.hashCode());
        result = prime * result + ((this.toPhone == null) ? 0 : this.toPhone.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbSmsH (");

        sb.append(logId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createUser);
        sb.append(", ").append(sts);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(errorMsg);
        sb.append(", ").append(fromPhone);
        sb.append(", ").append(smsId);
        sb.append(", ").append(success);
        sb.append(", ").append(text);
        sb.append(", ").append(toPhone);

        sb.append(")");
        return sb.toString();
    }
}
