/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String userId;
    private final LocalDateTime createDate;
    private final String createUser;
    private final String sts;
    private final LocalDateTime timestamp;
    private final String updateUser;
    private final String email;
    private final String gender;
    private final String name;
    private final String password;
    private final String phoneNum;
    private final String role;
    private final String userType;
    private final String deptCode;

    public TbUser(TbUser value) {
        this.userId = value.userId;
        this.createDate = value.createDate;
        this.createUser = value.createUser;
        this.sts = value.sts;
        this.timestamp = value.timestamp;
        this.updateUser = value.updateUser;
        this.email = value.email;
        this.gender = value.gender;
        this.name = value.name;
        this.password = value.password;
        this.phoneNum = value.phoneNum;
        this.role = value.role;
        this.userType = value.userType;
        this.deptCode = value.deptCode;
    }

    public TbUser(
        String userId,
        LocalDateTime createDate,
        String createUser,
        String sts,
        LocalDateTime timestamp,
        String updateUser,
        String email,
        String gender,
        String name,
        String password,
        String phoneNum,
        String role,
        String userType,
        String deptCode
    ) {
        this.userId = userId;
        this.createDate = createDate;
        this.createUser = createUser;
        this.sts = sts;
        this.timestamp = timestamp;
        this.updateUser = updateUser;
        this.email = email;
        this.gender = gender;
        this.name = name;
        this.password = password;
        this.phoneNum = phoneNum;
        this.role = role;
        this.userType = userType;
        this.deptCode = deptCode;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.USER_ID</code>.
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.STS</code>.
     */
    public String getSts() {
        return this.sts;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.EMAIL</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.GENDER</code>.
     */
    public String getGender() {
        return this.gender;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.NAME</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.PASSWORD</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.PHONE_NUM</code>.
     */
    public String getPhoneNum() {
        return this.phoneNum;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.ROLE</code>.
     */
    public String getRole() {
        return this.role;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.USER_TYPE</code>.
     */
    public String getUserType() {
        return this.userType;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.DEPT_CODE</code>.
     */
    public String getDeptCode() {
        return this.deptCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbUser other = (TbUser) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.sts == null) {
            if (other.sts != null)
                return false;
        }
        else if (!this.sts.equals(other.sts))
            return false;
        if (this.timestamp == null) {
            if (other.timestamp != null)
                return false;
        }
        else if (!this.timestamp.equals(other.timestamp))
            return false;
        if (this.updateUser == null) {
            if (other.updateUser != null)
                return false;
        }
        else if (!this.updateUser.equals(other.updateUser))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.gender == null) {
            if (other.gender != null)
                return false;
        }
        else if (!this.gender.equals(other.gender))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.phoneNum == null) {
            if (other.phoneNum != null)
                return false;
        }
        else if (!this.phoneNum.equals(other.phoneNum))
            return false;
        if (this.role == null) {
            if (other.role != null)
                return false;
        }
        else if (!this.role.equals(other.role))
            return false;
        if (this.userType == null) {
            if (other.userType != null)
                return false;
        }
        else if (!this.userType.equals(other.userType))
            return false;
        if (this.deptCode == null) {
            if (other.deptCode != null)
                return false;
        }
        else if (!this.deptCode.equals(other.deptCode))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.sts == null) ? 0 : this.sts.hashCode());
        result = prime * result + ((this.timestamp == null) ? 0 : this.timestamp.hashCode());
        result = prime * result + ((this.updateUser == null) ? 0 : this.updateUser.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.gender == null) ? 0 : this.gender.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.phoneNum == null) ? 0 : this.phoneNum.hashCode());
        result = prime * result + ((this.role == null) ? 0 : this.role.hashCode());
        result = prime * result + ((this.userType == null) ? 0 : this.userType.hashCode());
        result = prime * result + ((this.deptCode == null) ? 0 : this.deptCode.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbUser (");

        sb.append(userId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createUser);
        sb.append(", ").append(sts);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(email);
        sb.append(", ").append(gender);
        sb.append(", ").append(name);
        sb.append(", ").append(password);
        sb.append(", ").append(phoneNum);
        sb.append(", ").append(role);
        sb.append(", ").append(userType);
        sb.append(", ").append(deptCode);

        sb.append(")");
        return sb.toString();
    }
}
