/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.CbskDev;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.TbBbs.TbBbsPath;
import com.basic.app.entity.jooq.tables.TbUser.TbUserPath;
import com.basic.app.entity.jooq.tables.records.TbBbsCommentRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbBbsComment extends TableImpl<TbBbsCommentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBSK-DEV.TB_BBS_COMMENT</code>
     */
    public static final TbBbsComment TB_BBS_COMMENT = new TbBbsComment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbBbsCommentRecord> getRecordType() {
        return TbBbsCommentRecord.class;
    }

    /**
     * The column <code>CBSK-DEV.TB_BBS_COMMENT.COMMENT_ID</code>.
     */
    public final TableField<TbBbsCommentRecord, String> COMMENT_ID = createField(DSL.name("COMMENT_ID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS_COMMENT.CREATE_DATE</code>.
     */
    public final TableField<TbBbsCommentRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS_COMMENT.CREATE_USER</code>.
     */
    public final TableField<TbBbsCommentRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS_COMMENT.STS</code>.
     */
    public final TableField<TbBbsCommentRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS_COMMENT.TIMESTAMP</code>.
     */
    public final TableField<TbBbsCommentRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS_COMMENT.UPDATE_USER</code>.
     */
    public final TableField<TbBbsCommentRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS_COMMENT.CONTENT</code>.
     */
    public final TableField<TbBbsCommentRecord, String> CONTENT = createField(DSL.name("CONTENT"), SQLDataType.VARCHAR(2048).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS_COMMENT.WRITE_DATE</code>.
     */
    public final TableField<TbBbsCommentRecord, LocalDateTime> WRITE_DATE = createField(DSL.name("WRITE_DATE"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS_COMMENT.BBS_ID</code>.
     */
    public final TableField<TbBbsCommentRecord, String> BBS_ID = createField(DSL.name("BBS_ID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS_COMMENT.WRITOR</code>.
     */
    public final TableField<TbBbsCommentRecord, String> WRITOR = createField(DSL.name("WRITOR"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    private TbBbsComment(Name alias, Table<TbBbsCommentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbBbsComment(Name alias, Table<TbBbsCommentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_BBS_COMMENT</code> table reference
     */
    public TbBbsComment(String alias) {
        this(DSL.name(alias), TB_BBS_COMMENT);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_BBS_COMMENT</code> table reference
     */
    public TbBbsComment(Name alias) {
        this(alias, TB_BBS_COMMENT);
    }

    /**
     * Create a <code>CBSK-DEV.TB_BBS_COMMENT</code> table reference
     */
    public TbBbsComment() {
        this(DSL.name("TB_BBS_COMMENT"), null);
    }

    public <O extends Record> TbBbsComment(Table<O> path, ForeignKey<O, TbBbsCommentRecord> childPath, InverseForeignKey<O, TbBbsCommentRecord> parentPath) {
        super(path, childPath, parentPath, TB_BBS_COMMENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TbBbsCommentPath extends TbBbsComment implements Path<TbBbsCommentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TbBbsCommentPath(Table<O> path, ForeignKey<O, TbBbsCommentRecord> childPath, InverseForeignKey<O, TbBbsCommentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TbBbsCommentPath(Name alias, Table<TbBbsCommentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TbBbsCommentPath as(String alias) {
            return new TbBbsCommentPath(DSL.name(alias), this);
        }

        @Override
        public TbBbsCommentPath as(Name alias) {
            return new TbBbsCommentPath(alias, this);
        }

        @Override
        public TbBbsCommentPath as(Table<?> alias) {
            return new TbBbsCommentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CbskDev.CBSK_DEV;
    }

    @Override
    public UniqueKey<TbBbsCommentRecord> getPrimaryKey() {
        return Keys.KEY_TB_BBS_COMMENT_PRIMARY;
    }

    @Override
    public List<ForeignKey<TbBbsCommentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK5MJQUUBMVN6NFIU2M646LBSIJ, Keys.FK9UO8HYHW4675EBUW2MBEYRHJC);
    }

    private transient TbUserPath _tbUser;

    /**
     * Get the implicit join path to the <code>CBSK-DEV.TB_USER</code> table.
     */
    public TbUserPath tbUser() {
        if (_tbUser == null)
            _tbUser = new TbUserPath(this, Keys.FK5MJQUUBMVN6NFIU2M646LBSIJ, null);

        return _tbUser;
    }

    private transient TbBbsPath _tbBbs;

    /**
     * Get the implicit join path to the <code>CBSK-DEV.TB_BBS</code> table.
     */
    public TbBbsPath tbBbs() {
        if (_tbBbs == null)
            _tbBbs = new TbBbsPath(this, Keys.FK9UO8HYHW4675EBUW2MBEYRHJC, null);

        return _tbBbs;
    }

    @Override
    public TbBbsComment as(String alias) {
        return new TbBbsComment(DSL.name(alias), this);
    }

    @Override
    public TbBbsComment as(Name alias) {
        return new TbBbsComment(alias, this);
    }

    @Override
    public TbBbsComment as(Table<?> alias) {
        return new TbBbsComment(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbBbsComment rename(String name) {
        return new TbBbsComment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbBbsComment rename(Name name) {
        return new TbBbsComment(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbBbsComment rename(Table<?> name) {
        return new TbBbsComment(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbBbsComment where(Condition condition) {
        return new TbBbsComment(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbBbsComment where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbBbsComment where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbBbsComment where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbBbsComment where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbBbsComment where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbBbsComment where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbBbsComment where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbBbsComment whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbBbsComment whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
