/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.CbskDev;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.TbBbsComment.TbBbsCommentPath;
import com.basic.app.entity.jooq.tables.TbUser.TbUserPath;
import com.basic.app.entity.jooq.tables.records.TbBbsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbBbs extends TableImpl<TbBbsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBSK-DEV.TB_BBS</code>
     */
    public static final TbBbs TB_BBS = new TbBbs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbBbsRecord> getRecordType() {
        return TbBbsRecord.class;
    }

    /**
     * The column <code>CBSK-DEV.TB_BBS.BBS_ID</code>.
     */
    public final TableField<TbBbsRecord, String> BBS_ID = createField(DSL.name("BBS_ID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS.CREATE_DATE</code>.
     */
    public final TableField<TbBbsRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS.CREATE_USER</code>.
     */
    public final TableField<TbBbsRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS.STS</code>.
     */
    public final TableField<TbBbsRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS.TIMESTAMP</code>.
     */
    public final TableField<TbBbsRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS.UPDATE_USER</code>.
     */
    public final TableField<TbBbsRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS.BBS_TYPE</code>.
     */
    public final TableField<TbBbsRecord, String> BBS_TYPE = createField(DSL.name("BBS_TYPE"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS.CONTENT</code>.
     */
    public final TableField<TbBbsRecord, String> CONTENT = createField(DSL.name("CONTENT"), SQLDataType.VARCHAR(2048).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS.TITLE</code>.
     */
    public final TableField<TbBbsRecord, String> TITLE = createField(DSL.name("TITLE"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS.WRITE_DATE</code>.
     */
    public final TableField<TbBbsRecord, LocalDateTime> WRITE_DATE = createField(DSL.name("WRITE_DATE"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP(3)"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>CBSK-DEV.TB_BBS.WRITOR</code>.
     */
    public final TableField<TbBbsRecord, String> WRITOR = createField(DSL.name("WRITOR"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    private TbBbs(Name alias, Table<TbBbsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbBbs(Name alias, Table<TbBbsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_BBS</code> table reference
     */
    public TbBbs(String alias) {
        this(DSL.name(alias), TB_BBS);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_BBS</code> table reference
     */
    public TbBbs(Name alias) {
        this(alias, TB_BBS);
    }

    /**
     * Create a <code>CBSK-DEV.TB_BBS</code> table reference
     */
    public TbBbs() {
        this(DSL.name("TB_BBS"), null);
    }

    public <O extends Record> TbBbs(Table<O> path, ForeignKey<O, TbBbsRecord> childPath, InverseForeignKey<O, TbBbsRecord> parentPath) {
        super(path, childPath, parentPath, TB_BBS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TbBbsPath extends TbBbs implements Path<TbBbsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TbBbsPath(Table<O> path, ForeignKey<O, TbBbsRecord> childPath, InverseForeignKey<O, TbBbsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TbBbsPath(Name alias, Table<TbBbsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TbBbsPath as(String alias) {
            return new TbBbsPath(DSL.name(alias), this);
        }

        @Override
        public TbBbsPath as(Name alias) {
            return new TbBbsPath(alias, this);
        }

        @Override
        public TbBbsPath as(Table<?> alias) {
            return new TbBbsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CbskDev.CBSK_DEV;
    }

    @Override
    public UniqueKey<TbBbsRecord> getPrimaryKey() {
        return Keys.KEY_TB_BBS_PRIMARY;
    }

    @Override
    public List<ForeignKey<TbBbsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKA8CBKY7LQWM99IYSMFLI3QMKM);
    }

    private transient TbUserPath _tbUser;

    /**
     * Get the implicit join path to the <code>CBSK-DEV.TB_USER</code> table.
     */
    public TbUserPath tbUser() {
        if (_tbUser == null)
            _tbUser = new TbUserPath(this, Keys.FKA8CBKY7LQWM99IYSMFLI3QMKM, null);

        return _tbUser;
    }

    private transient TbBbsCommentPath _tbBbsComment;

    /**
     * Get the implicit to-many join path to the
     * <code>CBSK-DEV.TB_BBS_COMMENT</code> table
     */
    public TbBbsCommentPath tbBbsComment() {
        if (_tbBbsComment == null)
            _tbBbsComment = new TbBbsCommentPath(this, null, Keys.FK9UO8HYHW4675EBUW2MBEYRHJC.getInverseKey());

        return _tbBbsComment;
    }

    @Override
    public TbBbs as(String alias) {
        return new TbBbs(DSL.name(alias), this);
    }

    @Override
    public TbBbs as(Name alias) {
        return new TbBbs(alias, this);
    }

    @Override
    public TbBbs as(Table<?> alias) {
        return new TbBbs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbBbs rename(String name) {
        return new TbBbs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbBbs rename(Name name) {
        return new TbBbs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbBbs rename(Table<?> name) {
        return new TbBbs(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbBbs where(Condition condition) {
        return new TbBbs(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbBbs where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbBbs where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbBbs where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbBbs where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbBbs where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbBbs where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbBbs where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbBbs whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbBbs whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
