/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.Cbms;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.records.TbChaebunRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbChaebun extends TableImpl<TbChaebunRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBMS.TB_CHAEBUN</code>
     */
    public static final TbChaebun TB_CHAEBUN = new TbChaebun();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbChaebunRecord> getRecordType() {
        return TbChaebunRecord.class;
    }

    /**
     * The column <code>CBMS.TB_CHAEBUN.SEQ_ID</code>.
     */
    public final TableField<TbChaebunRecord, String> SEQ_ID = createField(DSL.name("SEQ_ID"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_CHAEBUN.CREATE_DATE</code>.
     */
    public final TableField<TbChaebunRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_CHAEBUN.CREATE_USER</code>.
     */
    public final TableField<TbChaebunRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_CHAEBUN.STS</code>.
     */
    public final TableField<TbChaebunRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBMS.TB_CHAEBUN.TIMESTAMP</code>.
     */
    public final TableField<TbChaebunRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_CHAEBUN.UPDATE_USER</code>.
     */
    public final TableField<TbChaebunRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_CHAEBUN.CURRENT_VALUE</code>.
     */
    public final TableField<TbChaebunRecord, Integer> CURRENT_VALUE = createField(DSL.name("CURRENT_VALUE"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_CHAEBUN.DATEFORMAT</code>.
     */
    public final TableField<TbChaebunRecord, String> DATEFORMAT = createField(DSL.name("DATEFORMAT"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>CBMS.TB_CHAEBUN.LENGTH</code>.
     */
    public final TableField<TbChaebunRecord, Integer> LENGTH = createField(DSL.name("LENGTH"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("4", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>CBMS.TB_CHAEBUN.PATTERN</code>.
     */
    public final TableField<TbChaebunRecord, String> PATTERN = createField(DSL.name("PATTERN"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_CHAEBUN.PREFIX</code>.
     */
    public final TableField<TbChaebunRecord, String> PREFIX = createField(DSL.name("PREFIX"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_CHAEBUN.SEQ_NAME</code>.
     */
    public final TableField<TbChaebunRecord, String> SEQ_NAME = createField(DSL.name("SEQ_NAME"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_CHAEBUN.STEP</code>.
     */
    public final TableField<TbChaebunRecord, Integer> STEP = createField(DSL.name("STEP"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "");

    private TbChaebun(Name alias, Table<TbChaebunRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbChaebun(Name alias, Table<TbChaebunRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBMS.TB_CHAEBUN</code> table reference
     */
    public TbChaebun(String alias) {
        this(DSL.name(alias), TB_CHAEBUN);
    }

    /**
     * Create an aliased <code>CBMS.TB_CHAEBUN</code> table reference
     */
    public TbChaebun(Name alias) {
        this(alias, TB_CHAEBUN);
    }

    /**
     * Create a <code>CBMS.TB_CHAEBUN</code> table reference
     */
    public TbChaebun() {
        this(DSL.name("TB_CHAEBUN"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cbms.CBMS;
    }

    @Override
    public UniqueKey<TbChaebunRecord> getPrimaryKey() {
        return Keys.KEY_TB_CHAEBUN_PRIMARY;
    }

    @Override
    public TbChaebun as(String alias) {
        return new TbChaebun(DSL.name(alias), this);
    }

    @Override
    public TbChaebun as(Name alias) {
        return new TbChaebun(alias, this);
    }

    @Override
    public TbChaebun as(Table<?> alias) {
        return new TbChaebun(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbChaebun rename(String name) {
        return new TbChaebun(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbChaebun rename(Name name) {
        return new TbChaebun(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbChaebun rename(Table<?> name) {
        return new TbChaebun(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbChaebun where(Condition condition) {
        return new TbChaebun(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbChaebun where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbChaebun where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbChaebun where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbChaebun where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbChaebun where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbChaebun where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbChaebun where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbChaebun whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbChaebun whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
