/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.Cbms;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.TbComCodeM.TbComCodeMPath;
import com.basic.app.entity.jooq.tables.records.TbComCodeDPivotRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbComCodeDPivot extends TableImpl<TbComCodeDPivotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBMS.TB_COM_CODE_D_PIVOT</code>
     */
    public static final TbComCodeDPivot TB_COM_CODE_D_PIVOT = new TbComCodeDPivot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbComCodeDPivotRecord> getRecordType() {
        return TbComCodeDPivotRecord.class;
    }

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.DTL_CD</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> DTL_CD = createField(DSL.name("DTL_CD"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.GRP_CD</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> GRP_CD = createField(DSL.name("GRP_CD"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.CREATE_DATE</code>.
     */
    public final TableField<TbComCodeDPivotRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.CREATE_USER</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.STS</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.TIMESTAMP</code>.
     */
    public final TableField<TbComCodeDPivotRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.UPDATE_USER</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.ATTR_01</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> ATTR_01 = createField(DSL.name("ATTR_01"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.ATTR_02</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> ATTR_02 = createField(DSL.name("ATTR_02"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.ATTR_03</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> ATTR_03 = createField(DSL.name("ATTR_03"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.ATTR_04</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> ATTR_04 = createField(DSL.name("ATTR_04"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.ATTR_05</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> ATTR_05 = createField(DSL.name("ATTR_05"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.ATTR_06</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> ATTR_06 = createField(DSL.name("ATTR_06"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.ATTR_07</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> ATTR_07 = createField(DSL.name("ATTR_07"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.ATTR_08</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> ATTR_08 = createField(DSL.name("ATTR_08"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.ATTR_09</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> ATTR_09 = createField(DSL.name("ATTR_09"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.ATTR_10</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> ATTR_10 = createField(DSL.name("ATTR_10"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.ORDER_NUM</code>.
     */
    public final TableField<TbComCodeDPivotRecord, Integer> ORDER_NUM = createField(DSL.name("ORDER_NUM"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_D_PIVOT.USE_YN</code>.
     */
    public final TableField<TbComCodeDPivotRecord, String> USE_YN = createField(DSL.name("USE_YN"), SQLDataType.VARCHAR(1).defaultValue(DSL.inline("N", SQLDataType.VARCHAR)), this, "");

    private TbComCodeDPivot(Name alias, Table<TbComCodeDPivotRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbComCodeDPivot(Name alias, Table<TbComCodeDPivotRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBMS.TB_COM_CODE_D_PIVOT</code> table reference
     */
    public TbComCodeDPivot(String alias) {
        this(DSL.name(alias), TB_COM_CODE_D_PIVOT);
    }

    /**
     * Create an aliased <code>CBMS.TB_COM_CODE_D_PIVOT</code> table reference
     */
    public TbComCodeDPivot(Name alias) {
        this(alias, TB_COM_CODE_D_PIVOT);
    }

    /**
     * Create a <code>CBMS.TB_COM_CODE_D_PIVOT</code> table reference
     */
    public TbComCodeDPivot() {
        this(DSL.name("TB_COM_CODE_D_PIVOT"), null);
    }

    public <O extends Record> TbComCodeDPivot(Table<O> path, ForeignKey<O, TbComCodeDPivotRecord> childPath, InverseForeignKey<O, TbComCodeDPivotRecord> parentPath) {
        super(path, childPath, parentPath, TB_COM_CODE_D_PIVOT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TbComCodeDPivotPath extends TbComCodeDPivot implements Path<TbComCodeDPivotRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TbComCodeDPivotPath(Table<O> path, ForeignKey<O, TbComCodeDPivotRecord> childPath, InverseForeignKey<O, TbComCodeDPivotRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TbComCodeDPivotPath(Name alias, Table<TbComCodeDPivotRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TbComCodeDPivotPath as(String alias) {
            return new TbComCodeDPivotPath(DSL.name(alias), this);
        }

        @Override
        public TbComCodeDPivotPath as(Name alias) {
            return new TbComCodeDPivotPath(alias, this);
        }

        @Override
        public TbComCodeDPivotPath as(Table<?> alias) {
            return new TbComCodeDPivotPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cbms.CBMS;
    }

    @Override
    public UniqueKey<TbComCodeDPivotRecord> getPrimaryKey() {
        return Keys.KEY_TB_COM_CODE_D_PIVOT_PRIMARY;
    }

    @Override
    public List<ForeignKey<TbComCodeDPivotRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKO8E2CRL7MJAJDIXRVU48WO61V);
    }

    private transient TbComCodeMPath _tbComCodeM;

    /**
     * Get the implicit join path to the <code>CBMS.TB_COM_CODE_M</code> table.
     */
    public TbComCodeMPath tbComCodeM() {
        if (_tbComCodeM == null)
            _tbComCodeM = new TbComCodeMPath(this, Keys.FKO8E2CRL7MJAJDIXRVU48WO61V, null);

        return _tbComCodeM;
    }

    @Override
    public TbComCodeDPivot as(String alias) {
        return new TbComCodeDPivot(DSL.name(alias), this);
    }

    @Override
    public TbComCodeDPivot as(Name alias) {
        return new TbComCodeDPivot(alias, this);
    }

    @Override
    public TbComCodeDPivot as(Table<?> alias) {
        return new TbComCodeDPivot(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbComCodeDPivot rename(String name) {
        return new TbComCodeDPivot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbComCodeDPivot rename(Name name) {
        return new TbComCodeDPivot(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbComCodeDPivot rename(Table<?> name) {
        return new TbComCodeDPivot(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbComCodeDPivot where(Condition condition) {
        return new TbComCodeDPivot(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbComCodeDPivot where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbComCodeDPivot where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbComCodeDPivot where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbComCodeDPivot where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbComCodeDPivot where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbComCodeDPivot where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbComCodeDPivot where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbComCodeDPivot whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbComCodeDPivot whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
