/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.Cbms;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.TbComCodeD.TbComCodeDPath;
import com.basic.app.entity.jooq.tables.TbComCodeM.TbComCodeMPath;
import com.basic.app.entity.jooq.tables.records.TbComCodeTRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbComCodeT extends TableImpl<TbComCodeTRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBMS.TB_COM_CODE_T</code>
     */
    public static final TbComCodeT TB_COM_CODE_T = new TbComCodeT();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbComCodeTRecord> getRecordType() {
        return TbComCodeTRecord.class;
    }

    /**
     * The column <code>CBMS.TB_COM_CODE_T.ATTR_CD</code>.
     */
    public final TableField<TbComCodeTRecord, String> ATTR_CD = createField(DSL.name("ATTR_CD"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_T.CREATE_DATE</code>.
     */
    public final TableField<TbComCodeTRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_T.CREATE_USER</code>.
     */
    public final TableField<TbComCodeTRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_T.STS</code>.
     */
    public final TableField<TbComCodeTRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_T.TIMESTAMP</code>.
     */
    public final TableField<TbComCodeTRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_T.UPDATE_USER</code>.
     */
    public final TableField<TbComCodeTRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_T.ATTR_NM</code>.
     */
    public final TableField<TbComCodeTRecord, String> ATTR_NM = createField(DSL.name("ATTR_NM"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_T.ORDER_NUM</code>.
     */
    public final TableField<TbComCodeTRecord, Integer> ORDER_NUM = createField(DSL.name("ORDER_NUM"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COM_CODE_T.GRP_CD</code>.
     */
    public final TableField<TbComCodeTRecord, String> GRP_CD = createField(DSL.name("GRP_CD"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private TbComCodeT(Name alias, Table<TbComCodeTRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbComCodeT(Name alias, Table<TbComCodeTRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBMS.TB_COM_CODE_T</code> table reference
     */
    public TbComCodeT(String alias) {
        this(DSL.name(alias), TB_COM_CODE_T);
    }

    /**
     * Create an aliased <code>CBMS.TB_COM_CODE_T</code> table reference
     */
    public TbComCodeT(Name alias) {
        this(alias, TB_COM_CODE_T);
    }

    /**
     * Create a <code>CBMS.TB_COM_CODE_T</code> table reference
     */
    public TbComCodeT() {
        this(DSL.name("TB_COM_CODE_T"), null);
    }

    public <O extends Record> TbComCodeT(Table<O> path, ForeignKey<O, TbComCodeTRecord> childPath, InverseForeignKey<O, TbComCodeTRecord> parentPath) {
        super(path, childPath, parentPath, TB_COM_CODE_T);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TbComCodeTPath extends TbComCodeT implements Path<TbComCodeTRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TbComCodeTPath(Table<O> path, ForeignKey<O, TbComCodeTRecord> childPath, InverseForeignKey<O, TbComCodeTRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TbComCodeTPath(Name alias, Table<TbComCodeTRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TbComCodeTPath as(String alias) {
            return new TbComCodeTPath(DSL.name(alias), this);
        }

        @Override
        public TbComCodeTPath as(Name alias) {
            return new TbComCodeTPath(alias, this);
        }

        @Override
        public TbComCodeTPath as(Table<?> alias) {
            return new TbComCodeTPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cbms.CBMS;
    }

    @Override
    public UniqueKey<TbComCodeTRecord> getPrimaryKey() {
        return Keys.KEY_TB_COM_CODE_T_PRIMARY;
    }

    @Override
    public List<ForeignKey<TbComCodeTRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKJQCV6G5WVD8B52ICCXE4P537S);
    }

    private transient TbComCodeMPath _tbComCodeM;

    /**
     * Get the implicit join path to the <code>CBMS.TB_COM_CODE_M</code> table.
     */
    public TbComCodeMPath tbComCodeM() {
        if (_tbComCodeM == null)
            _tbComCodeM = new TbComCodeMPath(this, Keys.FKJQCV6G5WVD8B52ICCXE4P537S, null);

        return _tbComCodeM;
    }

    private transient TbComCodeDPath _tbComCodeD;

    /**
     * Get the implicit to-many join path to the <code>CBMS.TB_COM_CODE_D</code>
     * table
     */
    public TbComCodeDPath tbComCodeD() {
        if (_tbComCodeD == null)
            _tbComCodeD = new TbComCodeDPath(this, null, Keys.FKSXXB0B6K750U8TSC7KOMT0GMW.getInverseKey());

        return _tbComCodeD;
    }

    @Override
    public TbComCodeT as(String alias) {
        return new TbComCodeT(DSL.name(alias), this);
    }

    @Override
    public TbComCodeT as(Name alias) {
        return new TbComCodeT(alias, this);
    }

    @Override
    public TbComCodeT as(Table<?> alias) {
        return new TbComCodeT(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbComCodeT rename(String name) {
        return new TbComCodeT(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbComCodeT rename(Name name) {
        return new TbComCodeT(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbComCodeT rename(Table<?> name) {
        return new TbComCodeT(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbComCodeT where(Condition condition) {
        return new TbComCodeT(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbComCodeT where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbComCodeT where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbComCodeT where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbComCodeT where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbComCodeT where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbComCodeT where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbComCodeT where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbComCodeT whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbComCodeT whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
