/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.Cbms;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.TbDepartment.TbDepartmentPath;
import com.basic.app.entity.jooq.tables.records.TbCompanyRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbCompany extends TableImpl<TbCompanyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBMS.TB_COMPANY</code>
     */
    public static final TbCompany TB_COMPANY = new TbCompany();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbCompanyRecord> getRecordType() {
        return TbCompanyRecord.class;
    }

    /**
     * The column <code>CBMS.TB_COMPANY.COMPANY_CODE</code>.
     */
    public final TableField<TbCompanyRecord, String> COMPANY_CODE = createField(DSL.name("COMPANY_CODE"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COMPANY.CREATE_DATE</code>.
     */
    public final TableField<TbCompanyRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COMPANY.CREATE_USER</code>.
     */
    public final TableField<TbCompanyRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COMPANY.STS</code>.
     */
    public final TableField<TbCompanyRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBMS.TB_COMPANY.TIMESTAMP</code>.
     */
    public final TableField<TbCompanyRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COMPANY.UPDATE_USER</code>.
     */
    public final TableField<TbCompanyRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_COMPANY.COMPANY_NAME</code>.
     */
    public final TableField<TbCompanyRecord, String> COMPANY_NAME = createField(DSL.name("COMPANY_NAME"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private TbCompany(Name alias, Table<TbCompanyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbCompany(Name alias, Table<TbCompanyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBMS.TB_COMPANY</code> table reference
     */
    public TbCompany(String alias) {
        this(DSL.name(alias), TB_COMPANY);
    }

    /**
     * Create an aliased <code>CBMS.TB_COMPANY</code> table reference
     */
    public TbCompany(Name alias) {
        this(alias, TB_COMPANY);
    }

    /**
     * Create a <code>CBMS.TB_COMPANY</code> table reference
     */
    public TbCompany() {
        this(DSL.name("TB_COMPANY"), null);
    }

    public <O extends Record> TbCompany(Table<O> path, ForeignKey<O, TbCompanyRecord> childPath, InverseForeignKey<O, TbCompanyRecord> parentPath) {
        super(path, childPath, parentPath, TB_COMPANY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TbCompanyPath extends TbCompany implements Path<TbCompanyRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TbCompanyPath(Table<O> path, ForeignKey<O, TbCompanyRecord> childPath, InverseForeignKey<O, TbCompanyRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TbCompanyPath(Name alias, Table<TbCompanyRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TbCompanyPath as(String alias) {
            return new TbCompanyPath(DSL.name(alias), this);
        }

        @Override
        public TbCompanyPath as(Name alias) {
            return new TbCompanyPath(alias, this);
        }

        @Override
        public TbCompanyPath as(Table<?> alias) {
            return new TbCompanyPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cbms.CBMS;
    }

    @Override
    public UniqueKey<TbCompanyRecord> getPrimaryKey() {
        return Keys.KEY_TB_COMPANY_PRIMARY;
    }

    private transient TbDepartmentPath _tbDepartment;

    /**
     * Get the implicit to-many join path to the <code>CBMS.TB_DEPARTMENT</code>
     * table
     */
    public TbDepartmentPath tbDepartment() {
        if (_tbDepartment == null)
            _tbDepartment = new TbDepartmentPath(this, null, Keys.FKVMJBITIJ88M9U9VC2YM4HEOV.getInverseKey());

        return _tbDepartment;
    }

    @Override
    public TbCompany as(String alias) {
        return new TbCompany(DSL.name(alias), this);
    }

    @Override
    public TbCompany as(Name alias) {
        return new TbCompany(alias, this);
    }

    @Override
    public TbCompany as(Table<?> alias) {
        return new TbCompany(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbCompany rename(String name) {
        return new TbCompany(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbCompany rename(Name name) {
        return new TbCompany(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbCompany rename(Table<?> name) {
        return new TbCompany(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbCompany where(Condition condition) {
        return new TbCompany(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbCompany where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbCompany where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbCompany where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbCompany where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbCompany where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbCompany where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbCompany where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbCompany whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbCompany whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
