/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.CbskDev;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.TbCompany.TbCompanyPath;
import com.basic.app.entity.jooq.tables.TbUser.TbUserPath;
import com.basic.app.entity.jooq.tables.records.TbDepartmentRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbDepartment extends TableImpl<TbDepartmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBSK-DEV.TB_DEPARTMENT</code>
     */
    public static final TbDepartment TB_DEPARTMENT = new TbDepartment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbDepartmentRecord> getRecordType() {
        return TbDepartmentRecord.class;
    }

    /**
     * The column <code>CBSK-DEV.TB_DEPARTMENT.DEPT_LV</code>.
     */
    public final TableField<TbDepartmentRecord, Integer> DEPT_LV = createField(DSL.name("DEPT_LV"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_DEPARTMENT.USE_YN</code>.
     */
    public final TableField<TbDepartmentRecord, String> USE_YN = createField(DSL.name("USE_YN"), SQLDataType.VARCHAR(1).defaultValue(DSL.inline("N", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBSK-DEV.TB_DEPARTMENT.CREATE_DATE</code>.
     */
    public final TableField<TbDepartmentRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_DEPARTMENT.TIMESTAMP</code>.
     */
    public final TableField<TbDepartmentRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_DEPARTMENT.COMPANY_CODE</code>.
     */
    public final TableField<TbDepartmentRecord, String> COMPANY_CODE = createField(DSL.name("COMPANY_CODE"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_DEPARTMENT.CREATE_USER</code>.
     */
    public final TableField<TbDepartmentRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_DEPARTMENT.DEPT_CODE</code>.
     */
    public final TableField<TbDepartmentRecord, String> DEPT_CODE = createField(DSL.name("DEPT_CODE"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_DEPARTMENT.UPDATE_USER</code>.
     */
    public final TableField<TbDepartmentRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_DEPARTMENT.UPPER_DEPT_CODE</code>.
     */
    public final TableField<TbDepartmentRecord, String> UPPER_DEPT_CODE = createField(DSL.name("UPPER_DEPT_CODE"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_DEPARTMENT.DEPT_NM</code>.
     */
    public final TableField<TbDepartmentRecord, String> DEPT_NM = createField(DSL.name("DEPT_NM"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_DEPARTMENT.STS</code>.
     */
    public final TableField<TbDepartmentRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    private TbDepartment(Name alias, Table<TbDepartmentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbDepartment(Name alias, Table<TbDepartmentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_DEPARTMENT</code> table reference
     */
    public TbDepartment(String alias) {
        this(DSL.name(alias), TB_DEPARTMENT);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_DEPARTMENT</code> table reference
     */
    public TbDepartment(Name alias) {
        this(alias, TB_DEPARTMENT);
    }

    /**
     * Create a <code>CBSK-DEV.TB_DEPARTMENT</code> table reference
     */
    public TbDepartment() {
        this(DSL.name("TB_DEPARTMENT"), null);
    }

    public <O extends Record> TbDepartment(Table<O> path, ForeignKey<O, TbDepartmentRecord> childPath, InverseForeignKey<O, TbDepartmentRecord> parentPath) {
        super(path, childPath, parentPath, TB_DEPARTMENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TbDepartmentPath extends TbDepartment implements Path<TbDepartmentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TbDepartmentPath(Table<O> path, ForeignKey<O, TbDepartmentRecord> childPath, InverseForeignKey<O, TbDepartmentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TbDepartmentPath(Name alias, Table<TbDepartmentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TbDepartmentPath as(String alias) {
            return new TbDepartmentPath(DSL.name(alias), this);
        }

        @Override
        public TbDepartmentPath as(Name alias) {
            return new TbDepartmentPath(alias, this);
        }

        @Override
        public TbDepartmentPath as(Table<?> alias) {
            return new TbDepartmentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CbskDev.CBSK_DEV;
    }

    @Override
    public UniqueKey<TbDepartmentRecord> getPrimaryKey() {
        return Keys.KEY_TB_DEPARTMENT_PRIMARY;
    }

    @Override
    public List<ForeignKey<TbDepartmentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKVMJBITIJ88M9U9VC2YM4HEOV);
    }

    private transient TbCompanyPath _tbCompany;

    /**
     * Get the implicit join path to the <code>CBSK-DEV.TB_COMPANY</code> table.
     */
    public TbCompanyPath tbCompany() {
        if (_tbCompany == null)
            _tbCompany = new TbCompanyPath(this, Keys.FKVMJBITIJ88M9U9VC2YM4HEOV, null);

        return _tbCompany;
    }

    private transient TbUserPath _tbUser;

    /**
     * Get the implicit to-many join path to the <code>CBSK-DEV.TB_USER</code>
     * table
     */
    public TbUserPath tbUser() {
        if (_tbUser == null)
            _tbUser = new TbUserPath(this, null, Keys.FKJCDA7ENQGNL13EEO5SYHQFUNT.getInverseKey());

        return _tbUser;
    }

    @Override
    public TbDepartment as(String alias) {
        return new TbDepartment(DSL.name(alias), this);
    }

    @Override
    public TbDepartment as(Name alias) {
        return new TbDepartment(alias, this);
    }

    @Override
    public TbDepartment as(Table<?> alias) {
        return new TbDepartment(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbDepartment rename(String name) {
        return new TbDepartment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbDepartment rename(Name name) {
        return new TbDepartment(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbDepartment rename(Table<?> name) {
        return new TbDepartment(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbDepartment where(Condition condition) {
        return new TbDepartment(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbDepartment where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbDepartment where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbDepartment where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbDepartment where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbDepartment where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbDepartment where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbDepartment where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbDepartment whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbDepartment whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
