/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.CbskDev;
import com.basic.app.entity.jooq.Indexes;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.records.TbLogApiRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbLogApi extends TableImpl<TbLogApiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBSK-DEV.TB_LOG_API</code>
     */
    public static final TbLogApi TB_LOG_API = new TbLogApi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbLogApiRecord> getRecordType() {
        return TbLogApiRecord.class;
    }

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.CREATE_DATE</code>.
     */
    public final TableField<TbLogApiRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.END_DATE</code>.
     */
    public final TableField<TbLogApiRecord, LocalDateTime> END_DATE = createField(DSL.name("END_DATE"), SQLDataType.LOCALDATETIME(3), this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.EXEC_TIME</code>.
     */
    public final TableField<TbLogApiRecord, Long> EXEC_TIME = createField(DSL.name("EXEC_TIME"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.START_DATE</code>.
     */
    public final TableField<TbLogApiRecord, LocalDateTime> START_DATE = createField(DSL.name("START_DATE"), SQLDataType.LOCALDATETIME(3), this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.TIMESTAMP</code>.
     */
    public final TableField<TbLogApiRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.LOG_ID</code>.
     */
    public final TableField<TbLogApiRecord, String> LOG_ID = createField(DSL.name("LOG_ID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.CREATE_USER</code>.
     */
    public final TableField<TbLogApiRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.HTTP_METHOD</code>.
     */
    public final TableField<TbLogApiRecord, String> HTTP_METHOD = createField(DSL.name("HTTP_METHOD"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.IP_ADDR</code>.
     */
    public final TableField<TbLogApiRecord, String> IP_ADDR = createField(DSL.name("IP_ADDR"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.STATUS_CODE</code>.
     */
    public final TableField<TbLogApiRecord, String> STATUS_CODE = createField(DSL.name("STATUS_CODE"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.UPDATE_USER</code>.
     */
    public final TableField<TbLogApiRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.USER_AGENT</code>.
     */
    public final TableField<TbLogApiRecord, String> USER_AGENT = createField(DSL.name("USER_AGENT"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.USER_ID</code>.
     */
    public final TableField<TbLogApiRecord, String> USER_ID = createField(DSL.name("USER_ID"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.REQUEST_URI</code>.
     */
    public final TableField<TbLogApiRecord, String> REQUEST_URI = createField(DSL.name("REQUEST_URI"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.STS</code>.
     */
    public final TableField<TbLogApiRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.REQUEST_BODY</code>.
     */
    public final TableField<TbLogApiRecord, String> REQUEST_BODY = createField(DSL.name("REQUEST_BODY"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>CBSK-DEV.TB_LOG_API.RESPONSE_BODY</code>.
     */
    public final TableField<TbLogApiRecord, String> RESPONSE_BODY = createField(DSL.name("RESPONSE_BODY"), SQLDataType.CLOB, this, "");

    private TbLogApi(Name alias, Table<TbLogApiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbLogApi(Name alias, Table<TbLogApiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_LOG_API</code> table reference
     */
    public TbLogApi(String alias) {
        this(DSL.name(alias), TB_LOG_API);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_LOG_API</code> table reference
     */
    public TbLogApi(Name alias) {
        this(alias, TB_LOG_API);
    }

    /**
     * Create a <code>CBSK-DEV.TB_LOG_API</code> table reference
     */
    public TbLogApi() {
        this(DSL.name("TB_LOG_API"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CbskDev.CBSK_DEV;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.TB_LOG_API_IDX_ACCESS_LOG_END_DATE, Indexes.TB_LOG_API_IDX_ACCESS_LOG_IP_END_DATE, Indexes.TB_LOG_API_IDX_ACCESS_LOG_URI_END_DATE, Indexes.TB_LOG_API_IDX_ACCESS_LOG_USER_END_DATE);
    }

    @Override
    public UniqueKey<TbLogApiRecord> getPrimaryKey() {
        return Keys.KEY_TB_LOG_API_PRIMARY;
    }

    @Override
    public TbLogApi as(String alias) {
        return new TbLogApi(DSL.name(alias), this);
    }

    @Override
    public TbLogApi as(Name alias) {
        return new TbLogApi(alias, this);
    }

    @Override
    public TbLogApi as(Table<?> alias) {
        return new TbLogApi(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbLogApi rename(String name) {
        return new TbLogApi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbLogApi rename(Name name) {
        return new TbLogApi(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbLogApi rename(Table<?> name) {
        return new TbLogApi(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbLogApi where(Condition condition) {
        return new TbLogApi(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbLogApi where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbLogApi where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbLogApi where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbLogApi where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbLogApi where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbLogApi where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbLogApi where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbLogApi whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbLogApi whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
