/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.Cbms;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.records.TbLogActRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbLogAct extends TableImpl<TbLogActRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBMS.TB_LOG_ACT</code>
     */
    public static final TbLogAct TB_LOG_ACT = new TbLogAct();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbLogActRecord> getRecordType() {
        return TbLogActRecord.class;
    }

    /**
     * The column <code>CBMS.TB_LOG_ACT.LOG_ID</code>.
     */
    public final TableField<TbLogActRecord, String> LOG_ID = createField(DSL.name("LOG_ID"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_LOG_ACT.CREATE_DATE</code>.
     */
    public final TableField<TbLogActRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_LOG_ACT.CREATE_USER</code>.
     */
    public final TableField<TbLogActRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_LOG_ACT.STS</code>.
     */
    public final TableField<TbLogActRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBMS.TB_LOG_ACT.TIMESTAMP</code>.
     */
    public final TableField<TbLogActRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_LOG_ACT.UPDATE_USER</code>.
     */
    public final TableField<TbLogActRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_LOG_ACT.ACTION_TYPE</code>.
     */
    public final TableField<TbLogActRecord, String> ACTION_TYPE = createField(DSL.name("ACTION_TYPE"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>CBMS.TB_LOG_ACT.ACTION_TYPE_DETAIL</code>.
     */
    public final TableField<TbLogActRecord, String> ACTION_TYPE_DETAIL = createField(DSL.name("ACTION_TYPE_DETAIL"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>CBMS.TB_LOG_ACT.IP_ADDR</code>.
     */
    public final TableField<TbLogActRecord, String> IP_ADDR = createField(DSL.name("IP_ADDR"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>CBMS.TB_LOG_ACT.PAGE_URL</code>.
     */
    public final TableField<TbLogActRecord, String> PAGE_URL = createField(DSL.name("PAGE_URL"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>CBMS.TB_LOG_ACT.USER_ID</code>.
     */
    public final TableField<TbLogActRecord, String> USER_ID = createField(DSL.name("USER_ID"), SQLDataType.VARCHAR(45), this, "");

    private TbLogAct(Name alias, Table<TbLogActRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbLogAct(Name alias, Table<TbLogActRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBMS.TB_LOG_ACT</code> table reference
     */
    public TbLogAct(String alias) {
        this(DSL.name(alias), TB_LOG_ACT);
    }

    /**
     * Create an aliased <code>CBMS.TB_LOG_ACT</code> table reference
     */
    public TbLogAct(Name alias) {
        this(alias, TB_LOG_ACT);
    }

    /**
     * Create a <code>CBMS.TB_LOG_ACT</code> table reference
     */
    public TbLogAct() {
        this(DSL.name("TB_LOG_ACT"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cbms.CBMS;
    }

    @Override
    public UniqueKey<TbLogActRecord> getPrimaryKey() {
        return Keys.KEY_TB_LOG_ACT_PRIMARY;
    }

    @Override
    public TbLogAct as(String alias) {
        return new TbLogAct(DSL.name(alias), this);
    }

    @Override
    public TbLogAct as(Name alias) {
        return new TbLogAct(alias, this);
    }

    @Override
    public TbLogAct as(Table<?> alias) {
        return new TbLogAct(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbLogAct rename(String name) {
        return new TbLogAct(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbLogAct rename(Name name) {
        return new TbLogAct(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbLogAct rename(Table<?> name) {
        return new TbLogAct(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbLogAct where(Condition condition) {
        return new TbLogAct(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbLogAct where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbLogAct where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbLogAct where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbLogAct where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbLogAct where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbLogAct where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbLogAct where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbLogAct whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbLogAct whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
