/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.Cbms;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.records.TbMailMRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbMailM extends TableImpl<TbMailMRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBMS.TB_MAIL_M</code>
     */
    public static final TbMailM TB_MAIL_M = new TbMailM();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbMailMRecord> getRecordType() {
        return TbMailMRecord.class;
    }

    /**
     * The column <code>CBMS.TB_MAIL_M.MAIL_ID</code>.
     */
    public final TableField<TbMailMRecord, String> MAIL_ID = createField(DSL.name("MAIL_ID"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_MAIL_M.CREATE_DATE</code>.
     */
    public final TableField<TbMailMRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_MAIL_M.CREATE_USER</code>.
     */
    public final TableField<TbMailMRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_MAIL_M.STS</code>.
     */
    public final TableField<TbMailMRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBMS.TB_MAIL_M.TIMESTAMP</code>.
     */
    public final TableField<TbMailMRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_MAIL_M.UPDATE_USER</code>.
     */
    public final TableField<TbMailMRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_MAIL_M.CONTENT</code>.
     */
    public final TableField<TbMailMRecord, String> CONTENT = createField(DSL.name("CONTENT"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_MAIL_M.DESCRIPTION</code>.
     */
    public final TableField<TbMailMRecord, String> DESCRIPTION = createField(DSL.name("DESCRIPTION"), SQLDataType.VARCHAR(2048), this, "");

    /**
     * The column <code>CBMS.TB_MAIL_M.LANG_TYPE</code>.
     */
    public final TableField<TbMailMRecord, String> LANG_TYPE = createField(DSL.name("LANG_TYPE"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_MAIL_M.MAIL_NAME</code>.
     */
    public final TableField<TbMailMRecord, String> MAIL_NAME = createField(DSL.name("MAIL_NAME"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_MAIL_M.TITLE</code>.
     */
    public final TableField<TbMailMRecord, String> TITLE = createField(DSL.name("TITLE"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private TbMailM(Name alias, Table<TbMailMRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbMailM(Name alias, Table<TbMailMRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBMS.TB_MAIL_M</code> table reference
     */
    public TbMailM(String alias) {
        this(DSL.name(alias), TB_MAIL_M);
    }

    /**
     * Create an aliased <code>CBMS.TB_MAIL_M</code> table reference
     */
    public TbMailM(Name alias) {
        this(alias, TB_MAIL_M);
    }

    /**
     * Create a <code>CBMS.TB_MAIL_M</code> table reference
     */
    public TbMailM() {
        this(DSL.name("TB_MAIL_M"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cbms.CBMS;
    }

    @Override
    public UniqueKey<TbMailMRecord> getPrimaryKey() {
        return Keys.KEY_TB_MAIL_M_PRIMARY;
    }

    @Override
    public TbMailM as(String alias) {
        return new TbMailM(DSL.name(alias), this);
    }

    @Override
    public TbMailM as(Name alias) {
        return new TbMailM(alias, this);
    }

    @Override
    public TbMailM as(Table<?> alias) {
        return new TbMailM(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbMailM rename(String name) {
        return new TbMailM(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbMailM rename(Name name) {
        return new TbMailM(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbMailM rename(Table<?> name) {
        return new TbMailM(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMailM where(Condition condition) {
        return new TbMailM(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMailM where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMailM where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMailM where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbMailM where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbMailM where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbMailM where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbMailM where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMailM whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMailM whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
