/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.CbskDev;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.records.TbMailHRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbMailH extends TableImpl<TbMailHRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBSK-DEV.TB_MAIL_H</code>
     */
    public static final TbMailH TB_MAIL_H = new TbMailH();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbMailHRecord> getRecordType() {
        return TbMailHRecord.class;
    }

    /**
     * The column <code>CBSK-DEV.TB_MAIL_H.LOG_ID</code>.
     */
    public final TableField<TbMailHRecord, String> LOG_ID = createField(DSL.name("LOG_ID"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MAIL_H.CREATE_DATE</code>.
     */
    public final TableField<TbMailHRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MAIL_H.CREATE_USER</code>.
     */
    public final TableField<TbMailHRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MAIL_H.STS</code>.
     */
    public final TableField<TbMailHRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MAIL_H.TIMESTAMP</code>.
     */
    public final TableField<TbMailHRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MAIL_H.UPDATE_USER</code>.
     */
    public final TableField<TbMailHRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MAIL_H.CONTENT</code>.
     */
    public final TableField<TbMailHRecord, String> CONTENT = createField(DSL.name("CONTENT"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>CBSK-DEV.TB_MAIL_H.ERROR_MSG</code>.
     */
    public final TableField<TbMailHRecord, String> ERROR_MSG = createField(DSL.name("ERROR_MSG"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>CBSK-DEV.TB_MAIL_H.FROM_ADDR</code>.
     */
    public final TableField<TbMailHRecord, String> FROM_ADDR = createField(DSL.name("FROM_ADDR"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MAIL_H.MAIL_ID</code>.
     */
    public final TableField<TbMailHRecord, String> MAIL_ID = createField(DSL.name("MAIL_ID"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MAIL_H.SUCCESS</code>.
     */
    public final TableField<TbMailHRecord, String> SUCCESS = createField(DSL.name("SUCCESS"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MAIL_H.TITLE</code>.
     */
    public final TableField<TbMailHRecord, String> TITLE = createField(DSL.name("TITLE"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MAIL_H.TO_ADDR</code>.
     */
    public final TableField<TbMailHRecord, String> TO_ADDR = createField(DSL.name("TO_ADDR"), SQLDataType.CLOB, this, "");

    private TbMailH(Name alias, Table<TbMailHRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbMailH(Name alias, Table<TbMailHRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_MAIL_H</code> table reference
     */
    public TbMailH(String alias) {
        this(DSL.name(alias), TB_MAIL_H);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_MAIL_H</code> table reference
     */
    public TbMailH(Name alias) {
        this(alias, TB_MAIL_H);
    }

    /**
     * Create a <code>CBSK-DEV.TB_MAIL_H</code> table reference
     */
    public TbMailH() {
        this(DSL.name("TB_MAIL_H"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CbskDev.CBSK_DEV;
    }

    @Override
    public UniqueKey<TbMailHRecord> getPrimaryKey() {
        return Keys.KEY_TB_MAIL_H_PRIMARY;
    }

    @Override
    public TbMailH as(String alias) {
        return new TbMailH(DSL.name(alias), this);
    }

    @Override
    public TbMailH as(Name alias) {
        return new TbMailH(alias, this);
    }

    @Override
    public TbMailH as(Table<?> alias) {
        return new TbMailH(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbMailH rename(String name) {
        return new TbMailH(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbMailH rename(Name name) {
        return new TbMailH(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbMailH rename(Table<?> name) {
        return new TbMailH(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMailH where(Condition condition) {
        return new TbMailH(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMailH where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMailH where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMailH where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbMailH where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbMailH where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbMailH where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbMailH where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMailH whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMailH whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
