/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.CbskDev;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.TbMenu.TbMenuPath;
import com.basic.app.entity.jooq.tables.TbRole.TbRolePath;
import com.basic.app.entity.jooq.tables.TbRoleMenu.TbRoleMenuPath;
import com.basic.app.entity.jooq.tables.records.TbMenuRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbMenu extends TableImpl<TbMenuRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBSK-DEV.TB_MENU</code>
     */
    public static final TbMenu TB_MENU = new TbMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbMenuRecord> getRecordType() {
        return TbMenuRecord.class;
    }

    /**
     * The column <code>CBSK-DEV.TB_MENU.MENU_CD</code>.
     */
    public final TableField<TbMenuRecord, String> MENU_CD = createField(DSL.name("MENU_CD"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MENU.CREATE_DATE</code>.
     */
    public final TableField<TbMenuRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MENU.CREATE_USER</code>.
     */
    public final TableField<TbMenuRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MENU.STS</code>.
     */
    public final TableField<TbMenuRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MENU.TIMESTAMP</code>.
     */
    public final TableField<TbMenuRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MENU.UPDATE_USER</code>.
     */
    public final TableField<TbMenuRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MENU.MENU_LV</code>.
     */
    public final TableField<TbMenuRecord, Integer> MENU_LV = createField(DSL.name("MENU_LV"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MENU.MENU_NM</code>.
     */
    public final TableField<TbMenuRecord, String> MENU_NM = createField(DSL.name("MENU_NM"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MENU.MENU_URL</code>.
     */
    public final TableField<TbMenuRecord, String> MENU_URL = createField(DSL.name("MENU_URL"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MENU.ORDER_NUM</code>.
     */
    public final TableField<TbMenuRecord, Integer> ORDER_NUM = createField(DSL.name("ORDER_NUM"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MENU.USE_YN</code>.
     */
    public final TableField<TbMenuRecord, String> USE_YN = createField(DSL.name("USE_YN"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("N", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBSK-DEV.TB_MENU.UPPER_MENU_CD</code>.
     */
    public final TableField<TbMenuRecord, String> UPPER_MENU_CD = createField(DSL.name("UPPER_MENU_CD"), SQLDataType.VARCHAR(45), this, "");

    private TbMenu(Name alias, Table<TbMenuRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbMenu(Name alias, Table<TbMenuRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_MENU</code> table reference
     */
    public TbMenu(String alias) {
        this(DSL.name(alias), TB_MENU);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_MENU</code> table reference
     */
    public TbMenu(Name alias) {
        this(alias, TB_MENU);
    }

    /**
     * Create a <code>CBSK-DEV.TB_MENU</code> table reference
     */
    public TbMenu() {
        this(DSL.name("TB_MENU"), null);
    }

    public <O extends Record> TbMenu(Table<O> path, ForeignKey<O, TbMenuRecord> childPath, InverseForeignKey<O, TbMenuRecord> parentPath) {
        super(path, childPath, parentPath, TB_MENU);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TbMenuPath extends TbMenu implements Path<TbMenuRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TbMenuPath(Table<O> path, ForeignKey<O, TbMenuRecord> childPath, InverseForeignKey<O, TbMenuRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TbMenuPath(Name alias, Table<TbMenuRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TbMenuPath as(String alias) {
            return new TbMenuPath(DSL.name(alias), this);
        }

        @Override
        public TbMenuPath as(Name alias) {
            return new TbMenuPath(alias, this);
        }

        @Override
        public TbMenuPath as(Table<?> alias) {
            return new TbMenuPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CbskDev.CBSK_DEV;
    }

    @Override
    public UniqueKey<TbMenuRecord> getPrimaryKey() {
        return Keys.KEY_TB_MENU_PRIMARY;
    }

    @Override
    public List<ForeignKey<TbMenuRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKI4JQ5Q90M8E04JTKR7D5J1ULD);
    }

    private transient TbMenuPath _tbMenu;

    /**
     * Get the implicit join path to the <code>CBSK-DEV.TB_MENU</code> table.
     */
    public TbMenuPath tbMenu() {
        if (_tbMenu == null)
            _tbMenu = new TbMenuPath(this, Keys.FKI4JQ5Q90M8E04JTKR7D5J1ULD, null);

        return _tbMenu;
    }

    private transient TbRoleMenuPath _tbRoleMenu;

    /**
     * Get the implicit to-many join path to the
     * <code>CBSK-DEV.TB_ROLE_MENU</code> table
     */
    public TbRoleMenuPath tbRoleMenu() {
        if (_tbRoleMenu == null)
            _tbRoleMenu = new TbRoleMenuPath(this, null, Keys.FKQ4MSJY2YGWQY09W2OX0SUOJSV.getInverseKey());

        return _tbRoleMenu;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>CBSK-DEV.TB_ROLE</code> table
     */
    public TbRolePath tbRole() {
        return tbRoleMenu().tbRole();
    }

    @Override
    public TbMenu as(String alias) {
        return new TbMenu(DSL.name(alias), this);
    }

    @Override
    public TbMenu as(Name alias) {
        return new TbMenu(alias, this);
    }

    @Override
    public TbMenu as(Table<?> alias) {
        return new TbMenu(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbMenu rename(String name) {
        return new TbMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbMenu rename(Name name) {
        return new TbMenu(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbMenu rename(Table<?> name) {
        return new TbMenu(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMenu where(Condition condition) {
        return new TbMenu(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMenu where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMenu where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMenu where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbMenu where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbMenu where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbMenu where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbMenu where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMenu whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbMenu whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
