/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.Cbms;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.TbMenu.TbMenuPath;
import com.basic.app.entity.jooq.tables.TbRole.TbRolePath;
import com.basic.app.entity.jooq.tables.records.TbRoleMenuRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbRoleMenu extends TableImpl<TbRoleMenuRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBMS.TB_ROLE_MENU</code>
     */
    public static final TbRoleMenu TB_ROLE_MENU = new TbRoleMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbRoleMenuRecord> getRecordType() {
        return TbRoleMenuRecord.class;
    }

    /**
     * The column <code>CBMS.TB_ROLE_MENU.CREATE_DATE</code>.
     */
    public final TableField<TbRoleMenuRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_ROLE_MENU.CREATE_USER</code>.
     */
    public final TableField<TbRoleMenuRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_ROLE_MENU.STS</code>.
     */
    public final TableField<TbRoleMenuRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBMS.TB_ROLE_MENU.TIMESTAMP</code>.
     */
    public final TableField<TbRoleMenuRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_ROLE_MENU.UPDATE_USER</code>.
     */
    public final TableField<TbRoleMenuRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_ROLE_MENU.MENU_RW</code>.
     */
    public final TableField<TbRoleMenuRecord, String> MENU_RW = createField(DSL.name("MENU_RW"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>CBMS.TB_ROLE_MENU.USE_YN</code>.
     */
    public final TableField<TbRoleMenuRecord, String> USE_YN = createField(DSL.name("USE_YN"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("N", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBMS.TB_ROLE_MENU.MENU_CD</code>.
     */
    public final TableField<TbRoleMenuRecord, String> MENU_CD = createField(DSL.name("MENU_CD"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_ROLE_MENU.ROLE_CD</code>.
     */
    public final TableField<TbRoleMenuRecord, String> ROLE_CD = createField(DSL.name("ROLE_CD"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private TbRoleMenu(Name alias, Table<TbRoleMenuRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbRoleMenu(Name alias, Table<TbRoleMenuRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBMS.TB_ROLE_MENU</code> table reference
     */
    public TbRoleMenu(String alias) {
        this(DSL.name(alias), TB_ROLE_MENU);
    }

    /**
     * Create an aliased <code>CBMS.TB_ROLE_MENU</code> table reference
     */
    public TbRoleMenu(Name alias) {
        this(alias, TB_ROLE_MENU);
    }

    /**
     * Create a <code>CBMS.TB_ROLE_MENU</code> table reference
     */
    public TbRoleMenu() {
        this(DSL.name("TB_ROLE_MENU"), null);
    }

    public <O extends Record> TbRoleMenu(Table<O> path, ForeignKey<O, TbRoleMenuRecord> childPath, InverseForeignKey<O, TbRoleMenuRecord> parentPath) {
        super(path, childPath, parentPath, TB_ROLE_MENU);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TbRoleMenuPath extends TbRoleMenu implements Path<TbRoleMenuRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TbRoleMenuPath(Table<O> path, ForeignKey<O, TbRoleMenuRecord> childPath, InverseForeignKey<O, TbRoleMenuRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TbRoleMenuPath(Name alias, Table<TbRoleMenuRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TbRoleMenuPath as(String alias) {
            return new TbRoleMenuPath(DSL.name(alias), this);
        }

        @Override
        public TbRoleMenuPath as(Name alias) {
            return new TbRoleMenuPath(alias, this);
        }

        @Override
        public TbRoleMenuPath as(Table<?> alias) {
            return new TbRoleMenuPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cbms.CBMS;
    }

    @Override
    public UniqueKey<TbRoleMenuRecord> getPrimaryKey() {
        return Keys.KEY_TB_ROLE_MENU_PRIMARY;
    }

    @Override
    public List<ForeignKey<TbRoleMenuRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKCCRG3R0IBMLFE87KF9I4LSG65, Keys.FKQ4MSJY2YGWQY09W2OX0SUOJSV);
    }

    private transient TbRolePath _tbRole;

    /**
     * Get the implicit join path to the <code>CBMS.TB_ROLE</code> table.
     */
    public TbRolePath tbRole() {
        if (_tbRole == null)
            _tbRole = new TbRolePath(this, Keys.FKCCRG3R0IBMLFE87KF9I4LSG65, null);

        return _tbRole;
    }

    private transient TbMenuPath _tbMenu;

    /**
     * Get the implicit join path to the <code>CBMS.TB_MENU</code> table.
     */
    public TbMenuPath tbMenu() {
        if (_tbMenu == null)
            _tbMenu = new TbMenuPath(this, Keys.FKQ4MSJY2YGWQY09W2OX0SUOJSV, null);

        return _tbMenu;
    }

    @Override
    public TbRoleMenu as(String alias) {
        return new TbRoleMenu(DSL.name(alias), this);
    }

    @Override
    public TbRoleMenu as(Name alias) {
        return new TbRoleMenu(alias, this);
    }

    @Override
    public TbRoleMenu as(Table<?> alias) {
        return new TbRoleMenu(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbRoleMenu rename(String name) {
        return new TbRoleMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbRoleMenu rename(Name name) {
        return new TbRoleMenu(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbRoleMenu rename(Table<?> name) {
        return new TbRoleMenu(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbRoleMenu where(Condition condition) {
        return new TbRoleMenu(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbRoleMenu where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbRoleMenu where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbRoleMenu where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbRoleMenu where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbRoleMenu where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbRoleMenu where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbRoleMenu where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbRoleMenu whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbRoleMenu whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
