/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.CbskDev;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.records.TbScheHRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbScheH extends TableImpl<TbScheHRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBSK-DEV.TB_SCHE_H</code>
     */
    public static final TbScheH TB_SCHE_H = new TbScheH();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbScheHRecord> getRecordType() {
        return TbScheHRecord.class;
    }

    /**
     * The column <code>CBSK-DEV.TB_SCHE_H.LOG_ID</code>.
     */
    public final TableField<TbScheHRecord, String> LOG_ID = createField(DSL.name("LOG_ID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_SCHE_H.CREATE_DATE</code>.
     */
    public final TableField<TbScheHRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_SCHE_H.CREATE_USER</code>.
     */
    public final TableField<TbScheHRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_SCHE_H.STS</code>.
     */
    public final TableField<TbScheHRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBSK-DEV.TB_SCHE_H.TIMESTAMP</code>.
     */
    public final TableField<TbScheHRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_SCHE_H.UPDATE_USER</code>.
     */
    public final TableField<TbScheHRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_SCHE_H.END_TIME</code>.
     */
    public final TableField<TbScheHRecord, LocalDateTime> END_TIME = createField(DSL.name("END_TIME"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>CBSK-DEV.TB_SCHE_H.ERROR_MSG</code>.
     */
    public final TableField<TbScheHRecord, String> ERROR_MSG = createField(DSL.name("ERROR_MSG"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>CBSK-DEV.TB_SCHE_H.EXEC_TIME</code>.
     */
    public final TableField<TbScheHRecord, Long> EXEC_TIME = createField(DSL.name("EXEC_TIME"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>CBSK-DEV.TB_SCHE_H.SCHE_GROUP</code>.
     */
    public final TableField<TbScheHRecord, String> SCHE_GROUP = createField(DSL.name("SCHE_GROUP"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>CBSK-DEV.TB_SCHE_H.SCHE_ID</code>.
     */
    public final TableField<TbScheHRecord, String> SCHE_ID = createField(DSL.name("SCHE_ID"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>CBSK-DEV.TB_SCHE_H.START_TIME</code>.
     */
    public final TableField<TbScheHRecord, LocalDateTime> START_TIME = createField(DSL.name("START_TIME"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>CBSK-DEV.TB_SCHE_H.SUCCESS</code>.
     */
    public final TableField<TbScheHRecord, String> SUCCESS = createField(DSL.name("SUCCESS"), SQLDataType.VARCHAR(1), this, "");

    private TbScheH(Name alias, Table<TbScheHRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbScheH(Name alias, Table<TbScheHRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_SCHE_H</code> table reference
     */
    public TbScheH(String alias) {
        this(DSL.name(alias), TB_SCHE_H);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_SCHE_H</code> table reference
     */
    public TbScheH(Name alias) {
        this(alias, TB_SCHE_H);
    }

    /**
     * Create a <code>CBSK-DEV.TB_SCHE_H</code> table reference
     */
    public TbScheH() {
        this(DSL.name("TB_SCHE_H"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CbskDev.CBSK_DEV;
    }

    @Override
    public UniqueKey<TbScheHRecord> getPrimaryKey() {
        return Keys.KEY_TB_SCHE_H_PRIMARY;
    }

    @Override
    public TbScheH as(String alias) {
        return new TbScheH(DSL.name(alias), this);
    }

    @Override
    public TbScheH as(Name alias) {
        return new TbScheH(alias, this);
    }

    @Override
    public TbScheH as(Table<?> alias) {
        return new TbScheH(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbScheH rename(String name) {
        return new TbScheH(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbScheH rename(Name name) {
        return new TbScheH(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbScheH rename(Table<?> name) {
        return new TbScheH(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbScheH where(Condition condition) {
        return new TbScheH(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbScheH where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbScheH where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbScheH where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbScheH where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbScheH where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbScheH where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbScheH where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbScheH whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbScheH whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
