/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.Cbms;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.records.TbScheMRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbScheM extends TableImpl<TbScheMRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBMS.TB_SCHE_M</code>
     */
    public static final TbScheM TB_SCHE_M = new TbScheM();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbScheMRecord> getRecordType() {
        return TbScheMRecord.class;
    }

    /**
     * The column <code>CBMS.TB_SCHE_M.SCHE_ID</code>.
     */
    public final TableField<TbScheMRecord, String> SCHE_ID = createField(DSL.name("SCHE_ID"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SCHE_M.CREATE_DATE</code>.
     */
    public final TableField<TbScheMRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SCHE_M.CREATE_USER</code>.
     */
    public final TableField<TbScheMRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SCHE_M.STS</code>.
     */
    public final TableField<TbScheMRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBMS.TB_SCHE_M.TIMESTAMP</code>.
     */
    public final TableField<TbScheMRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SCHE_M.UPDATE_USER</code>.
     */
    public final TableField<TbScheMRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SCHE_M.CLASS_NAME</code>.
     */
    public final TableField<TbScheMRecord, String> CLASS_NAME = createField(DSL.name("CLASS_NAME"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SCHE_M.CRON_EXP</code>.
     */
    public final TableField<TbScheMRecord, String> CRON_EXP = createField(DSL.name("CRON_EXP"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SCHE_M.DESCRIPTION</code>.
     */
    public final TableField<TbScheMRecord, String> DESCRIPTION = createField(DSL.name("DESCRIPTION"), SQLDataType.VARCHAR(2048), this, "");

    /**
     * The column <code>CBMS.TB_SCHE_M.LAST_EXEC_TIME</code>.
     */
    public final TableField<TbScheMRecord, LocalDateTime> LAST_EXEC_TIME = createField(DSL.name("LAST_EXEC_TIME"), SQLDataType.LOCALDATETIME(3), this, "");

    /**
     * The column <code>CBMS.TB_SCHE_M.METHOD_NAME</code>.
     */
    public final TableField<TbScheMRecord, String> METHOD_NAME = createField(DSL.name("METHOD_NAME"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SCHE_M.NEXT_EXEC_TIME</code>.
     */
    public final TableField<TbScheMRecord, LocalDateTime> NEXT_EXEC_TIME = createField(DSL.name("NEXT_EXEC_TIME"), SQLDataType.LOCALDATETIME(3), this, "");

    /**
     * The column <code>CBMS.TB_SCHE_M.SCHE_GROUP</code>.
     */
    public final TableField<TbScheMRecord, String> SCHE_GROUP = createField(DSL.name("SCHE_GROUP"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SCHE_M.SCHE_NAME</code>.
     */
    public final TableField<TbScheMRecord, String> SCHE_NAME = createField(DSL.name("SCHE_NAME"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SCHE_M.TRIGGER_NAME</code>.
     */
    public final TableField<TbScheMRecord, String> TRIGGER_NAME = createField(DSL.name("TRIGGER_NAME"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SCHE_M.USE_YN</code>.
     */
    public final TableField<TbScheMRecord, String> USE_YN = createField(DSL.name("USE_YN"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("N", SQLDataType.VARCHAR)), this, "");

    private TbScheM(Name alias, Table<TbScheMRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbScheM(Name alias, Table<TbScheMRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBMS.TB_SCHE_M</code> table reference
     */
    public TbScheM(String alias) {
        this(DSL.name(alias), TB_SCHE_M);
    }

    /**
     * Create an aliased <code>CBMS.TB_SCHE_M</code> table reference
     */
    public TbScheM(Name alias) {
        this(alias, TB_SCHE_M);
    }

    /**
     * Create a <code>CBMS.TB_SCHE_M</code> table reference
     */
    public TbScheM() {
        this(DSL.name("TB_SCHE_M"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cbms.CBMS;
    }

    @Override
    public UniqueKey<TbScheMRecord> getPrimaryKey() {
        return Keys.KEY_TB_SCHE_M_PRIMARY;
    }

    @Override
    public TbScheM as(String alias) {
        return new TbScheM(DSL.name(alias), this);
    }

    @Override
    public TbScheM as(Name alias) {
        return new TbScheM(alias, this);
    }

    @Override
    public TbScheM as(Table<?> alias) {
        return new TbScheM(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbScheM rename(String name) {
        return new TbScheM(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbScheM rename(Name name) {
        return new TbScheM(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbScheM rename(Table<?> name) {
        return new TbScheM(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbScheM where(Condition condition) {
        return new TbScheM(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbScheM where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbScheM where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbScheM where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbScheM where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbScheM where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbScheM where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbScheM where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbScheM whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbScheM whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
