/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.Cbms;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.records.TbSmsHRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbSmsH extends TableImpl<TbSmsHRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBMS.TB_SMS_H</code>
     */
    public static final TbSmsH TB_SMS_H = new TbSmsH();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbSmsHRecord> getRecordType() {
        return TbSmsHRecord.class;
    }

    /**
     * The column <code>CBMS.TB_SMS_H.LOG_ID</code>.
     */
    public final TableField<TbSmsHRecord, String> LOG_ID = createField(DSL.name("LOG_ID"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SMS_H.CREATE_DATE</code>.
     */
    public final TableField<TbSmsHRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SMS_H.CREATE_USER</code>.
     */
    public final TableField<TbSmsHRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SMS_H.STS</code>.
     */
    public final TableField<TbSmsHRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBMS.TB_SMS_H.TIMESTAMP</code>.
     */
    public final TableField<TbSmsHRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SMS_H.UPDATE_USER</code>.
     */
    public final TableField<TbSmsHRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBMS.TB_SMS_H.ERROR_MSG</code>.
     */
    public final TableField<TbSmsHRecord, String> ERROR_MSG = createField(DSL.name("ERROR_MSG"), SQLDataType.VARCHAR(2048), this, "");

    /**
     * The column <code>CBMS.TB_SMS_H.FROM_PHONE</code>.
     */
    public final TableField<TbSmsHRecord, String> FROM_PHONE = createField(DSL.name("FROM_PHONE"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>CBMS.TB_SMS_H.SMS_ID</code>.
     */
    public final TableField<TbSmsHRecord, String> SMS_ID = createField(DSL.name("SMS_ID"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>CBMS.TB_SMS_H.SUCCESS</code>.
     */
    public final TableField<TbSmsHRecord, String> SUCCESS = createField(DSL.name("SUCCESS"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>CBMS.TB_SMS_H.TEXT</code>.
     */
    public final TableField<TbSmsHRecord, String> TEXT = createField(DSL.name("TEXT"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>CBMS.TB_SMS_H.TO_PHONE</code>.
     */
    public final TableField<TbSmsHRecord, String> TO_PHONE = createField(DSL.name("TO_PHONE"), SQLDataType.VARCHAR(45), this, "");

    private TbSmsH(Name alias, Table<TbSmsHRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbSmsH(Name alias, Table<TbSmsHRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBMS.TB_SMS_H</code> table reference
     */
    public TbSmsH(String alias) {
        this(DSL.name(alias), TB_SMS_H);
    }

    /**
     * Create an aliased <code>CBMS.TB_SMS_H</code> table reference
     */
    public TbSmsH(Name alias) {
        this(alias, TB_SMS_H);
    }

    /**
     * Create a <code>CBMS.TB_SMS_H</code> table reference
     */
    public TbSmsH() {
        this(DSL.name("TB_SMS_H"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cbms.CBMS;
    }

    @Override
    public UniqueKey<TbSmsHRecord> getPrimaryKey() {
        return Keys.KEY_TB_SMS_H_PRIMARY;
    }

    @Override
    public TbSmsH as(String alias) {
        return new TbSmsH(DSL.name(alias), this);
    }

    @Override
    public TbSmsH as(Name alias) {
        return new TbSmsH(alias, this);
    }

    @Override
    public TbSmsH as(Table<?> alias) {
        return new TbSmsH(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbSmsH rename(String name) {
        return new TbSmsH(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbSmsH rename(Name name) {
        return new TbSmsH(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbSmsH rename(Table<?> name) {
        return new TbSmsH(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbSmsH where(Condition condition) {
        return new TbSmsH(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbSmsH where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbSmsH where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbSmsH where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbSmsH where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbSmsH where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbSmsH where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbSmsH where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbSmsH whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbSmsH whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
