/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables;


import com.basic.app.entity.jooq.CbskDev;
import com.basic.app.entity.jooq.Keys;
import com.basic.app.entity.jooq.tables.records.TbWebSvcRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbWebSvc extends TableImpl<TbWebSvcRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBSK-DEV.TB_WEB_SVC</code>
     */
    public static final TbWebSvc TB_WEB_SVC = new TbWebSvc();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbWebSvcRecord> getRecordType() {
        return TbWebSvcRecord.class;
    }

    /**
     * The column <code>CBSK-DEV.TB_WEB_SVC.SVC_ID</code>.
     */
    public final TableField<TbWebSvcRecord, String> SVC_ID = createField(DSL.name("SVC_ID"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_WEB_SVC.CREATE_DATE</code>.
     */
    public final TableField<TbWebSvcRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("CREATE_DATE"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_WEB_SVC.CREATE_USER</code>.
     */
    public final TableField<TbWebSvcRecord, String> CREATE_USER = createField(DSL.name("CREATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_WEB_SVC.STS</code>.
     */
    public final TableField<TbWebSvcRecord, String> STS = createField(DSL.name("STS"), SQLDataType.VARCHAR(1).nullable(false).defaultValue(DSL.inline("C", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CBSK-DEV.TB_WEB_SVC.TIMESTAMP</code>.
     */
    public final TableField<TbWebSvcRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_WEB_SVC.UPDATE_USER</code>.
     */
    public final TableField<TbWebSvcRecord, String> UPDATE_USER = createField(DSL.name("UPDATE_USER"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>CBSK-DEV.TB_WEB_SVC.SVC_NAME</code>.
     */
    public final TableField<TbWebSvcRecord, String> SVC_NAME = createField(DSL.name("SVC_NAME"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private TbWebSvc(Name alias, Table<TbWebSvcRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbWebSvc(Name alias, Table<TbWebSvcRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_WEB_SVC</code> table reference
     */
    public TbWebSvc(String alias) {
        this(DSL.name(alias), TB_WEB_SVC);
    }

    /**
     * Create an aliased <code>CBSK-DEV.TB_WEB_SVC</code> table reference
     */
    public TbWebSvc(Name alias) {
        this(alias, TB_WEB_SVC);
    }

    /**
     * Create a <code>CBSK-DEV.TB_WEB_SVC</code> table reference
     */
    public TbWebSvc() {
        this(DSL.name("TB_WEB_SVC"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : CbskDev.CBSK_DEV;
    }

    @Override
    public UniqueKey<TbWebSvcRecord> getPrimaryKey() {
        return Keys.KEY_TB_WEB_SVC_PRIMARY;
    }

    @Override
    public TbWebSvc as(String alias) {
        return new TbWebSvc(DSL.name(alias), this);
    }

    @Override
    public TbWebSvc as(Name alias) {
        return new TbWebSvc(alias, this);
    }

    @Override
    public TbWebSvc as(Table<?> alias) {
        return new TbWebSvc(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbWebSvc rename(String name) {
        return new TbWebSvc(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbWebSvc rename(Name name) {
        return new TbWebSvc(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbWebSvc rename(Table<?> name) {
        return new TbWebSvc(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbWebSvc where(Condition condition) {
        return new TbWebSvc(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbWebSvc where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbWebSvc where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbWebSvc where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbWebSvc where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbWebSvc where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbWebSvc where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbWebSvc where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbWebSvc whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbWebSvc whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
