/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbBbs;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbBbsRecord extends UpdatableRecordImpl<TbBbsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBSK-DEV.TB_BBS.BBS_ID</code>.
     */
    public void setBbsId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_BBS.BBS_ID</code>.
     */
    public String getBbsId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_BBS.CREATE_DATE</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_BBS.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_BBS.CREATE_USER</code>.
     */
    public void setCreateUser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_BBS.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_BBS.STS</code>.
     */
    public void setSts(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_BBS.STS</code>.
     */
    public String getSts() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_BBS.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_BBS.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_BBS.UPDATE_USER</code>.
     */
    public void setUpdateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_BBS.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_BBS.BBS_TYPE</code>.
     */
    public void setBbsType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_BBS.BBS_TYPE</code>.
     */
    public String getBbsType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_BBS.CONTENT</code>.
     */
    public void setContent(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_BBS.CONTENT</code>.
     */
    public String getContent() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_BBS.TITLE</code>.
     */
    public void setTitle(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_BBS.TITLE</code>.
     */
    public String getTitle() {
        return (String) get(8);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_BBS.WRITE_DATE</code>.
     */
    public void setWriteDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_BBS.WRITE_DATE</code>.
     */
    public LocalDateTime getWriteDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_BBS.WRITOR</code>.
     */
    public void setWritor(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_BBS.WRITOR</code>.
     */
    public String getWritor() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbBbsRecord
     */
    public TbBbsRecord() {
        super(TbBbs.TB_BBS);
    }

    /**
     * Create a detached, initialised TbBbsRecord
     */
    public TbBbsRecord(String bbsId, LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, String bbsType, String content, String title, LocalDateTime writeDate, String writor) {
        super(TbBbs.TB_BBS);

        setBbsId(bbsId);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setBbsType(bbsType);
        setContent(content);
        setTitle(title);
        setWriteDate(writeDate);
        setWritor(writor);
        resetChangedOnNotNull();
    }
}
