/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbComCodeT;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbComCodeTRecord extends UpdatableRecordImpl<TbComCodeTRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBSK-DEV.TB_COM_CODE_T.ATTR_CD</code>.
     */
    public void setAttrCd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T.ATTR_CD</code>.
     */
    public String getAttrCd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_COM_CODE_T.CREATE_DATE</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_COM_CODE_T.CREATE_USER</code>.
     */
    public void setCreateUser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_COM_CODE_T.STS</code>.
     */
    public void setSts(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T.STS</code>.
     */
    public String getSts() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_COM_CODE_T.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_COM_CODE_T.UPDATE_USER</code>.
     */
    public void setUpdateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_COM_CODE_T.ATTR_NM</code>.
     */
    public void setAttrNm(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T.ATTR_NM</code>.
     */
    public String getAttrNm() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_COM_CODE_T.ORDER_NUM</code>.
     */
    public void setOrderNum(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T.ORDER_NUM</code>.
     */
    public Integer getOrderNum() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_COM_CODE_T.GRP_CD</code>.
     */
    public void setGrpCd(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COM_CODE_T.GRP_CD</code>.
     */
    public String getGrpCd() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbComCodeTRecord
     */
    public TbComCodeTRecord() {
        super(TbComCodeT.TB_COM_CODE_T);
    }

    /**
     * Create a detached, initialised TbComCodeTRecord
     */
    public TbComCodeTRecord(String attrCd, LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, String attrNm, Integer orderNum, String grpCd) {
        super(TbComCodeT.TB_COM_CODE_T);

        setAttrCd(attrCd);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setAttrNm(attrNm);
        setOrderNum(orderNum);
        setGrpCd(grpCd);
        resetChangedOnNotNull();
    }
}
