/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbCompany;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbCompanyRecord extends UpdatableRecordImpl<TbCompanyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBSK-DEV.TB_COMPANY.CREATE_DATE</code>.
     */
    public TbCompanyRecord setCreateDate(LocalDateTime value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COMPANY.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(0);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_COMPANY.TIMESTAMP</code>.
     */
    public TbCompanyRecord setTimestamp(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COMPANY.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_COMPANY.COMPANY_CODE</code>.
     */
    public TbCompanyRecord setCompanyCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COMPANY.COMPANY_CODE</code>.
     */
    public String getCompanyCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_COMPANY.CREATE_USER</code>.
     */
    public TbCompanyRecord setCreateUser(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COMPANY.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_COMPANY.UPDATE_USER</code>.
     */
    public TbCompanyRecord setUpdateUser(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COMPANY.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(4);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_COMPANY.COMPANY_NAME</code>.
     */
    public TbCompanyRecord setCompanyName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COMPANY.COMPANY_NAME</code>.
     */
    public String getCompanyName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_COMPANY.STS</code>.
     */
    public TbCompanyRecord setSts(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_COMPANY.STS</code>.
     */
    public String getSts() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbCompanyRecord
     */
    public TbCompanyRecord() {
        super(TbCompany.TB_COMPANY);
    }

    /**
     * Create a detached, initialised TbCompanyRecord
     */
    public TbCompanyRecord(LocalDateTime createDate, LocalDateTime timestamp, String companyCode, String createUser, String updateUser, String companyName, String sts) {
        super(TbCompany.TB_COMPANY);

        setCreateDate(createDate);
        setTimestamp(timestamp);
        setCompanyCode(companyCode);
        setCreateUser(createUser);
        setUpdateUser(updateUser);
        setCompanyName(companyName);
        setSts(sts);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TbCompanyRecord
     */
    public TbCompanyRecord(com.basic.app.entity.jooq.tables.pojos.TbCompany value) {
        super(TbCompany.TB_COMPANY);

        if (value != null) {
            setCreateDate(value.getCreateDate());
            setTimestamp(value.getTimestamp());
            setCompanyCode(value.getCompanyCode());
            setCreateUser(value.getCreateUser());
            setUpdateUser(value.getUpdateUser());
            setCompanyName(value.getCompanyName());
            setSts(value.getSts());
            resetChangedOnNotNull();
        }
    }
}
