/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbCompany;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbCompanyRecord extends UpdatableRecordImpl<TbCompanyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBMS.TB_COMPANY.COMPANY_CODE</code>.
     */
    public void setCompanyCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CBMS.TB_COMPANY.COMPANY_CODE</code>.
     */
    public String getCompanyCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CBMS.TB_COMPANY.CREATE_DATE</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>CBMS.TB_COMPANY.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBMS.TB_COMPANY.CREATE_USER</code>.
     */
    public void setCreateUser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CBMS.TB_COMPANY.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBMS.TB_COMPANY.STS</code>.
     */
    public void setSts(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CBMS.TB_COMPANY.STS</code>.
     */
    public String getSts() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBMS.TB_COMPANY.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>CBMS.TB_COMPANY.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>CBMS.TB_COMPANY.UPDATE_USER</code>.
     */
    public void setUpdateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CBMS.TB_COMPANY.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBMS.TB_COMPANY.COMPANY_NAME</code>.
     */
    public void setCompanyName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>CBMS.TB_COMPANY.COMPANY_NAME</code>.
     */
    public String getCompanyName() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbCompanyRecord
     */
    public TbCompanyRecord() {
        super(TbCompany.TB_COMPANY);
    }

    /**
     * Create a detached, initialised TbCompanyRecord
     */
    public TbCompanyRecord(String companyCode, LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, String companyName) {
        super(TbCompany.TB_COMPANY);

        setCompanyCode(companyCode);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setCompanyName(companyName);
        resetChangedOnNotNull();
    }
}
