/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbDepartment;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbDepartmentRecord extends UpdatableRecordImpl<TbDepartmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBMS.TB_DEPARTMENT.DEPT_CODE</code>.
     */
    public void setDeptCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CBMS.TB_DEPARTMENT.DEPT_CODE</code>.
     */
    public String getDeptCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CBMS.TB_DEPARTMENT.CREATE_DATE</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>CBMS.TB_DEPARTMENT.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBMS.TB_DEPARTMENT.CREATE_USER</code>.
     */
    public void setCreateUser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CBMS.TB_DEPARTMENT.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBMS.TB_DEPARTMENT.STS</code>.
     */
    public void setSts(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CBMS.TB_DEPARTMENT.STS</code>.
     */
    public String getSts() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBMS.TB_DEPARTMENT.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>CBMS.TB_DEPARTMENT.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>CBMS.TB_DEPARTMENT.UPDATE_USER</code>.
     */
    public void setUpdateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CBMS.TB_DEPARTMENT.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBMS.TB_DEPARTMENT.DEPT_LV</code>.
     */
    public void setDeptLv(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>CBMS.TB_DEPARTMENT.DEPT_LV</code>.
     */
    public Integer getDeptLv() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>CBMS.TB_DEPARTMENT.DEPT_NM</code>.
     */
    public void setDeptNm(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CBMS.TB_DEPARTMENT.DEPT_NM</code>.
     */
    public String getDeptNm() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CBMS.TB_DEPARTMENT.UPPER_DEPT_CODE</code>.
     */
    public void setUpperDeptCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>CBMS.TB_DEPARTMENT.UPPER_DEPT_CODE</code>.
     */
    public String getUpperDeptCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>CBMS.TB_DEPARTMENT.USE_YN</code>.
     */
    public void setUseYn(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>CBMS.TB_DEPARTMENT.USE_YN</code>.
     */
    public String getUseYn() {
        return (String) get(9);
    }

    /**
     * Setter for <code>CBMS.TB_DEPARTMENT.COMPANY_CODE</code>.
     */
    public void setCompanyCode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>CBMS.TB_DEPARTMENT.COMPANY_CODE</code>.
     */
    public String getCompanyCode() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbDepartmentRecord
     */
    public TbDepartmentRecord() {
        super(TbDepartment.TB_DEPARTMENT);
    }

    /**
     * Create a detached, initialised TbDepartmentRecord
     */
    public TbDepartmentRecord(String deptCode, LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, Integer deptLv, String deptNm, String upperDeptCode, String useYn, String companyCode) {
        super(TbDepartment.TB_DEPARTMENT);

        setDeptCode(deptCode);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setDeptLv(deptLv);
        setDeptNm(deptNm);
        setUpperDeptCode(upperDeptCode);
        setUseYn(useYn);
        setCompanyCode(companyCode);
        resetChangedOnNotNull();
    }
}
