/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbIf;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbIfRecord extends UpdatableRecordImpl<TbIfRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBSK-DEV.TB_IF.IF_ID</code>.
     */
    public TbIfRecord setIfId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_IF.IF_ID</code>.
     */
    public String getIfId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_IF.CREATE_DATE</code>.
     */
    public TbIfRecord setCreateDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_IF.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_IF.CREATE_USER</code>.
     */
    public TbIfRecord setCreateUser(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_IF.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_IF.STS</code>.
     */
    public TbIfRecord setSts(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_IF.STS</code>.
     */
    public String getSts() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_IF.TIMESTAMP</code>.
     */
    public TbIfRecord setTimestamp(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_IF.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_IF.UPDATE_USER</code>.
     */
    public TbIfRecord setUpdateUser(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_IF.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_IF.IF_NAME</code>.
     */
    public TbIfRecord setIfName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_IF.IF_NAME</code>.
     */
    public String getIfName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_IF.TEXT</code>.
     */
    public TbIfRecord setText(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_IF.TEXT</code>.
     */
    public String getText() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbIfRecord
     */
    public TbIfRecord() {
        super(TbIf.TB_IF);
    }

    /**
     * Create a detached, initialised TbIfRecord
     */
    public TbIfRecord(String ifId, LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, String ifName, String text) {
        super(TbIf.TB_IF);

        setIfId(ifId);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setIfName(ifName);
        setText(text);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TbIfRecord
     */
    public TbIfRecord(com.basic.app.entity.jooq.tables.pojos.TbIf value) {
        super(TbIf.TB_IF);

        if (value != null) {
            setIfId(value.getIfId());
            setCreateDate(value.getCreateDate());
            setCreateUser(value.getCreateUser());
            setSts(value.getSts());
            setTimestamp(value.getTimestamp());
            setUpdateUser(value.getUpdateUser());
            setIfName(value.getIfName());
            setText(value.getText());
            resetChangedOnNotNull();
        }
    }
}
