/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbIf;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbIfRecord extends UpdatableRecordImpl<TbIfRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBMS.TB_IF.IF_ID</code>.
     */
    public void setIfId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CBMS.TB_IF.IF_ID</code>.
     */
    public String getIfId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CBMS.TB_IF.CREATE_DATE</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>CBMS.TB_IF.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBMS.TB_IF.CREATE_USER</code>.
     */
    public void setCreateUser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CBMS.TB_IF.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBMS.TB_IF.STS</code>.
     */
    public void setSts(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CBMS.TB_IF.STS</code>.
     */
    public String getSts() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBMS.TB_IF.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>CBMS.TB_IF.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>CBMS.TB_IF.UPDATE_USER</code>.
     */
    public void setUpdateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CBMS.TB_IF.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBMS.TB_IF.IF_NAME</code>.
     */
    public void setIfName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>CBMS.TB_IF.IF_NAME</code>.
     */
    public String getIfName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CBMS.TB_IF.TEXT</code>.
     */
    public void setText(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CBMS.TB_IF.TEXT</code>.
     */
    public String getText() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbIfRecord
     */
    public TbIfRecord() {
        super(TbIf.TB_IF);
    }

    /**
     * Create a detached, initialised TbIfRecord
     */
    public TbIfRecord(String ifId, LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, String ifName, String text) {
        super(TbIf.TB_IF);

        setIfId(ifId);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setIfName(ifName);
        setText(text);
        resetChangedOnNotNull();
    }
}
