/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbLogError;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbLogErrorRecord extends UpdatableRecordImpl<TbLogErrorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_ERROR.CREATE_DATE</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(0, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(0);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_ERROR.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_ERROR.ERR_ID</code>.
     */
    public void setErrId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.ERR_ID</code>.
     */
    public String getErrId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_ERROR.CREATE_USER</code>.
     */
    public void setCreateUser(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_ERROR.HTTP_METHOD</code>.
     */
    public void setHttpMethod(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.HTTP_METHOD</code>.
     */
    public String getHttpMethod() {
        return (String) get(4);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_ERROR.IP_ADDR</code>.
     */
    public void setIpAddr(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.IP_ADDR</code>.
     */
    public String getIpAddr() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_ERROR.UPDATE_USER</code>.
     */
    public void setUpdateUser(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_ERROR.USER_AGENT</code>.
     */
    public void setUserAgent(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.USER_AGENT</code>.
     */
    public String getUserAgent() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_ERROR.USER_ID</code>.
     */
    public void setUserId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.USER_ID</code>.
     */
    public String getUserId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_ERROR.REQUEST_URI</code>.
     */
    public void setRequestUri(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.REQUEST_URI</code>.
     */
    public String getRequestUri() {
        return (String) get(9);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_ERROR.ERR_MSG</code>.
     */
    public void setErrMsg(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.ERR_MSG</code>.
     */
    public String getErrMsg() {
        return (String) get(10);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_ERROR.STS</code>.
     */
    public void setSts(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.STS</code>.
     */
    public String getSts() {
        return (String) get(11);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_ERROR.ERR_STACK</code>.
     */
    public void setErrStack(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_ERROR.ERR_STACK</code>.
     */
    public String getErrStack() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbLogErrorRecord
     */
    public TbLogErrorRecord() {
        super(TbLogError.TB_LOG_ERROR);
    }

    /**
     * Create a detached, initialised TbLogErrorRecord
     */
    public TbLogErrorRecord(LocalDateTime createDate, LocalDateTime timestamp, String errId, String createUser, String httpMethod, String ipAddr, String updateUser, String userAgent, String userId, String requestUri, String errMsg, String sts, String errStack) {
        super(TbLogError.TB_LOG_ERROR);

        setCreateDate(createDate);
        setTimestamp(timestamp);
        setErrId(errId);
        setCreateUser(createUser);
        setHttpMethod(httpMethod);
        setIpAddr(ipAddr);
        setUpdateUser(updateUser);
        setUserAgent(userAgent);
        setUserId(userId);
        setRequestUri(requestUri);
        setErrMsg(errMsg);
        setSts(sts);
        setErrStack(errStack);
        resetChangedOnNotNull();
    }
}
