/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbLogApi;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbLogApiRecord extends UpdatableRecordImpl<TbLogApiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.CREATE_DATE</code>.
     */
    public TbLogApiRecord setCreateDate(LocalDateTime value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(0);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.END_DATE</code>.
     */
    public TbLogApiRecord setEndDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.END_DATE</code>.
     */
    public LocalDateTime getEndDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.EXEC_TIME</code>.
     */
    public TbLogApiRecord setExecTime(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.EXEC_TIME</code>.
     */
    public Long getExecTime() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.START_DATE</code>.
     */
    public TbLogApiRecord setStartDate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.START_DATE</code>.
     */
    public LocalDateTime getStartDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.TIMESTAMP</code>.
     */
    public TbLogApiRecord setTimestamp(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.LOG_ID</code>.
     */
    public TbLogApiRecord setLogId(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.LOG_ID</code>.
     */
    public String getLogId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.CREATE_USER</code>.
     */
    public TbLogApiRecord setCreateUser(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.HTTP_METHOD</code>.
     */
    public TbLogApiRecord setHttpMethod(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.HTTP_METHOD</code>.
     */
    public String getHttpMethod() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.IP_ADDR</code>.
     */
    public TbLogApiRecord setIpAddr(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.IP_ADDR</code>.
     */
    public String getIpAddr() {
        return (String) get(8);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.STATUS_CODE</code>.
     */
    public TbLogApiRecord setStatusCode(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.STATUS_CODE</code>.
     */
    public String getStatusCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.UPDATE_USER</code>.
     */
    public TbLogApiRecord setUpdateUser(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(10);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.USER_AGENT</code>.
     */
    public TbLogApiRecord setUserAgent(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.USER_AGENT</code>.
     */
    public String getUserAgent() {
        return (String) get(11);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.USER_ID</code>.
     */
    public TbLogApiRecord setUserId(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.USER_ID</code>.
     */
    public String getUserId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.REQUEST_URI</code>.
     */
    public TbLogApiRecord setRequestUri(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.REQUEST_URI</code>.
     */
    public String getRequestUri() {
        return (String) get(13);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.STS</code>.
     */
    public TbLogApiRecord setSts(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.STS</code>.
     */
    public String getSts() {
        return (String) get(14);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.REQUEST_BODY</code>.
     */
    public TbLogApiRecord setRequestBody(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.REQUEST_BODY</code>.
     */
    public String getRequestBody() {
        return (String) get(15);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_LOG_API.RESPONSE_BODY</code>.
     */
    public TbLogApiRecord setResponseBody(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_LOG_API.RESPONSE_BODY</code>.
     */
    public String getResponseBody() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbLogApiRecord
     */
    public TbLogApiRecord() {
        super(TbLogApi.TB_LOG_API);
    }

    /**
     * Create a detached, initialised TbLogApiRecord
     */
    public TbLogApiRecord(LocalDateTime createDate, LocalDateTime endDate, Long execTime, LocalDateTime startDate, LocalDateTime timestamp, String logId, String createUser, String httpMethod, String ipAddr, String statusCode, String updateUser, String userAgent, String userId, String requestUri, String sts, String requestBody, String responseBody) {
        super(TbLogApi.TB_LOG_API);

        setCreateDate(createDate);
        setEndDate(endDate);
        setExecTime(execTime);
        setStartDate(startDate);
        setTimestamp(timestamp);
        setLogId(logId);
        setCreateUser(createUser);
        setHttpMethod(httpMethod);
        setIpAddr(ipAddr);
        setStatusCode(statusCode);
        setUpdateUser(updateUser);
        setUserAgent(userAgent);
        setUserId(userId);
        setRequestUri(requestUri);
        setSts(sts);
        setRequestBody(requestBody);
        setResponseBody(responseBody);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TbLogApiRecord
     */
    public TbLogApiRecord(com.basic.app.entity.jooq.tables.pojos.TbLogApi value) {
        super(TbLogApi.TB_LOG_API);

        if (value != null) {
            setCreateDate(value.getCreateDate());
            setEndDate(value.getEndDate());
            setExecTime(value.getExecTime());
            setStartDate(value.getStartDate());
            setTimestamp(value.getTimestamp());
            setLogId(value.getLogId());
            setCreateUser(value.getCreateUser());
            setHttpMethod(value.getHttpMethod());
            setIpAddr(value.getIpAddr());
            setStatusCode(value.getStatusCode());
            setUpdateUser(value.getUpdateUser());
            setUserAgent(value.getUserAgent());
            setUserId(value.getUserId());
            setRequestUri(value.getRequestUri());
            setSts(value.getSts());
            setRequestBody(value.getRequestBody());
            setResponseBody(value.getResponseBody());
            resetChangedOnNotNull();
        }
    }
}
