/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbLogAct;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbLogActRecord extends UpdatableRecordImpl<TbLogActRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBMS.TB_LOG_ACT.LOG_ID</code>.
     */
    public void setLogId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CBMS.TB_LOG_ACT.LOG_ID</code>.
     */
    public String getLogId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CBMS.TB_LOG_ACT.CREATE_DATE</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>CBMS.TB_LOG_ACT.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBMS.TB_LOG_ACT.CREATE_USER</code>.
     */
    public void setCreateUser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CBMS.TB_LOG_ACT.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBMS.TB_LOG_ACT.STS</code>.
     */
    public void setSts(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CBMS.TB_LOG_ACT.STS</code>.
     */
    public String getSts() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBMS.TB_LOG_ACT.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>CBMS.TB_LOG_ACT.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>CBMS.TB_LOG_ACT.UPDATE_USER</code>.
     */
    public void setUpdateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CBMS.TB_LOG_ACT.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBMS.TB_LOG_ACT.ACTION_TYPE</code>.
     */
    public void setActionType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>CBMS.TB_LOG_ACT.ACTION_TYPE</code>.
     */
    public String getActionType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CBMS.TB_LOG_ACT.ACTION_TYPE_DETAIL</code>.
     */
    public void setActionTypeDetail(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CBMS.TB_LOG_ACT.ACTION_TYPE_DETAIL</code>.
     */
    public String getActionTypeDetail() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CBMS.TB_LOG_ACT.IP_ADDR</code>.
     */
    public void setIpAddr(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>CBMS.TB_LOG_ACT.IP_ADDR</code>.
     */
    public String getIpAddr() {
        return (String) get(8);
    }

    /**
     * Setter for <code>CBMS.TB_LOG_ACT.PAGE_URL</code>.
     */
    public void setPageUrl(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>CBMS.TB_LOG_ACT.PAGE_URL</code>.
     */
    public String getPageUrl() {
        return (String) get(9);
    }

    /**
     * Setter for <code>CBMS.TB_LOG_ACT.USER_ID</code>.
     */
    public void setUserId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>CBMS.TB_LOG_ACT.USER_ID</code>.
     */
    public String getUserId() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbLogActRecord
     */
    public TbLogActRecord() {
        super(TbLogAct.TB_LOG_ACT);
    }

    /**
     * Create a detached, initialised TbLogActRecord
     */
    public TbLogActRecord(String logId, LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, String actionType, String actionTypeDetail, String ipAddr, String pageUrl, String userId) {
        super(TbLogAct.TB_LOG_ACT);

        setLogId(logId);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setActionType(actionType);
        setActionTypeDetail(actionTypeDetail);
        setIpAddr(ipAddr);
        setPageUrl(pageUrl);
        setUserId(userId);
        resetChangedOnNotNull();
    }
}
