/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbMailH;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbMailHRecord extends UpdatableRecordImpl<TbMailHRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBMS.TB_MAIL_H.LOG_ID</code>.
     */
    public void setLogId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CBMS.TB_MAIL_H.LOG_ID</code>.
     */
    public String getLogId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CBMS.TB_MAIL_H.CREATE_DATE</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>CBMS.TB_MAIL_H.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBMS.TB_MAIL_H.CREATE_USER</code>.
     */
    public void setCreateUser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CBMS.TB_MAIL_H.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBMS.TB_MAIL_H.STS</code>.
     */
    public void setSts(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CBMS.TB_MAIL_H.STS</code>.
     */
    public String getSts() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBMS.TB_MAIL_H.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>CBMS.TB_MAIL_H.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>CBMS.TB_MAIL_H.UPDATE_USER</code>.
     */
    public void setUpdateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CBMS.TB_MAIL_H.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBMS.TB_MAIL_H.CONTENT</code>.
     */
    public void setContent(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>CBMS.TB_MAIL_H.CONTENT</code>.
     */
    public String getContent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CBMS.TB_MAIL_H.ERROR_MSG</code>.
     */
    public void setErrorMsg(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CBMS.TB_MAIL_H.ERROR_MSG</code>.
     */
    public String getErrorMsg() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CBMS.TB_MAIL_H.FROM_ADDR</code>.
     */
    public void setFromAddr(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>CBMS.TB_MAIL_H.FROM_ADDR</code>.
     */
    public String getFromAddr() {
        return (String) get(8);
    }

    /**
     * Setter for <code>CBMS.TB_MAIL_H.MAIL_ID</code>.
     */
    public void setMailId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>CBMS.TB_MAIL_H.MAIL_ID</code>.
     */
    public String getMailId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>CBMS.TB_MAIL_H.SUCCESS</code>.
     */
    public void setSuccess(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>CBMS.TB_MAIL_H.SUCCESS</code>.
     */
    public String getSuccess() {
        return (String) get(10);
    }

    /**
     * Setter for <code>CBMS.TB_MAIL_H.TITLE</code>.
     */
    public void setTitle(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>CBMS.TB_MAIL_H.TITLE</code>.
     */
    public String getTitle() {
        return (String) get(11);
    }

    /**
     * Setter for <code>CBMS.TB_MAIL_H.TO_ADDR</code>.
     */
    public void setToAddr(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>CBMS.TB_MAIL_H.TO_ADDR</code>.
     */
    public String getToAddr() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbMailHRecord
     */
    public TbMailHRecord() {
        super(TbMailH.TB_MAIL_H);
    }

    /**
     * Create a detached, initialised TbMailHRecord
     */
    public TbMailHRecord(String logId, LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, String content, String errorMsg, String fromAddr, String mailId, String success, String title, String toAddr) {
        super(TbMailH.TB_MAIL_H);

        setLogId(logId);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setContent(content);
        setErrorMsg(errorMsg);
        setFromAddr(fromAddr);
        setMailId(mailId);
        setSuccess(success);
        setTitle(title);
        setToAddr(toAddr);
        resetChangedOnNotNull();
    }
}
