/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbNotice;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbNoticeRecord extends UpdatableRecordImpl<TbNoticeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBSK-DEV.TB_NOTICE.NOT_ID</code>.
     */
    public TbNoticeRecord setNotId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.NOT_ID</code>.
     */
    public String getNotId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_NOTICE.CREATE_DATE</code>.
     */
    public TbNoticeRecord setCreateDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_NOTICE.CREATE_USER</code>.
     */
    public TbNoticeRecord setCreateUser(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_NOTICE.STS</code>.
     */
    public TbNoticeRecord setSts(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.STS</code>.
     */
    public String getSts() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_NOTICE.TIMESTAMP</code>.
     */
    public TbNoticeRecord setTimestamp(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_NOTICE.UPDATE_USER</code>.
     */
    public TbNoticeRecord setUpdateUser(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_NOTICE.CONTENT</code>.
     */
    public TbNoticeRecord setContent(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.CONTENT</code>.
     */
    public String getContent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_NOTICE.NOT_TYPE</code>.
     */
    public TbNoticeRecord setNotType(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.NOT_TYPE</code>.
     */
    public String getNotType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_NOTICE.TITLE</code>.
     */
    public TbNoticeRecord setTitle(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.TITLE</code>.
     */
    public String getTitle() {
        return (String) get(8);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_NOTICE.WRITE_DATE</code>.
     */
    public TbNoticeRecord setWriteDate(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.WRITE_DATE</code>.
     */
    public LocalDateTime getWriteDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_NOTICE.WRITOR</code>.
     */
    public TbNoticeRecord setWritor(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_NOTICE.WRITOR</code>.
     */
    public String getWritor() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbNoticeRecord
     */
    public TbNoticeRecord() {
        super(TbNotice.TB_NOTICE);
    }

    /**
     * Create a detached, initialised TbNoticeRecord
     */
    public TbNoticeRecord(String notId, LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, String content, String notType, String title, LocalDateTime writeDate, String writor) {
        super(TbNotice.TB_NOTICE);

        setNotId(notId);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setContent(content);
        setNotType(notType);
        setTitle(title);
        setWriteDate(writeDate);
        setWritor(writor);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TbNoticeRecord
     */
    public TbNoticeRecord(com.basic.app.entity.jooq.tables.pojos.TbNotice value) {
        super(TbNotice.TB_NOTICE);

        if (value != null) {
            setNotId(value.getNotId());
            setCreateDate(value.getCreateDate());
            setCreateUser(value.getCreateUser());
            setSts(value.getSts());
            setTimestamp(value.getTimestamp());
            setUpdateUser(value.getUpdateUser());
            setContent(value.getContent());
            setNotType(value.getNotType());
            setTitle(value.getTitle());
            setWriteDate(value.getWriteDate());
            setWritor(value.getWritor());
            resetChangedOnNotNull();
        }
    }
}
