/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbRoleMenu;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbRoleMenuRecord extends UpdatableRecordImpl<TbRoleMenuRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBSK-DEV.TB_ROLE_MENU.CREATE_DATE</code>.
     */
    public TbRoleMenuRecord setCreateDate(LocalDateTime value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_ROLE_MENU.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(0);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_ROLE_MENU.CREATE_USER</code>.
     */
    public TbRoleMenuRecord setCreateUser(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_ROLE_MENU.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_ROLE_MENU.STS</code>.
     */
    public TbRoleMenuRecord setSts(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_ROLE_MENU.STS</code>.
     */
    public String getSts() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_ROLE_MENU.TIMESTAMP</code>.
     */
    public TbRoleMenuRecord setTimestamp(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_ROLE_MENU.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_ROLE_MENU.UPDATE_USER</code>.
     */
    public TbRoleMenuRecord setUpdateUser(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_ROLE_MENU.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(4);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_ROLE_MENU.MENU_RW</code>.
     */
    public TbRoleMenuRecord setMenuRw(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_ROLE_MENU.MENU_RW</code>.
     */
    public String getMenuRw() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_ROLE_MENU.USE_YN</code>.
     */
    public TbRoleMenuRecord setUseYn(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_ROLE_MENU.USE_YN</code>.
     */
    public String getUseYn() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_ROLE_MENU.MENU_CD</code>.
     */
    public TbRoleMenuRecord setMenuCd(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_ROLE_MENU.MENU_CD</code>.
     */
    public String getMenuCd() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_ROLE_MENU.ROLE_CD</code>.
     */
    public TbRoleMenuRecord setRoleCd(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_ROLE_MENU.ROLE_CD</code>.
     */
    public String getRoleCd() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbRoleMenuRecord
     */
    public TbRoleMenuRecord() {
        super(TbRoleMenu.TB_ROLE_MENU);
    }

    /**
     * Create a detached, initialised TbRoleMenuRecord
     */
    public TbRoleMenuRecord(LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, String menuRw, String useYn, String menuCd, String roleCd) {
        super(TbRoleMenu.TB_ROLE_MENU);

        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setMenuRw(menuRw);
        setUseYn(useYn);
        setMenuCd(menuCd);
        setRoleCd(roleCd);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TbRoleMenuRecord
     */
    public TbRoleMenuRecord(com.basic.app.entity.jooq.tables.pojos.TbRoleMenu value) {
        super(TbRoleMenu.TB_ROLE_MENU);

        if (value != null) {
            setCreateDate(value.getCreateDate());
            setCreateUser(value.getCreateUser());
            setSts(value.getSts());
            setTimestamp(value.getTimestamp());
            setUpdateUser(value.getUpdateUser());
            setMenuRw(value.getMenuRw());
            setUseYn(value.getUseYn());
            setMenuCd(value.getMenuCd());
            setRoleCd(value.getRoleCd());
            resetChangedOnNotNull();
        }
    }
}
