/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbRoleUser;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbRoleUserRecord extends UpdatableRecordImpl<TbRoleUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBMS.TB_ROLE_USER.CREATE_DATE</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(0, value);
    }

    /**
     * Getter for <code>CBMS.TB_ROLE_USER.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(0);
    }

    /**
     * Setter for <code>CBMS.TB_ROLE_USER.CREATE_USER</code>.
     */
    public void setCreateUser(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CBMS.TB_ROLE_USER.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CBMS.TB_ROLE_USER.STS</code>.
     */
    public void setSts(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CBMS.TB_ROLE_USER.STS</code>.
     */
    public String getSts() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBMS.TB_ROLE_USER.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>CBMS.TB_ROLE_USER.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>CBMS.TB_ROLE_USER.UPDATE_USER</code>.
     */
    public void setUpdateUser(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>CBMS.TB_ROLE_USER.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(4);
    }

    /**
     * Setter for <code>CBMS.TB_ROLE_USER.USE_YN</code>.
     */
    public void setUseYn(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CBMS.TB_ROLE_USER.USE_YN</code>.
     */
    public String getUseYn() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBMS.TB_ROLE_USER.ROLE_CD</code>.
     */
    public void setRoleCd(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>CBMS.TB_ROLE_USER.ROLE_CD</code>.
     */
    public String getRoleCd() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CBMS.TB_ROLE_USER.USER_ID</code>.
     */
    public void setUserId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CBMS.TB_ROLE_USER.USER_ID</code>.
     */
    public String getUserId() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbRoleUserRecord
     */
    public TbRoleUserRecord() {
        super(TbRoleUser.TB_ROLE_USER);
    }

    /**
     * Create a detached, initialised TbRoleUserRecord
     */
    public TbRoleUserRecord(LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, String useYn, String roleCd, String userId) {
        super(TbRoleUser.TB_ROLE_USER);

        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setUseYn(useYn);
        setRoleCd(roleCd);
        setUserId(userId);
        resetChangedOnNotNull();
    }
}
