/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbScheH;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbScheHRecord extends UpdatableRecordImpl<TbScheHRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBSK-DEV.TB_SCHE_H.LOG_ID</code>.
     */
    public void setLogId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.LOG_ID</code>.
     */
    public String getLogId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SCHE_H.CREATE_DATE</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SCHE_H.CREATE_USER</code>.
     */
    public void setCreateUser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SCHE_H.STS</code>.
     */
    public void setSts(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.STS</code>.
     */
    public String getSts() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SCHE_H.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SCHE_H.UPDATE_USER</code>.
     */
    public void setUpdateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SCHE_H.END_TIME</code>.
     */
    public void setEndTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.END_TIME</code>.
     */
    public LocalDateTime getEndTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SCHE_H.ERROR_MSG</code>.
     */
    public void setErrorMsg(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.ERROR_MSG</code>.
     */
    public String getErrorMsg() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SCHE_H.EXEC_TIME</code>.
     */
    public void setExecTime(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.EXEC_TIME</code>.
     */
    public Long getExecTime() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SCHE_H.SCHE_GROUP</code>.
     */
    public void setScheGroup(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.SCHE_GROUP</code>.
     */
    public String getScheGroup() {
        return (String) get(9);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SCHE_H.SCHE_ID</code>.
     */
    public void setScheId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.SCHE_ID</code>.
     */
    public String getScheId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SCHE_H.START_TIME</code>.
     */
    public void setStartTime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.START_TIME</code>.
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SCHE_H.SUCCESS</code>.
     */
    public void setSuccess(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SCHE_H.SUCCESS</code>.
     */
    public String getSuccess() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbScheHRecord
     */
    public TbScheHRecord() {
        super(TbScheH.TB_SCHE_H);
    }

    /**
     * Create a detached, initialised TbScheHRecord
     */
    public TbScheHRecord(String logId, LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, LocalDateTime endTime, String errorMsg, Long execTime, String scheGroup, String scheId, LocalDateTime startTime, String success) {
        super(TbScheH.TB_SCHE_H);

        setLogId(logId);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setEndTime(endTime);
        setErrorMsg(errorMsg);
        setExecTime(execTime);
        setScheGroup(scheGroup);
        setScheId(scheId);
        setStartTime(startTime);
        setSuccess(success);
        resetChangedOnNotNull();
    }
}
