/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbSmsH;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbSmsHRecord extends UpdatableRecordImpl<TbSmsHRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBMS.TB_SMS_H.LOG_ID</code>.
     */
    public void setLogId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CBMS.TB_SMS_H.LOG_ID</code>.
     */
    public String getLogId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CBMS.TB_SMS_H.CREATE_DATE</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>CBMS.TB_SMS_H.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBMS.TB_SMS_H.CREATE_USER</code>.
     */
    public void setCreateUser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CBMS.TB_SMS_H.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBMS.TB_SMS_H.STS</code>.
     */
    public void setSts(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CBMS.TB_SMS_H.STS</code>.
     */
    public String getSts() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBMS.TB_SMS_H.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>CBMS.TB_SMS_H.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>CBMS.TB_SMS_H.UPDATE_USER</code>.
     */
    public void setUpdateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CBMS.TB_SMS_H.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBMS.TB_SMS_H.ERROR_MSG</code>.
     */
    public void setErrorMsg(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>CBMS.TB_SMS_H.ERROR_MSG</code>.
     */
    public String getErrorMsg() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CBMS.TB_SMS_H.FROM_PHONE</code>.
     */
    public void setFromPhone(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CBMS.TB_SMS_H.FROM_PHONE</code>.
     */
    public String getFromPhone() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CBMS.TB_SMS_H.SMS_ID</code>.
     */
    public void setSmsId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>CBMS.TB_SMS_H.SMS_ID</code>.
     */
    public String getSmsId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>CBMS.TB_SMS_H.SUCCESS</code>.
     */
    public void setSuccess(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>CBMS.TB_SMS_H.SUCCESS</code>.
     */
    public String getSuccess() {
        return (String) get(9);
    }

    /**
     * Setter for <code>CBMS.TB_SMS_H.TEXT</code>.
     */
    public void setText(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>CBMS.TB_SMS_H.TEXT</code>.
     */
    public String getText() {
        return (String) get(10);
    }

    /**
     * Setter for <code>CBMS.TB_SMS_H.TO_PHONE</code>.
     */
    public void setToPhone(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>CBMS.TB_SMS_H.TO_PHONE</code>.
     */
    public String getToPhone() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbSmsHRecord
     */
    public TbSmsHRecord() {
        super(TbSmsH.TB_SMS_H);
    }

    /**
     * Create a detached, initialised TbSmsHRecord
     */
    public TbSmsHRecord(String logId, LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, String errorMsg, String fromPhone, String smsId, String success, String text, String toPhone) {
        super(TbSmsH.TB_SMS_H);

        setLogId(logId);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setErrorMsg(errorMsg);
        setFromPhone(fromPhone);
        setSmsId(smsId);
        setSuccess(success);
        setText(text);
        setToPhone(toPhone);
        resetChangedOnNotNull();
    }
}
