/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbSmsM;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbSmsMRecord extends UpdatableRecordImpl<TbSmsMRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_M.SMS_ID</code>.
     */
    public void setSmsId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_M.SMS_ID</code>.
     */
    public String getSmsId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_M.CREATE_DATE</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_M.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_M.CREATE_USER</code>.
     */
    public void setCreateUser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_M.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_M.STS</code>.
     */
    public void setSts(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_M.STS</code>.
     */
    public String getSts() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_M.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_M.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_M.UPDATE_USER</code>.
     */
    public void setUpdateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_M.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_M.DESCRIPTION</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_M.DESCRIPTION</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_M.LANG_TYPE</code>.
     */
    public void setLangType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_M.LANG_TYPE</code>.
     */
    public String getLangType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_M.SMS_NAME</code>.
     */
    public void setSmsName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_M.SMS_NAME</code>.
     */
    public String getSmsName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_M.TEXT</code>.
     */
    public void setText(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_M.TEXT</code>.
     */
    public String getText() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbSmsMRecord
     */
    public TbSmsMRecord() {
        super(TbSmsM.TB_SMS_M);
    }

    /**
     * Create a detached, initialised TbSmsMRecord
     */
    public TbSmsMRecord(String smsId, LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, String description, String langType, String smsName, String text) {
        super(TbSmsM.TB_SMS_M);

        setSmsId(smsId);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setDescription(description);
        setLangType(langType);
        setSmsName(smsName);
        setText(text);
        resetChangedOnNotNull();
    }
}
