/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbSmsH;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbSmsHRecord extends UpdatableRecordImpl<TbSmsHRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_H.LOG_ID</code>.
     */
    public TbSmsHRecord setLogId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.LOG_ID</code>.
     */
    public String getLogId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_H.CREATE_DATE</code>.
     */
    public TbSmsHRecord setCreateDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_H.CREATE_USER</code>.
     */
    public TbSmsHRecord setCreateUser(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_H.STS</code>.
     */
    public TbSmsHRecord setSts(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.STS</code>.
     */
    public String getSts() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_H.TIMESTAMP</code>.
     */
    public TbSmsHRecord setTimestamp(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_H.UPDATE_USER</code>.
     */
    public TbSmsHRecord setUpdateUser(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_H.ERROR_MSG</code>.
     */
    public TbSmsHRecord setErrorMsg(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.ERROR_MSG</code>.
     */
    public String getErrorMsg() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_H.FROM_PHONE</code>.
     */
    public TbSmsHRecord setFromPhone(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.FROM_PHONE</code>.
     */
    public String getFromPhone() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_H.SMS_ID</code>.
     */
    public TbSmsHRecord setSmsId(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.SMS_ID</code>.
     */
    public String getSmsId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_H.SUCCESS</code>.
     */
    public TbSmsHRecord setSuccess(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.SUCCESS</code>.
     */
    public String getSuccess() {
        return (String) get(9);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_H.TEXT</code>.
     */
    public TbSmsHRecord setText(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.TEXT</code>.
     */
    public String getText() {
        return (String) get(10);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_SMS_H.TO_PHONE</code>.
     */
    public TbSmsHRecord setToPhone(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_SMS_H.TO_PHONE</code>.
     */
    public String getToPhone() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbSmsHRecord
     */
    public TbSmsHRecord() {
        super(TbSmsH.TB_SMS_H);
    }

    /**
     * Create a detached, initialised TbSmsHRecord
     */
    public TbSmsHRecord(String logId, LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, String errorMsg, String fromPhone, String smsId, String success, String text, String toPhone) {
        super(TbSmsH.TB_SMS_H);

        setLogId(logId);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setErrorMsg(errorMsg);
        setFromPhone(fromPhone);
        setSmsId(smsId);
        setSuccess(success);
        setText(text);
        setToPhone(toPhone);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TbSmsHRecord
     */
    public TbSmsHRecord(com.basic.app.entity.jooq.tables.pojos.TbSmsH value) {
        super(TbSmsH.TB_SMS_H);

        if (value != null) {
            setLogId(value.getLogId());
            setCreateDate(value.getCreateDate());
            setCreateUser(value.getCreateUser());
            setSts(value.getSts());
            setTimestamp(value.getTimestamp());
            setUpdateUser(value.getUpdateUser());
            setErrorMsg(value.getErrorMsg());
            setFromPhone(value.getFromPhone());
            setSmsId(value.getSmsId());
            setSuccess(value.getSuccess());
            setText(value.getText());
            setToPhone(value.getToPhone());
            resetChangedOnNotNull();
        }
    }
}
