/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq.tables.records;


import com.basic.app.entity.jooq.tables.TbUser;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbUserRecord extends UpdatableRecordImpl<TbUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CBSK-DEV.TB_USER.USER_ID</code>.
     */
    public TbUserRecord setUserId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.USER_ID</code>.
     */
    public String getUserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_USER.CREATE_DATE</code>.
     */
    public TbUserRecord setCreateDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.CREATE_DATE</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_USER.CREATE_USER</code>.
     */
    public TbUserRecord setCreateUser(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.CREATE_USER</code>.
     */
    public String getCreateUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_USER.STS</code>.
     */
    public TbUserRecord setSts(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.STS</code>.
     */
    public String getSts() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_USER.TIMESTAMP</code>.
     */
    public TbUserRecord setTimestamp(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_USER.UPDATE_USER</code>.
     */
    public TbUserRecord setUpdateUser(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.UPDATE_USER</code>.
     */
    public String getUpdateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_USER.EMAIL</code>.
     */
    public TbUserRecord setEmail(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_USER.GENDER</code>.
     */
    public TbUserRecord setGender(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.GENDER</code>.
     */
    public String getGender() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_USER.NAME</code>.
     */
    public TbUserRecord setName(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.NAME</code>.
     */
    public String getName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_USER.PASSWORD</code>.
     */
    public TbUserRecord setPassword(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.PASSWORD</code>.
     */
    public String getPassword() {
        return (String) get(9);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_USER.PHONE_NUM</code>.
     */
    public TbUserRecord setPhoneNum(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.PHONE_NUM</code>.
     */
    public String getPhoneNum() {
        return (String) get(10);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_USER.ROLE</code>.
     */
    public TbUserRecord setRole(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.ROLE</code>.
     */
    public String getRole() {
        return (String) get(11);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_USER.USER_TYPE</code>.
     */
    public TbUserRecord setUserType(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.USER_TYPE</code>.
     */
    public String getUserType() {
        return (String) get(12);
    }

    /**
     * Setter for <code>CBSK-DEV.TB_USER.DEPT_CODE</code>.
     */
    public TbUserRecord setDeptCode(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>CBSK-DEV.TB_USER.DEPT_CODE</code>.
     */
    public String getDeptCode() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbUserRecord
     */
    public TbUserRecord() {
        super(TbUser.TB_USER);
    }

    /**
     * Create a detached, initialised TbUserRecord
     */
    public TbUserRecord(String userId, LocalDateTime createDate, String createUser, String sts, LocalDateTime timestamp, String updateUser, String email, String gender, String name, String password, String phoneNum, String role, String userType, String deptCode) {
        super(TbUser.TB_USER);

        setUserId(userId);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setSts(sts);
        setTimestamp(timestamp);
        setUpdateUser(updateUser);
        setEmail(email);
        setGender(gender);
        setName(name);
        setPassword(password);
        setPhoneNum(phoneNum);
        setRole(role);
        setUserType(userType);
        setDeptCode(deptCode);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TbUserRecord
     */
    public TbUserRecord(com.basic.app.entity.jooq.tables.pojos.TbUser value) {
        super(TbUser.TB_USER);

        if (value != null) {
            setUserId(value.getUserId());
            setCreateDate(value.getCreateDate());
            setCreateUser(value.getCreateUser());
            setSts(value.getSts());
            setTimestamp(value.getTimestamp());
            setUpdateUser(value.getUpdateUser());
            setEmail(value.getEmail());
            setGender(value.getGender());
            setName(value.getName());
            setPassword(value.getPassword());
            setPhoneNum(value.getPhoneNum());
            setRole(value.getRole());
            setUserType(value.getUserType());
            setDeptCode(value.getDeptCode());
            resetChangedOnNotNull();
        }
    }
}
