# [dev 프로필 전용 설정 파일]
server:
  port: 8080 # 개발 서버 포트

front-end:
  url: http://dev.cbmsori.com:3000 # 개발 환경 프론트엔드 URL

spring:
  profiles:
    group:
      env: dev

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/CBSK-DEV?useUnicode=true&serverTimezone=Asia/Seoul # 개발 DB 접속 URL (DOCKER DB명: CBSK-DEV)
    username: root
    password: root961019
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect # Hibernate가 사용할 DB 방언(Dialect) 지정 (MySQLDialect로 변경)
    hibernate:
      ddl-auto: validate # 애플리케이션 실행 시 DDL 자동 생성/수정 옵션 (none, update, create, create-drop 등)
    properties:
      hibernate:
        "[jdbc.batch_size]": 100
        "[show_sql]": false # 실행되는 SQL 쿼리를 콘솔에 비활성화
        "[format_sql]": true # SQL 쿼리를 보기 좋게 포맷팅해서 출력
        "[use_sql_comments]": true # SQL 쿼리에 주석 추가해서 출력

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: host.docker.internal
      port: 6379
      database: 0 # Redis 데이터베이스 번호 (0~15, 기본 0)
      timeout: 30000ms

  quartz:
    job-store-type: jdbc # Quartz 상태 저장 방식을 JDBC(DB)로 설정
    jdbc:
      initialize-schema: never # 스키마 자동 생성 비활성화 (직접 SQL 실행 후 사용)
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyClusteredScheduler # 스케줄러 이름, 클러스터 내 구분용
            instanceId: AUTO # 클러스터 노드별 고유 ID 자동 생성

          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX # 트랜잭션 지원하는 JDBC JobStore 구현체
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate # MySQL용 드라이버 델리게이트
            useProperties: false # 잡 데이터 저장시 별도 properties 사용 안함
            dataSource: myDS # 사용할 데이터소스 이름
            tablePrefix: QRTZ_ # Quartz 테이블 접두사
            isClustered: true # 클러스터링 활성화
            clusterCheckinInterval: 20000 # 클러스터 상태 점검 주기 (밀리초, 20초)

          threadPool:
            threadCount: 10 # Quartz 스레드 풀 크기 (동시 실행 가능한 잡 수)

          dataSource:
            myDS:
              driver: com.mysql.cj.jdbc.Driver # 데이터소스 드라이버
              URL: jdbc:mysql://host.docker.internal:3306/CBSK-QUARTZ?useUnicode=true&serverTimezone=Asia/Seoul
              user: root # 데이터소스 사용자명
              password: root961019 # 데이터소스 비밀번호

  mail:
    host: smtp.gmail.com
    port: 587
    username: ksygt728.study@gmail.com
    alias: "[CBSK] SYSTEM-DEV"
    password: awuc myeu ipxo vjdc
    max-mail-queue: 1000 # 메일 큐 최대 크기
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  sms:
    provider: coolSMS
    api-key: NCSNCL3RFCGBWVHC
    api-secret-key: AKKSPK5FYIHGQVVDRP4OCLAJTQGQJYT6
    api-domain: https://api.solapi.com # SMS API 도메인
    from-phone: 01084320767

  security:
    oauth2:
      client:
        registration:
          # ------------------- Kakao -------------------
          kakao:
            client-id: 305da1aa1489acfde40743eecdd25716 # 카카오 개발자센터에서 발급받은 REST API Key
            client-secret: K5PHcStiFJhdhx1nlu4Bgrzx2jewx6iz # 필요 시 카카오 앱 시크릿
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-authentication-method: client_secret_post

          # ------------------- Naver -------------------
          naver:
            client-id: lzmJMjrfOVC3E0CtO8Bq # 네이버 개발자센터에서 발급받은 Client ID
            client-secret: t96zRG_Fdk # 네이버 개발자센터에서 발급받은 Client Secret
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - name
              - email
            client-authentication-method: client_secret_post

          # ------------------- Google -------------------
          google:
            client-id: 425928171876-d8f6h7f73bp66akn1c7a085vr3pm6sit.apps.googleusercontent.com # 구글 Cloud Console에서 발급받은 Client ID
            client-secret: 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 # 구글 Client Secret
            client-name: google
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - profile
              - email
            client-authentication-method: client_secret_post

        provider:
          # ------------------- Kakao -------------------
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 카카오 인증 URL
            token-uri: https://kauth.kakao.com/oauth/token # 카카오 토큰 발급 URL
            user-info-uri: https://kapi.kakao.com/v2/user/me # 카카오 사용자 정보 조회 URL
            user-name-attribute: id # 카카오 사용자 ID 속성명

          # ------------------- Naver -------------------
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 인증 URL
            token-uri: https://nid.naver.com/oauth2.0/token # 네이버 토큰 발급 URL
            user-info-uri: https://openapi.naver.com/v1/nid/me # 네이버 사용자 정보 조회 URL
            user-name-attribute: response # 네이버 사용자 ID 속성명

          # ------------------- Google -------------------
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth # 구글 인증 URL
            token-uri: https://oauth2.googleapis.com/token # 구글 토큰 발급 URL
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo # 구글 사용자 정보 조회 URL
            user-name-attribute: sub # 구글 사용자 ID 속성명

  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: log-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 500 # 한 번에 가져올 최대 레코드 수
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        "[max.poll.interval.ms]": 300000
        "[session.timeout.ms]": 600000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.type.mapping]": "LogApi:com.basic.app.entity.LogApi"
    listener:
      concurrency: 5 # 1개 인스턴스 5개 컨슈머 스레드 생성
      missing-topics-fatal: false # 리스너가 시작 시 존재하지 않는 토픽이 있어도 예외 발생시키지 않음 (개발 편의 목적)

logging:
  level:
    root: info # 기본 로깅 레벨
    org:
      jooq: debug
      "[jooq.tools]": debug
      "[jooq.tools.LoggerListener]": debug
      "[springframework.kafka]": error
      hibernate:
        SQL: debug # 실행되는 SQL 출력
        orm:
          jdbc:
            bind: trace # Hibernate 6 이상에서 바인딩 값 출력
    com:
      basic:
        app: debug
        featureTest: debug # 테스트 패키지
  pattern:
    console: "\u001B[1;36m%d{yyyy-MM-dd HH:mm:ss.SSS}\u001B[0m \u001B[35m[%thread-%X{tid}][%X{traceId}]\u001B[0m \u001B[1;33m[%level]\u001B[0m \u001B[32m%logger{32}.%M:%L : \u001B[34m%msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%-5level] %logger{36} - %msg%n"

jwt:
  env: dev # 현재 활성화된 프로필 설정 (dev 프로필 사용)
  testId: ADMIN # 테스트용 토큰 사용 여부
  access-token-header: Authorization-AccessToken-DEV
  refresh-token-header: Authorization-RefreshToken-DEV
  bearer-type: Bearer
  issuer: CBSK SERVER(DEV)
  subject:
    first: CBSK JWT TOKEN
    second: userId
    third: phoneNum
    fourth: roles
  expire-time:
    access-token: 10m # 10분 = 1000 * 60 * 10
    refresh-token: 1d
  dead-time-for-server: 10s # 10초
  secret-key: CBSK-DEV-SECRET-KEY-KSYGT728-ORI-IS-THE-BEST-ANIMAL # JWT 서명에 사용할 비밀 키

springdoc:
  swagger-ui:
    enabled: true # UI 활성화
    path: /swagger-ui.html # 기본 접속 경로 지정
    operations-sorter: method # 정렬 방식 (alpha, method)
    tags-sorter: alpha
  api-docs:
    enabled: true # openApi 문서 활성화
    path: /api-docs
  override-with-generic-response: false # 일반화된 응답 사용 여부 결정
