version: "3.9"

services:
  back:
    image: ${REGISTRY}/${IMAGE_NAME}-${ENV}:${IMAGE_TAG}
    container_name: ${IMAGE_NAME}-${ENV}
    restart: unless-stopped
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: ${ENV}
    networks:
      - cbms-net

networks:
  cbms-net:
    external: true
