version: '3.8'

services:
  mysql-prod:
    image: mysql:8.0
    container_name: CBSK-DB-PROD
    environment:
      MYSQL_ROOT_PASSWORD: root961019
      MYSQL_DATABASE: CBSK-PROD
      TZ: Asia/Seoul
    ports:
      - "3308:3306"
    volumes:
      - mysql-prod-data:/var/lib/mysql

  redis-prod:
    image: redis:latest
    container_name: CBSK-REDIS-PROD
    environment:
      TZ: Asia/Seoul
    ports:
      - "6381:6379"
    volumes:
      - redis-prod-data:/data

  zookeeper-prod:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: CBSK-ZOOKEEPER-PROD
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2183:2181"

  kafka-prod:
    image: confluentinc/cp-kafka:7.4.0
    container_name: CBSK-KAFKA-PROD
    depends_on:
      - zookeeper-prod
    ports:
      - "9094:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-prod:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mysql-prod-data:
  redis-prod-data: