version: "3.8"

services:
  mysql-prod:
    image: mysql:8.0
    container_name: CBSK-DB-PROD
    environment:
      MYSQL_ROOT_PASSWORD: root961019
      MYSQL_DATABASE: CBSK-PROD
      TZ: Asia/Seoul
    ports:
      - "3308:3306"
    logging:
      driver: "none"
    volumes:
      - mysql-prod-data:/var/lib/mysql

  redis-prod:
    image: redis:latest
    container_name: CBSK-REDIS-PROD
    environment:
      TZ: Asia/Seoul
    ports:
      - "6381:6379"
    logging:
      driver: "none"
    volumes:
      - redis-prod-data:/data

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: CBSK-ZOOKEEPER-PROD
    ports:
      - "2183:2181" # PROD용 포트 분리
    logging:
      driver: "none"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: CBSK-KAFKA-PROD
    ports:
      - "9094:9092" # PROD용 포트 분리
    logging:
      driver: "none"
    environment:
      # 외부 접근을 위한 리스너 설정
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://prod.cbmsori.com:9094,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: CBSK-KAFKA-UI-PROD
    ports:
      - "9082:8080" # PROD용 포트 분리
    logging:
      driver: "none"
    depends_on:
      - kafka
      - zookeeper
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_NAME=prod
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

volumes:
  mysql-prod-data:
  redis-prod-data:
