/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq;


import com.basic.app.entity.jooq.tables.TbBbs;
import com.basic.app.entity.jooq.tables.TbBbsComment;
import com.basic.app.entity.jooq.tables.TbChaebun;
import com.basic.app.entity.jooq.tables.TbComCodeD;
import com.basic.app.entity.jooq.tables.TbComCodeDPivot;
import com.basic.app.entity.jooq.tables.TbComCodeM;
import com.basic.app.entity.jooq.tables.TbComCodeT;
import com.basic.app.entity.jooq.tables.TbComCodeTPivot;
import com.basic.app.entity.jooq.tables.TbCompany;
import com.basic.app.entity.jooq.tables.TbDepartment;
import com.basic.app.entity.jooq.tables.TbIf;
import com.basic.app.entity.jooq.tables.TbLogAct;
import com.basic.app.entity.jooq.tables.TbLogApi;
import com.basic.app.entity.jooq.tables.TbLogError;
import com.basic.app.entity.jooq.tables.TbMailH;
import com.basic.app.entity.jooq.tables.TbMailM;
import com.basic.app.entity.jooq.tables.TbMenu;
import com.basic.app.entity.jooq.tables.TbMulLang;
import com.basic.app.entity.jooq.tables.TbNotice;
import com.basic.app.entity.jooq.tables.TbRole;
import com.basic.app.entity.jooq.tables.TbRoleMenu;
import com.basic.app.entity.jooq.tables.TbRoleUser;
import com.basic.app.entity.jooq.tables.TbScheH;
import com.basic.app.entity.jooq.tables.TbScheM;
import com.basic.app.entity.jooq.tables.TbSmsH;
import com.basic.app.entity.jooq.tables.TbSmsM;
import com.basic.app.entity.jooq.tables.TbUser;
import com.basic.app.entity.jooq.tables.TbWebSvc;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CbskDev extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CBSK-DEV</code>
     */
    public static final CbskDev CBSK_DEV = new CbskDev();

    /**
     * The table <code>CBSK-DEV.TB_BBS</code>.
     */
    public final TbBbs TB_BBS = TbBbs.TB_BBS;

    /**
     * The table <code>CBSK-DEV.TB_BBS_COMMENT</code>.
     */
    public final TbBbsComment TB_BBS_COMMENT = TbBbsComment.TB_BBS_COMMENT;

    /**
     * The table <code>CBSK-DEV.TB_CHAEBUN</code>.
     */
    public final TbChaebun TB_CHAEBUN = TbChaebun.TB_CHAEBUN;

    /**
     * The table <code>CBSK-DEV.TB_COM_CODE_D</code>.
     */
    public final TbComCodeD TB_COM_CODE_D = TbComCodeD.TB_COM_CODE_D;

    /**
     * The table <code>CBSK-DEV.TB_COM_CODE_D_PIVOT</code>.
     */
    public final TbComCodeDPivot TB_COM_CODE_D_PIVOT = TbComCodeDPivot.TB_COM_CODE_D_PIVOT;

    /**
     * The table <code>CBSK-DEV.TB_COM_CODE_M</code>.
     */
    public final TbComCodeM TB_COM_CODE_M = TbComCodeM.TB_COM_CODE_M;

    /**
     * The table <code>CBSK-DEV.TB_COM_CODE_T</code>.
     */
    public final TbComCodeT TB_COM_CODE_T = TbComCodeT.TB_COM_CODE_T;

    /**
     * The table <code>CBSK-DEV.TB_COM_CODE_T_PIVOT</code>.
     */
    public final TbComCodeTPivot TB_COM_CODE_T_PIVOT = TbComCodeTPivot.TB_COM_CODE_T_PIVOT;

    /**
     * The table <code>CBSK-DEV.TB_COMPANY</code>.
     */
    public final TbCompany TB_COMPANY = TbCompany.TB_COMPANY;

    /**
     * The table <code>CBSK-DEV.TB_DEPARTMENT</code>.
     */
    public final TbDepartment TB_DEPARTMENT = TbDepartment.TB_DEPARTMENT;

    /**
     * The table <code>CBSK-DEV.TB_IF</code>.
     */
    public final TbIf TB_IF = TbIf.TB_IF;

    /**
     * The table <code>CBSK-DEV.TB_LOG_ACT</code>.
     */
    public final TbLogAct TB_LOG_ACT = TbLogAct.TB_LOG_ACT;

    /**
     * The table <code>CBSK-DEV.TB_LOG_API</code>.
     */
    public final TbLogApi TB_LOG_API = TbLogApi.TB_LOG_API;

    /**
     * The table <code>CBSK-DEV.TB_LOG_ERROR</code>.
     */
    public final TbLogError TB_LOG_ERROR = TbLogError.TB_LOG_ERROR;

    /**
     * The table <code>CBSK-DEV.TB_MAIL_H</code>.
     */
    public final TbMailH TB_MAIL_H = TbMailH.TB_MAIL_H;

    /**
     * The table <code>CBSK-DEV.TB_MAIL_M</code>.
     */
    public final TbMailM TB_MAIL_M = TbMailM.TB_MAIL_M;

    /**
     * The table <code>CBSK-DEV.TB_MENU</code>.
     */
    public final TbMenu TB_MENU = TbMenu.TB_MENU;

    /**
     * The table <code>CBSK-DEV.TB_MUL_LANG</code>.
     */
    public final TbMulLang TB_MUL_LANG = TbMulLang.TB_MUL_LANG;

    /**
     * The table <code>CBSK-DEV.TB_NOTICE</code>.
     */
    public final TbNotice TB_NOTICE = TbNotice.TB_NOTICE;

    /**
     * The table <code>CBSK-DEV.TB_ROLE</code>.
     */
    public final TbRole TB_ROLE = TbRole.TB_ROLE;

    /**
     * The table <code>CBSK-DEV.TB_ROLE_MENU</code>.
     */
    public final TbRoleMenu TB_ROLE_MENU = TbRoleMenu.TB_ROLE_MENU;

    /**
     * The table <code>CBSK-DEV.TB_ROLE_USER</code>.
     */
    public final TbRoleUser TB_ROLE_USER = TbRoleUser.TB_ROLE_USER;

    /**
     * The table <code>CBSK-DEV.TB_SCHE_H</code>.
     */
    public final TbScheH TB_SCHE_H = TbScheH.TB_SCHE_H;

    /**
     * The table <code>CBSK-DEV.TB_SCHE_M</code>.
     */
    public final TbScheM TB_SCHE_M = TbScheM.TB_SCHE_M;

    /**
     * The table <code>CBSK-DEV.TB_SMS_H</code>.
     */
    public final TbSmsH TB_SMS_H = TbSmsH.TB_SMS_H;

    /**
     * The table <code>CBSK-DEV.TB_SMS_M</code>.
     */
    public final TbSmsM TB_SMS_M = TbSmsM.TB_SMS_M;

    /**
     * The table <code>CBSK-DEV.TB_USER</code>.
     */
    public final TbUser TB_USER = TbUser.TB_USER;

    /**
     * The table <code>CBSK-DEV.TB_WEB_SVC</code>.
     */
    public final TbWebSvc TB_WEB_SVC = TbWebSvc.TB_WEB_SVC;

    /**
     * No further instances allowed
     */
    private CbskDev() {
        super("CBSK-DEV", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            TbBbs.TB_BBS,
            TbBbsComment.TB_BBS_COMMENT,
            TbChaebun.TB_CHAEBUN,
            TbComCodeD.TB_COM_CODE_D,
            TbComCodeDPivot.TB_COM_CODE_D_PIVOT,
            TbComCodeM.TB_COM_CODE_M,
            TbComCodeT.TB_COM_CODE_T,
            TbComCodeTPivot.TB_COM_CODE_T_PIVOT,
            TbCompany.TB_COMPANY,
            TbDepartment.TB_DEPARTMENT,
            TbIf.TB_IF,
            TbLogAct.TB_LOG_ACT,
            TbLogApi.TB_LOG_API,
            TbLogError.TB_LOG_ERROR,
            TbMailH.TB_MAIL_H,
            TbMailM.TB_MAIL_M,
            TbMenu.TB_MENU,
            TbMulLang.TB_MUL_LANG,
            TbNotice.TB_NOTICE,
            TbRole.TB_ROLE,
            TbRoleMenu.TB_ROLE_MENU,
            TbRoleUser.TB_ROLE_USER,
            TbScheH.TB_SCHE_H,
            TbScheM.TB_SCHE_M,
            TbSmsH.TB_SMS_H,
            TbSmsM.TB_SMS_M,
            TbUser.TB_USER,
            TbWebSvc.TB_WEB_SVC
        );
    }
}
