/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq;


import com.basic.app.entity.jooq.tables.TbLogApi;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in CBSK-DEV.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TB_LOG_API_IDX_ACCESS_LOG_END_DATE = Internal.createIndex(DSL.name("idx_access_log_end_date"), TbLogApi.TB_LOG_API, new OrderField[] { TbLogApi.TB_LOG_API.END_DATE }, false);
    public static final Index TB_LOG_API_IDX_ACCESS_LOG_IP_END_DATE = Internal.createIndex(DSL.name("idx_access_log_ip_end_date"), TbLogApi.TB_LOG_API, new OrderField[] { TbLogApi.TB_LOG_API.IP_ADDR, TbLogApi.TB_LOG_API.END_DATE }, false);
    public static final Index TB_LOG_API_IDX_ACCESS_LOG_URI_END_DATE = Internal.createIndex(DSL.name("idx_access_log_uri_end_date"), TbLogApi.TB_LOG_API, new OrderField[] { TbLogApi.TB_LOG_API.REQUEST_URI, TbLogApi.TB_LOG_API.END_DATE }, false);
    public static final Index TB_LOG_API_IDX_ACCESS_LOG_USER_END_DATE = Internal.createIndex(DSL.name("idx_access_log_user_end_date"), TbLogApi.TB_LOG_API, new OrderField[] { TbLogApi.TB_LOG_API.USER_ID, TbLogApi.TB_LOG_API.END_DATE }, false);
}
