/*
 * This file is generated by jOOQ.
 */
package com.basic.app.entity.jooq;


import com.basic.app.entity.jooq.tables.TbBbs;
import com.basic.app.entity.jooq.tables.TbBbsComment;
import com.basic.app.entity.jooq.tables.TbChaebun;
import com.basic.app.entity.jooq.tables.TbComCodeD;
import com.basic.app.entity.jooq.tables.TbComCodeDPivot;
import com.basic.app.entity.jooq.tables.TbComCodeM;
import com.basic.app.entity.jooq.tables.TbComCodeT;
import com.basic.app.entity.jooq.tables.TbComCodeTPivot;
import com.basic.app.entity.jooq.tables.TbCompany;
import com.basic.app.entity.jooq.tables.TbDepartment;
import com.basic.app.entity.jooq.tables.TbIf;
import com.basic.app.entity.jooq.tables.TbLogAct;
import com.basic.app.entity.jooq.tables.TbLogApi;
import com.basic.app.entity.jooq.tables.TbLogError;
import com.basic.app.entity.jooq.tables.TbMailH;
import com.basic.app.entity.jooq.tables.TbMailM;
import com.basic.app.entity.jooq.tables.TbMenu;
import com.basic.app.entity.jooq.tables.TbMulLang;
import com.basic.app.entity.jooq.tables.TbNotice;
import com.basic.app.entity.jooq.tables.TbRole;
import com.basic.app.entity.jooq.tables.TbRoleMenu;
import com.basic.app.entity.jooq.tables.TbRoleUser;
import com.basic.app.entity.jooq.tables.TbScheH;
import com.basic.app.entity.jooq.tables.TbScheM;
import com.basic.app.entity.jooq.tables.TbSmsH;
import com.basic.app.entity.jooq.tables.TbSmsM;
import com.basic.app.entity.jooq.tables.TbUser;
import com.basic.app.entity.jooq.tables.TbWebSvc;


/**
 * Convenience access to all tables in CBSK-DEV.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>CBSK-DEV.TB_BBS</code>.
     */
    public static final TbBbs TB_BBS = TbBbs.TB_BBS;

    /**
     * The table <code>CBSK-DEV.TB_BBS_COMMENT</code>.
     */
    public static final TbBbsComment TB_BBS_COMMENT = TbBbsComment.TB_BBS_COMMENT;

    /**
     * The table <code>CBSK-DEV.TB_CHAEBUN</code>.
     */
    public static final TbChaebun TB_CHAEBUN = TbChaebun.TB_CHAEBUN;

    /**
     * The table <code>CBSK-DEV.TB_COM_CODE_D</code>.
     */
    public static final TbComCodeD TB_COM_CODE_D = TbComCodeD.TB_COM_CODE_D;

    /**
     * The table <code>CBSK-DEV.TB_COM_CODE_D_PIVOT</code>.
     */
    public static final TbComCodeDPivot TB_COM_CODE_D_PIVOT = TbComCodeDPivot.TB_COM_CODE_D_PIVOT;

    /**
     * The table <code>CBSK-DEV.TB_COM_CODE_M</code>.
     */
    public static final TbComCodeM TB_COM_CODE_M = TbComCodeM.TB_COM_CODE_M;

    /**
     * The table <code>CBSK-DEV.TB_COM_CODE_T</code>.
     */
    public static final TbComCodeT TB_COM_CODE_T = TbComCodeT.TB_COM_CODE_T;

    /**
     * The table <code>CBSK-DEV.TB_COM_CODE_T_PIVOT</code>.
     */
    public static final TbComCodeTPivot TB_COM_CODE_T_PIVOT = TbComCodeTPivot.TB_COM_CODE_T_PIVOT;

    /**
     * The table <code>CBSK-DEV.TB_COMPANY</code>.
     */
    public static final TbCompany TB_COMPANY = TbCompany.TB_COMPANY;

    /**
     * The table <code>CBSK-DEV.TB_DEPARTMENT</code>.
     */
    public static final TbDepartment TB_DEPARTMENT = TbDepartment.TB_DEPARTMENT;

    /**
     * The table <code>CBSK-DEV.TB_IF</code>.
     */
    public static final TbIf TB_IF = TbIf.TB_IF;

    /**
     * The table <code>CBSK-DEV.TB_LOG_ACT</code>.
     */
    public static final TbLogAct TB_LOG_ACT = TbLogAct.TB_LOG_ACT;

    /**
     * The table <code>CBSK-DEV.TB_LOG_API</code>.
     */
    public static final TbLogApi TB_LOG_API = TbLogApi.TB_LOG_API;

    /**
     * The table <code>CBSK-DEV.TB_LOG_ERROR</code>.
     */
    public static final TbLogError TB_LOG_ERROR = TbLogError.TB_LOG_ERROR;

    /**
     * The table <code>CBSK-DEV.TB_MAIL_H</code>.
     */
    public static final TbMailH TB_MAIL_H = TbMailH.TB_MAIL_H;

    /**
     * The table <code>CBSK-DEV.TB_MAIL_M</code>.
     */
    public static final TbMailM TB_MAIL_M = TbMailM.TB_MAIL_M;

    /**
     * The table <code>CBSK-DEV.TB_MENU</code>.
     */
    public static final TbMenu TB_MENU = TbMenu.TB_MENU;

    /**
     * The table <code>CBSK-DEV.TB_MUL_LANG</code>.
     */
    public static final TbMulLang TB_MUL_LANG = TbMulLang.TB_MUL_LANG;

    /**
     * The table <code>CBSK-DEV.TB_NOTICE</code>.
     */
    public static final TbNotice TB_NOTICE = TbNotice.TB_NOTICE;

    /**
     * The table <code>CBSK-DEV.TB_ROLE</code>.
     */
    public static final TbRole TB_ROLE = TbRole.TB_ROLE;

    /**
     * The table <code>CBSK-DEV.TB_ROLE_MENU</code>.
     */
    public static final TbRoleMenu TB_ROLE_MENU = TbRoleMenu.TB_ROLE_MENU;

    /**
     * The table <code>CBSK-DEV.TB_ROLE_USER</code>.
     */
    public static final TbRoleUser TB_ROLE_USER = TbRoleUser.TB_ROLE_USER;

    /**
     * The table <code>CBSK-DEV.TB_SCHE_H</code>.
     */
    public static final TbScheH TB_SCHE_H = TbScheH.TB_SCHE_H;

    /**
     * The table <code>CBSK-DEV.TB_SCHE_M</code>.
     */
    public static final TbScheM TB_SCHE_M = TbScheM.TB_SCHE_M;

    /**
     * The table <code>CBSK-DEV.TB_SMS_H</code>.
     */
    public static final TbSmsH TB_SMS_H = TbSmsH.TB_SMS_H;

    /**
     * The table <code>CBSK-DEV.TB_SMS_M</code>.
     */
    public static final TbSmsM TB_SMS_M = TbSmsM.TB_SMS_M;

    /**
     * The table <code>CBSK-DEV.TB_USER</code>.
     */
    public static final TbUser TB_USER = TbUser.TB_USER;

    /**
     * The table <code>CBSK-DEV.TB_WEB_SVC</code>.
     */
    public static final TbWebSvc TB_WEB_SVC = TbWebSvc.TB_WEB_SVC;
}
